#!/usr/bin/env python3
"""Snapshot of static/js/canvas.js — the baseline for Phase 8 (turning the kanban into classes).

The behaviour is pinned BEFORE the rewrite, by value: helpers (an agent's
group, a pair's primary port, a client's key and name qualified by host,
history formats, gguf's short name, walking edges to a schedule node),
building `canvasNodes` (inputs, rule nodes of every kind with their ports,
the server block, the embeddings slot), graph operations through
`saveRouters` (a schedule node is born with two outputs, one output on an
in:-port is a replacement, inc: expands into a client's ports, queue/onError
roles hold edge pointers and get cleaned up, a rewire inherits schedPortId,
healing accepts the first free edge as main and converges), the grid-save
queue (one request in flight, the latest grid catches up), the node config
panel, geometry (a world point via the offsetParent chain, anchors, the
curve, connectors with `data-t-id="from->to"` and role classes, the cable
while dragging), dragging (a node → position, and a save through saveRouters
for rule:, otherwise localStorage; panning; connect/rewire → an edge onto the
target), spreading out overlaps, the binder (one binding per world
generation, the palette built once, zoom to cursor 0.35–2.2, queue field
clamps).

The DOM is a selector dict and element models with an offsetParent chain;
neighbors are stubs recording their calls; saveRouters applies the mutator to
a copy.

Run: python3 scripts/test_js_canvas.py
"""
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from caravan.common.queue_policy import SharedQueuePolicy
from _node import find_node, node_search_paths  # noqa: E402

STUBS = ("dialogs,form,llama-edit,polling,remote-cells,routers,topology-activity,topology-proxies,topology-render,"
         "charts,cables,cloud,history,favorites,config-locator,system-panels,onboarding,onboarding-tours,usage-stats,"
         "dialog-llamas,models-page,system-page,memory,command-preview,topology-nodes,topology-modals,topology-dnd,model-meta")

PREAMBLE = r"""
import "./_js_globals.mjs";
import { pathToFileURL } from "node:url";
const st = await import(pathToFileURL(process.env.JS_ROOT + "/state.js").href);
const i18n = await import(pathToFileURL(process.env.JS_ROOT + "/i18n.js").href);
st.setState({ config: {} }); st.setTopology({ proxies: [], clients: [], routers: [], assignments: {} });
globalThis.CSS = { escape: (s) => String(s) }; globalThis.MutationObserver = class { observe() {} };
globalThis.__timers = []; globalThis.setInterval = (fn, ms) => { globalThis.__timers.push("interval:" + ms); return 0; }; globalThis.setTimeout = (fn, ms) => { globalThis.__timers.push("timeout:" + ms); globalThis.__deferred.push(fn); return 0; }; globalThis.__deferred = [];
globalThis.requestAnimationFrame = (fn) => { globalThis.__raf.push(fn); return 0; }; globalThis.__raf = [];
const docListeners = {}; document.addEventListener = (t, fn, opts) => { (docListeners[t] ||= []).push({ fn, capture: opts === true }); };
const winListeners = {}; globalThis.addEventListener = (t, fn) => { (winListeners[t] ||= []).push(fn); };
Date.now = () => 1_700_000_100_000; globalThis.Math.random = () => 0.5;
globalThis.__stubValues = { "topology-activity.stickySlotAnims": {} };
const cls = () => { const s = new Set(); return { add: (...c) => c.forEach((x) => s.add(x)), remove: (...c) => c.forEach((x) => s.delete(x)), toggle: (c, on) => (on === undefined ? (s.has(c) ? s.delete(c) : s.add(c)) : (on ? s.add(c) : s.delete(c))), contains: (c) => s.has(c), has: (c) => s.has(c), list: () => [...s].sort() } };
// Элемент мира: offsetParent-цепочка для геометрии, dataset, стиль, слушатели, querySelector по словарю q/qa.
const mkEl = (props = {}) => { const e = { dataset: {}, classList: cls(), style: {}, listeners: {}, offsetLeft: 0, offsetTop: 0, offsetWidth: 100, offsetHeight: 40, offsetParent: null, parentElement: null, innerHTML: "", value: "", textContent: "",
  addEventListener(t, fn) { (this.listeners[t] ||= []).push(fn); }, closest(sel) { return this.q?.[sel] ?? (this.parentElement ? this.parentElement.closest(sel) : null); }, querySelector(sel) { return this.q?.[sel] ?? null; }, querySelectorAll(sel) { return this.qa?.[sel] ?? []; }, getBoundingClientRect() { return this.rect || { left: 0, top: 0, width: 100, height: 40 }; }, contains: () => false, remove() { this.removed = true; }, ...props }; return e; };
globalThis.__q = {}; globalThis.__qa = {};
document.querySelector = (sel) => (Object.prototype.hasOwnProperty.call(globalThis.__q, sel) ? globalThis.__q[sel] : null);
document.querySelectorAll = (sel) => globalThis.__qa[sel] || [];
document.getElementById = (id) => (Object.prototype.hasOwnProperty.call(globalThis.__fields, id) ? globalThis.__fields[id] : null);
globalThis.__atPoint = null; document.elementFromPoint = () => globalThis.__atPoint;
document.body = { appendChild() {} }; document.createElement = () => mkEl();
globalThis.__calls = [];
const isEventLike = (x) => x && typeof x === "object" && (x.listeners || "target" in x || typeof x.preventDefault === "function");
const arg = (x) => (typeof x === "function" ? "fn" : isEventLike(x) ? null : x);
const rec = (name, ret) => (...a) => { globalThis.__calls.push([name, ...a.map(arg)]); return ret; };
const m = await import(pathToFileURL(process.env.JS_ROOT + "/canvas.js").href);
const qs = await import(pathToFileURL(process.env.JS_ROOT + "/queue-settings.js").href);
const names = () => globalThis.__calls.map((c) => c[0]);
const saved = () => globalThis.__calls.filter((c) => c[0] === "saveRouters").map((c) => c[1]);
const lastSaved = () => saved().at(-1);
const PROXIES = () => [
  { id: "skynet:proxy:23001", port: 23001, label: "hotel primary", clientId: "box-a", upstreamHost: "127.0.0.1", upstreamPort: 22001 },
  { id: "skynet:proxy:23002", port: 23002, label: "hotel fallback", clientId: "box-a" },
  { id: "skynet:proxy:23101", port: 23101, label: "crane", clientId: "box-b" },
  { id: "skynet:proxy:8022", port: 8022, label: "proton", clientId: "" },
];
const ROUTER = (extra = {}) => ({ id: "router:a", inputs: ["skynet:proxy:23001", "skynet:proxy:23002", "skynet:proxy:23101"], outputs: [
  { id: "srv:22001", label: "qwen", upstreamType: "llama", upstreamHost: "127.0.0.1", upstreamPort: 22001 },
  { id: "cb:terra", label: "☁ terra", upstreamType: "cloud", providerId: "cb:terra", accountId: "acct" },
  { id: "srv:22003", label: "embed", upstreamType: "llama", upstreamHost: "127.0.0.1", upstreamPort: 22003 } ],
  rules: { default: "srv:22001", embeddingsOutput: "", bySource: [] },
  graph: { nodes: [
    { id: "q1", type: "queue", x: 300, y: 100, config: { spillPct: 25, admitEdge: "e1", spillEdge: "e2" } },
    { id: "s1", type: "schedule", x: 300, y: 400, config: { outputs: [{ id: "o1", name: "day" }, { id: "o2", name: "night" }], grid: [[null, "o1"]] } },
    { id: "w1", type: "weighted", x: 300, y: 700, config: { weights: [{ edge: "e5", pct: 70 }] } },
    { id: "f1", type: "failover", x: 300, y: 800, config: { order: [] } },
    { id: "oe1", type: "onError", x: 300, y: 900, config: { mainEdge: "e7", rescueEdge: "e8" } },
    { id: "rt1", type: "requestType", x: 300, y: 1000, config: {} },
    { id: "rs1", type: "requestSize", x: 300, y: 1100, config: { maxTokensAt: 500 } } ],
  edges: [
    { id: "e0", from: "in:skynet:proxy:23001", to: "rule:q1" }, { id: "e1", from: "rule:q1", to: "out:srv:22001" }, { id: "e2", from: "rule:q1", to: "out:cb:terra" },
    { id: "e3", from: "rule:s1", to: "out:srv:22001", schedPortId: "o1" }, { id: "e4", from: "rule:s1", to: "out:cb:terra", schedPortId: "__default__" },
    { id: "e5", from: "rule:w1", to: "out:srv:22001" }, { id: "e6", from: "rule:w1", to: "out:cb:terra" },
    { id: "e7", from: "rule:oe1", to: "out:srv:22001" }, { id: "e8", from: "rule:oe1", to: "out:cb:terra" },
    { id: "e9", from: "rule:rt1", to: "out:srv:22003", schedPortId: "embed" }, { id: "e10", from: "rule:rs1", to: "out:srv:22001", schedPortId: "small" } ] }, ...extra });
const TOPO = (extra = {}) => ({ proxies: PROXIES(), clients: [{ id: "box-a", name: "Box A", agents: [{ id: "hotel" }] }, { id: "box-b", name: "Box B", agents: [{ id: "crane" }] }], routers: [ROUTER()], assignments: {
  "box-a": { assignments: [{ agentId: "hotel", routes: [{ role: "primary", proxyId: "skynet:proxy:23001" }, { role: "fallback", proxyId: "skynet:proxy:23002" }] }] },
  "box-b": { assignments: [{ agentId: "crane", routes: [{ role: "primary", proxyId: "skynet:proxy:23101" }] }] } }, cloudProviders: [{ id: "cb:terra", model: "gpt-5.6-terra", unlisted: false }], proxyPolicy: { loadingModelWaitSec: 90 }, ...extra });
const boardClients = (proxies) => { const rows = []; const claimed = new Set(); for (const c of (st.topology.clients || [])) for (const a of ((st.topology.assignments[c.id] || {}).assignments || [])) { const own = []; for (const r of (a.routes || [])) { const p = proxies.find((x) => x.id === r.proxyId); if (p && !claimed.has(p.id)) { own.push(p); claimed.add(p.id); } } if (own.length) rows.push({ key: `${c.id}::${a.agentId}`, clientId: c.id, agentId: a.agentId, proxies: own }); } return { rows, unclaimed: proxies.filter((p) => !claimed.has(p.id)) }; };
const reset = () => { st.setTopology(TOPO()); st.ui.topologyCanvasRouterId = "router:a"; st.ui.topologyRouterNodeCfgId = ""; st.ui.pendingConfirm = null; st.ui.latestSystemMonitor = null; localStorage.clear();
  globalThis.__q = {}; globalThis.__qa = {}; globalThis.__fields = { confirmTitle: mkEl(), confirmText: mkEl(), confirmMeta: mkEl(), confirmPath: mkEl(), confirmDelete: mkEl(), confirmOverlay: mkEl({ hidden: true }), toast: mkEl() }; globalThis.__calls = []; globalThis.__timers.length = 0; globalThis.__deferred.length = 0; globalThis.__raf.length = 0; globalThis.__atPoint = null;
  globalThis.__fetchCalls.length = 0; globalThis.__fetchReply = {};
  for (const k of Object.keys(m._cvQueueHistData)) delete m._cvQueueHistData[k]; for (const k of Object.keys(m._cvQueueHistOpen)) delete m._cvQueueHistOpen[k]; for (const k of Object.keys(m._cvSchedHistData)) delete m._cvSchedHistData[k]; for (const k of Object.keys(m._cvSchedHistOpen)) delete m._cvSchedHistOpen[k]; for (const k of Object.keys(m._cvSchedPaintIds)) delete m._cvSchedPaintIds[k]; for (const k of Object.keys(m._cvSchedWorkingGrids)) delete m._cvSchedWorkingGrids[k]; for (const k of Object.keys(m._cvSchedSaveQueue)) delete m._cvSchedSaveQueue[k]; m._cvSchedCollapsed.clear(); m.ModelQueueNode.open.clear(); qs.QUEUE_SETTINGS.editing = false;
  m.cvSetViewport({}, { tx: 24, ty: 24, scale: 1 });
  globalThis.__stubReturns = { "routers.routerById": (rs, id) => rs.find((r) => r.id === id), "routers.saveRouters": async (mut) => { const copy = JSON.parse(JSON.stringify(st.topology.routers)); mut(copy); globalThis.__calls.push(["saveRouters", copy[0]]); }, "routers.topologyRouterOutputLabel": (o) => o.label || o.id, "routers.renderServersBlockHtml": () => "<div class=\"srv\">SERVERS</div>",
    "topology-proxies.canvasBoardClients": boardClients, "topology-proxies._cvProxyIsTombstoned": () => false, "topology-proxies.topologyMutedProxyIds": () => new Set(), "topology-proxies.topologyProxyOwner": (id) => (id === "skynet:proxy:23001" ? { title: "Hotel" } : null), "topology-proxies.editTopologyProxy": rec("editTopologyProxy"),
    "topology-activity._proxyUpstreamStr": (p) => `${p.upstreamHost || "127.0.0.1"}:${p.upstreamPort || 8080}`, "topology-activity.proxyEffectiveWaitTimeout": () => 1800, "topology-activity.topologyRuntimeOverview": () => globalThis.__overview || { running: [], queued: [] }, "topology-activity.topologyItemGroup": (it) => it.group, "topology-activity.topologyFormatDuration": (ms) => `${Math.round(ms / 1000)}s`, "topology-activity.topologyDurationMs": () => 5000, "topology-activity.topologyQueueRuntime": (it) => ({ timeoutSec: 100, queuedMs: 20000, leftMs: 80000, cloudAt: 40 }), "topology-activity.ensureStickyBarTicker": rec("ensureStickyBarTicker"),
    "topology-render.renderTopology": rec("renderTopology"), "topology-render.refreshTopology": async () => {}, "dialogs.appConfirm": async () => true, "llama-edit.closeConfirmModal": rec("closeConfirmModal"), "form.option": (v, l) => `<option value="${v}">${l}</option>`, "remote-cells.deleteOrphanAgent": rec("deleteOrphanAgent"),
    // output-cells.js finds a cell by its machine (topology-nodes, stubbed here; the real rules
    // are pinned in test_js_output_cells): every address is the machine "m1".
    "topology-nodes.machineAt": () => ({ key: "m1", name: "m1", address: "10.0.0.5" }), "topology-nodes.cellRunnerId": (cfg) => String((cfg || {}).RUNNER || "llama-server"), "topology-nodes.cellJobs": () => ["llm"] };
  globalThis.__overview = null; };
reset();
const settle = async () => { for (let i = 0; i < 4; i++) await new Promise((r) => setImmediate(r)); };
const nodesOf = () => m.canvasNodes(st.topology.routers[0]);
const node = (id) => nodesOf().find((n) => n.id === id);
const panels = () => m.canvasPanels(st.topology.routers[0]);
const out = {};
"""

PINS = [
    # ── helpers ──
    ("agent_group_and_primary_port", '', '[m._cvAgentGroup({ label: "hotel primary" }), m._cvAgentGroup({ label: "hotel  Fallback" }), m._cvAgentGroup({}), m._cvPrimaryPort({ port: 23002 }), m._cvPrimaryPort({ port: 23001 }), m._cvPrimaryPort({ port: "0" }), m._cvPrimaryPort({})]', '["hotel","hotel","",23001,23001,0,0]',
     "имя группы — подпись без суффикса роли; primary пары — нечётный порт (чётный → порт−1)"),
    ("client_key_and_name", '', '[m.canvasClientKey(PROXIES()[1]), m.canvasClientKey(PROXIES()[3]), m.canvasClientName(PROXIES()[0]), m.canvasClientName(PROXIES()[1]), m.canvasClientName(PROXIES()[2]), m.canvasClientName(PROXIES()[3])]', '["box-a::23001","::8021","hotel","hotel","crane","proton"]',
     "ключ клиента — хост::primary-порт (as-is: без хоста, но с портом — «::порт», id только когда нет обоих); имя — агент из назначений, иначе подпись"),
    ("client_name_qualified_by_host_when_duplicated", 'st.topology.assignments["box-b"].assignments[0].agentId = "hotel";', '[m.canvasClientName(PROXIES()[0]), m.canvasClientName(PROXIES()[2])]', '["hotel · box-a","hotel · box-b"]', "одноимённые агенты на двух хостах квалифицируются хостом"),
    ("client_name_fallbacks_without_assignment", 'st.setTopology(TOPO({ assignments: {} }));', '[m.canvasClientName({ id: "x", label: "box-a", clientId: "box-a", port: 23005 }), m.canvasClientName({ id: "x", label: "box-a", clientId: "box-a" }), m.canvasClientName({ id: "raw", label: "" })]', '["box-a:23005","box-a","raw"]',
     "без назначения: подпись; подпись = хост → хост:primary; ни того ни другого — id"),
    ("hist_formats", '', '[m._cvQHistFmt(null), m._cvQHistFmt(999), m._cvQHistFmt(1500), m._cvQHistFmt(60000), m._cvQHistFmt(125000), m._cvQHistModel({ queue: { cloudFallback: true }, model: "gpt" }), m._cvQHistModel({ stream: { model: "/m/Qwen_Qwen3.6-27B-Q5_K_L.gguf" } }), m._cvQHistModel({ model: "plain" }), m._cvQHistModel({})]',
     '["—","999ms","1.5s","1m","2m 5s",{"text":"gpt","overflow":true},{"text":"Qwen3.6-27B","overflow":false},{"text":"plain","overflow":false},{"text":"?","overflow":false}]', "формат длительности; имя модели: облако — как есть с пометкой, gguf — семейство-размер"),
    ("port_display_name_and_hist_route", '', '[m._portDisplayName(23001), m._portDisplayName(23001, { short: true }), m._portDisplayName(23001, { nameOnly: true }), m._portDisplayName(23101), m._portDisplayName(0), m._cvQHistRoute({ item: { port: 23001 } }), m._cvQHistRoute({ route: "box · hotel fallback" }), m._cvQHistRoute({})]',
     '["Hotel :23001","Hotel:01","Hotel",":23101",":????","Hotel:01","hotel",":?"]', "имя порта: владелец с портом (коротко — две цифры), без владельца — порт; маршрут истории — порт, иначе подпись без роли и хоста"),
    ("sched_input_ports_walk_backwards", '', '(() => { const r = ROUTER(); r.graph.edges.push({ id: "x", from: "in:skynet:proxy:23101", to: "rule:w1" }, { id: "y", from: "rule:w1", to: "rule:s1" }); return [[...m._cvSchedInputPorts(r, "s1")].sort(), [...m._cvSchedInputPorts(r, "q1")], [...m._cvSchedInputPorts(r, "nope")]]; })()', '[[23101],[23001],[]]',
     "порты, доходящие до узла расписания, — обход рёбер назад через промежуточные узлы"),
    ("sched_grid_color_now", '', '(() => { const g = m._cvSchedMakeGrid({ grid: [[null, "o1"]] }); const now = m._cvSchedNow(); return [g.length, g[0].length, g[0][1], g[0][0], g[6][23], m._cvSchedColor([{ id: "a" }, { id: "b" }], "b"), m._cvSchedColor([], "a"), now.d >= 0 && now.d <= 6, /^\\d\\d:\\d\\d$/.test(now.timeStr)]; })()', '[7,24,"o1",null,null,"#f59e0b","",true,true]',
     "сетка 7×24 из частичного конфига, пустое — null; цвет по индексу выхода; «сейчас» — день Пн=0 и часы:минуты"),
    ("labels_summary_edges", '', '(() => { const r = ROUTER(); return [m.cvNodeTypeLabel("queue"), m.cvNodeTypeLabel("zzz"), m._ruleNodeSummary({ type: "weighted", config: { weights: [{ pct: 70 }, { pct: 30 }] } }), m._ruleNodeSummary({ type: "queue", config: { maxSlots: 4, spillPct: 10 } }).includes("spill 20%"), m._ruleNodeSummary({ type: "roundRobin" }).length > 0, m.edgeTargetLabel(r, { to: "out:cb:terra" }), m.edgeTargetLabel(r, { to: "rule:q1" }), m.edgeTargetLabel(r, { to: "out:gone" }), m.graphOutEdges(r, "q1").map((e) => e.id), m.clientProxyInputRefs(r, "box-a::23001"), m._isSingleOut("in:x"), m._isSingleOut("rule:x")]; })()',
     '["queue","zzz","70% / 30%",true,true,"☁ terra","⏳ queue","gone",["e1","e2"],["in:skynet:proxy:23001","in:skynet:proxy:23002"],true,false]', "подписи типов, сводки, подпись цели ребра (выход — подпись, узел — глиф+тип, пропавший — id), исходящие рёбра, входы клиента, одиночный выход у in:"),
    ("paths_positions_viewport", '', '(() => { localStorage.setItem("cvpos:router:a", JSON.stringify({ "rule:q1": { x: 509, y: 359 } })); localStorage.setItem("cvpos:router:b", "{}"); const opened = m.canvasOpenPositions("router:a"); return [m._cvPathD({ x: 0, y: 0 }, { x: 200, y: 100 }), opened, localStorage.getItem("cvpos:router:a"), localStorage.getItem("cvpos:router:b"), m.canvasPosKey("r")]; })()',
     '["M 0 0 C 96 0, 104 100, 200 100",{},null,"{}","cvpos:r"]', "кривая с плечом 48%; место узла правила — только на сервере: холст открывается без своих мест, а старая копия браузера (cvpos:<роутер>) стирается при открытии — она побеждала сервер и отменяла перетаскивания оператора; negative: копия другого роутера не тронута, пока его не откроют"),
    ("client_to_world", '', '(() => { globalThis.__q["[data-cv-viewport]"] = mkEl({ rect: { left: 100, top: 50 } }); m.cvSetViewport({}, { tx: 24, ty: 24, scale: 2 }); const p = m._cvClientToWorld(324, 274); m.cvSetViewport({}, { tx: 24, ty: 24, scale: 1 }); return p; })()', '{"x":100,"y":100}', "экранная точка → мир: минус вьюпорт, минус пан, делить на масштаб"),
    ("initial_view_puts_the_nodes_in_from_the_corner", '', '(() => { const r = st.topology.routers[0]; const plain = m.canvasInitialView("router:a"); r.graph.nodes[0].modelOutputId = "srv:22001"; const withoutQueue = m.canvasInitialView("router:a"); r.graph.nodes.forEach((n) => { n.x = undefined; n.y = undefined; }); const noCoords = m.canvasInitialView("router:a"); return [plain, withoutQueue, noCoords, m.canvasInitialView("router:zzz"), m.Board.initialView({ graph: { nodes: [] } })]; })()',
     '[{"tx":-276,"ty":-76,"scale":1},{"tx":-276,"ty":-376,"scale":1},{"tx":24,"ty":24,"scale":1},{"tx":24,"ty":24,"scale":1},{"tx":24,"ty":24,"scale":1}]', "холст открывается так, что левый верхний угол узлов правил стоит в 24 px от угла; узел очереди модели в расчёт не идёт (он не на холсте); нет координат, нет роутера, нет узлов — прежние 24/24"),
    ("fit_view_shows_the_box_whole", '', '[m.Board.fitView({ x: 0, y: 0, w: 1000, h: 500 }, 800, 600), m.Board.fitView({ x: 100, y: 50, w: 200, h: 100 }, 800, 600), m.Board.fitView({ x: -50, y: 0, w: 10000, h: 100 }, 800, 600), m.Board.boxOf([{ x: 10, y: 20, w: 30, h: 40 }, { x: -5, y: 100, w: 10, h: 10 }])]',
     '[{"scale":0.736,"tx":32,"ty":116},{"scale":1,"tx":200,"ty":200},{"scale":0.35,"tx":-1332,"ty":283},{"x":-5,"y":20,"w":45,"h":90}]',
     "⤢ Show all: рамка вокруг узлов целиком и по центру окна с полями 32 px; мелкая рамка не увеличивается больше 1:1; огромная — не мельче предела колеса 0.35; рамка — по краям прямоугольников"),
    ("queue_live_stats", 'globalThis.__overview = { running: [{ group: "127.0.0.1:22001" }, { group: "127.0.0.1:22001" }, { group: "other" }], queued: [{ group: "127.0.0.1:22001", queue: { queuedMs: 40000, timeoutSec: 85 } }] }; st.ui.latestSystemMonitor = { latest: { agentProxies: { slotTotals: { "127.0.0.1:22001": 4 } } } };',
     '(() => { const r = ROUTER(); const q = r.graph.nodes[0]; return [m.queueNodeLiveStats(r, q), m.queueNodeLiveStats(r, { id: "q1", config: { admitEdge: "e2" } }), m.queueNodeLiveStats(r, { id: "zzz", config: {} })]; })()',
     '[{"group":"127.0.0.1:22001","running":2,"queued":1,"slots":4,"waitPct":40},null,null]', "живая статистика очереди: по группе admit-выхода — бегущие, ждущие, слоты из монитора, прогресс ожидания к полному таймауту (85 с при abort 85% = 100 с → 40%); облачный admit или без рёбер — null"),
    # ── canvasNodes ──
    ("nodes_ids_and_positions", '', '(() => nodesOf().map((n) => [n.id, n.type, n.fixed?.x, n.fixed?.y]))()', '[["rule:q1","rule",300,100],["rule:s1","rule",300,400],["rule:w1","rule",300,700],["rule:f1","rule",300,800],["rule:oe1","rule",300,900],["rule:rt1","rule",300,1000],["rule:rs1","rule",300,1100]]',
     "узлы холста: только узлы правил по своим x/y в порядке графа; клиентов и серверов среди узлов больше нет — это боковые панели"),
    ("inputs_block_rows", '', '(() => { const h = panels().left; return [(h.match(/cv-inputs-client /g) || []).length, h.includes(\'data-cv-in-row="in:skynet:proxy:23001"\'), h.includes(\'data-cv-in-row="in:skynet:proxy:23002"\'), h.includes("cv-in-row primary"), h.includes("cv-in-row fallback unwired"), h.includes("↳"), h.includes("wait 1800s") || h.includes("1800"), h.includes("kanban-unclaimed"), h.includes("data-cv-reconcile"), h.includes("cv-orphan-agents")]; })()',
     '[2,true,true,true,true,true,true,false,false,false]', "панель клиентов: строка на агента с P и F (фолбэк без ребра — «↳ follows»), бюджет ожидания, непринадлежащих нет; кнопки сверки с живыми отчётами и полосы мёртвых агентов больше нет — их знание пришло от скаута"),
    ("inputs_block_empty_says_so", 'st.topology.routers[0].inputs = [];', '(() => { const h = panels().left; return [h.includes("cv-inputs-client"), h.includes("${"), h.includes(i18n.t("cvNoProxyPorts"))]; })()', '[false,false,true]',
     "роутер без портов: блок клиентов пуст и говорит это словами из en.js, а не буквальным `${…}`"),
    ("inputs_block_unclaimed_and_no_orphans", 'st.setTopology(TOPO({ orphanedAgents: [{ agentId: "ghost", clientId: "box-z", ports: [23901] }] })); st.topology.routers[0].inputs.push("skynet:proxy:8022");', '(() => { const h = panels().left; return [h.includes("kanban-unclaimed"), h.includes(":8022"), h.includes("cv-orphan-agents"), h.includes("ghost · box-z"), h.includes(":23901"), h.includes(\'data-cv-orphan-agent="ghost"\')]; })()',
     '[true,true,false,false,false,false]', "порт без владельца назван непринадлежащим; старое поле orphanedAgents ничего не рисует — «мёртвых» агентов называл отчёт скаута, а теперь удаление агента уносит и его строку"),
    ("queue_node_html", '', '(() => { const h = node("rule:q1").html; return [h.includes("cv-q-dest admit") && h.includes("cv-q-dest spill"), h.includes(\'data-cv-qrole="admit"\'), h.includes(\'data-cv-qrole="spill"\'), h.includes(">qwen<") || h.includes("qwen"), h.includes("☁ terra"), h.includes(\'data-cv-q="spillPct" value="25"\'), h.includes(\'data-cv-q="loadingModelWaitSec" value="90"\'), h.includes("cv-q-warn"), h.includes(\'data-cv-q-live="q1"\'), h.includes("cv-port in"), h.includes(\'data-cv-delnode="q1"\'), h.includes("cv-q-hist-toggle")]; })()',
     '[true,true,true,true,true,false,false,false,true,true,true,true]', "узел очереди: main/overflow с ролевыми портами и подписями целей, общие поля отсутствуют, без предупреждений, живая область, вход, удаление, история"),
    ("queue_node_warns_on_dead_or_unlisted_target", 'st.topology.routers[0].outputs.splice(0, 1); st.topology.cloudProviders[0].unlisted = true;', '(() => { const h = node("rule:q1").html; return [(h.match(/cv-q-warn/g) || []).length, h.includes("main:"), h.includes("overflow:")]; })()', '[2,true,true]',
     "предупреждения: у admit пропал выход, у spill блок не в списке провайдера"),
    ("queue_live_html_empty_and_busy", '', '(() => { const r = ROUTER(); const empty = m.queueNodeLiveHtml(r, r.graph.nodes[0]); globalThis.__overview = { running: [{ group: "127.0.0.1:22001", port: 23001, startedAt: 1 }], queued: [{ group: "127.0.0.1:22001", port: 23101, queue: { position: 1, queuedMs: 20000, timeoutSec: 100 } }] }; const busy = m.queueNodeLiveHtml(r, r.graph.nodes[0]); return [empty.includes("cv-q-empty"), empty.includes("cv-q-qd idle"), busy.includes("cv-q-now-row running"), busy.includes("Hotel :23001"), busy.includes("→ main"), busy.includes("⏳ 1"), busy.includes("cv-q-wait-row"), busy.includes("cv-q-bar-mk spill"), busy.includes("width:20%")]; })()',
     '[true,true,true,true,true,true,true,true,true]', "живая область: пусто — «нет активных», idle; занято — бегущий с именем порта и «→ main», счётчик ждущих, строка ожидания с заливкой 20% и меткой spill"),
    ("schedule_node_html_expanded_and_collapsed", '', '(() => { const h = node("rule:s1").html; m._cvSchedCollapsed.add("s1"); const c = node("rule:s1").html; return [(h.match(/data-cv-sched-cell="s1"/g) || []).length, (h.match(/data-cv-sched-chip="s1:/g) || []).length, h.includes(\'data-cv-sched-port="o1"\'), h.includes(\'data-cv-sched-port="__default__"\'), h.includes("cv-sched-row--active") && h.includes(\'data-cv-sched-chip="s1:o1"\'), h.includes("+ output"), h.includes("cv-port in"), c.includes("cv-sched-chip-stub"), (c.match(/data-cv-sched-port=/g) || []).length, c.includes("cv-sched-gcal")]; })()',
     '[168,3,true,true,true,true,true,true,3,false]', "расписание раскрыто: 168 клеток, строки двух выходов + default (первый выход — кисть), порт на каждом; свёрнуто — только заглушки портов, без сетки"),
    ("other_rule_nodes_html", '', '(() => { const w = node("rule:w1").html, f = node("rule:f1").html, oe = node("rule:oe1").html, rt = node("rule:rt1").html, rs = node("rule:rs1").html; return [w.includes(\'data-cv-cfgnode="w1"\') && w.includes(\'data-cv-port="out"\'), w.includes("70%"), f.includes("data-cv-cfgnode"), oe.includes(\'data-cv-qrole="main"\') && oe.includes(\'data-cv-qrole="rescue"\'), oe.includes("data-cv-cfgnode"), rt.includes(\'data-cv-sched-port="embed"\') && rt.includes(\'data-cv-sched-port="__default__"\'), rt.includes(\'cv-q-dest spill"\') && rt.includes("cv-q-dest admit unset"), rs.includes(\'data-cv-q="maxTokensAt" value="500"\'), rs.includes(\'data-cv-sched-port="small"\')]; })()',
     '[true,true,true,true,false,true,true,true,true]', "weighted/failover — шестерёнка и общий выход; onError — main/rescue без шестерёнки; requestType — embed привязан, default без ребра — unset; requestSize — порог и порт small"),
    ("request_type_global_note", 'st.topology.routers[0].rules.embeddingsOutput = "srv:22003";', '(() => { const rt = node("rule:rt1").html; const inp = panels().left; return [rt.includes("cv-q-note"), inp.includes("cv-embed-slot assigned"), inp.includes(\'<option value="srv:22003" selected>\'), inp.includes("cb:terra")]; })()', '[true,true,true,false]',
     "глобальный слот embeddings назначен: узел by-type предупреждает, слот показывает выбор; облачные выходы в слот не попадают"),
    ("servers_panel_uses_servers_renderer", '', '(() => { const h = panels().right; return [h.includes("SERVERS"), h.includes(`<div class="rw-side-body"><div class="srv">SERVERS</div>`)]; })()',
     '[true,true]', "панель серверов рисует renderServersBlockHtml внутри своего прокручиваемого тела"),
    ("side_panels_are_asides_not_nodes", '', '(() => { const { left: l, right: r } = panels(); const at = (h, ...keys) => keys.map((k) => h.indexOf(k)); const [lh, lb, lf] = at(l, "rw-side-head", "rw-side-body", "rw-side-foot"); const [rh, rs, rb] = at(r, "rw-side-head", "data-cv-queue-settings", "rw-side-body"); return [l.startsWith(`<aside class="rw-side rw-clients" data-t="kanban-node" data-t-id="inputs:block"`), r.startsWith(`<aside class="rw-side rw-servers" data-t="kanban-node" data-t-id="outputs:block"`), lh < lb && lb < lf, l.includes(`<div class="rw-side-foot"><div class="cv-embed-slot `), rh < rs && rs < rb, l.includes("data-cv-node"), r.includes("data-cv-node"), l.endsWith("</aside>"), r.endsWith("</aside>")]; })()',
     '[true,true,true,true,true,false,false,true,true]', "панели — это aside с прежними хуками kanban-node, а не узлы холста: шапка, прокручиваемое тело, подвал (слот embeddings под строками клиентов), строка политики между шапкой и телом серверов; data-cv-node у них нет"),
    ("side_panels_split_into_the_band_and_the_rows", '', '(() => { const { left: l, right: r } = panels(); const inner = (h) => h.slice(h.indexOf(">") + 1, h.lastIndexOf("</aside>")); const lm = inner(l).indexOf(`</div><div class="rw-side-main"><div class="rw-side-body">`), rt = inner(r).indexOf(`<div class="rw-side-top"><div class="rw-side-head">`); return [inner(l).startsWith(`<div class="rw-side-head">`), lm > 0, inner(l).endsWith("</div></div>") && inner(l).indexOf("rw-side-foot") > lm, rt === 0, inner(r).indexOf("data-cv-queue-settings") < inner(r).indexOf(`</div><div class="rw-side-body">`), inner(r).endsWith("</div>")]; })()',
     '[true,true,true,true,true,true]',
     "у каждой панели две части — по одной на строку общей полосы доски (canvas.css, subgrid): у клиентов шапка, затем строки со слотом embeddings вместе; "
     "у серверов шапка со строкой политики очередей вместе, затем строки; так строки обеих панелей начинаются там, где холст (канат первого клиента "
     "резался краем холста, когда палитра вставала в две строки)"),
    # ── graph operations ──
    ("add_rule_node_schedule_gets_two_outputs", 'globalThis.__q["[data-cv-viewport]"] = mkEl({ clientWidth: 800, clientHeight: 600 });', 'await (async () => { m.addRuleNode("schedule"); await settle(); const sn = lastSaved().graph.nodes.at(-1); return [sn.type, sn.config.outputs.length, sn.config.grid.length, sn.x, sn.y, sn.id.startsWith("n")]; })()',
     '["schedule",2,7,376,276,true]', "новый узел в центре вьюпорта (с учётом пана 24); расписание рождается с двумя выходами и пустой сеткой"),
    ("delete_rule_node_confirms_and_drops_edges", '', 'await (async () => { globalThis.__stubReturns["dialogs.appConfirm"] = async () => false; await m.deleteRuleNode("q1"); const refused = saved().length; globalThis.__stubReturns["dialogs.appConfirm"] = async () => true; await m.deleteRuleNode("q1"); await settle(); const g = lastSaved().graph; return [refused, g.nodes.some((n) => n.id === "q1"), g.edges.filter((e) => e.from === "rule:q1" || e.to === "rule:q1").length, g.edges.length]; })()',
     '[0,false,0,8]', "удаление узла: без подтверждения ничего; с ним — узел и все его рёбра (входящие и исходящие) сняты"),
    ("add_edge_single_out_replaces_for_ports", '', 'await (async () => { m.addGraphEdge("in:skynet:proxy:23001", "rule:w1"); await settle(); const g = lastSaved().graph; return [g.edges.filter((e) => e.from === "in:skynet:proxy:23001").map((e) => e.to), g.edges.length]; })()', '[["rule:w1"],11]',
     "порт клиента имеет один выход: новое ребро заменяет прежнее"),
    ("add_edge_inc_expands_and_dedupes", '', 'await (async () => { m.addGraphEdge("inc:box-a::23001", "rule:w1"); await settle(); const g = lastSaved().graph; m.addGraphEdge("rule:w1", "out:srv:22001"); await settle(); return [g.edges.filter((e) => e.to === "rule:w1").map((e) => e.from).sort(), lastSaved().graph.edges.filter((e) => e.from === "rule:w1" && e.to === "out:srv:22001").length, saved().length]; })()',
     '[["in:skynet:proxy:23001","in:skynet:proxy:23002"],1,2]', "inc:клиент раскрывается в ребро на каждый порт клиента; дубль ребра узла не добавляется"),
    ("add_edge_noops", '', 'await (async () => { m.addGraphEdge("", "rule:w1"); m.addGraphEdge("rule:w1", "rule:w1"); m.addGraphEdge("rule:w1", "out:x", "admit"); await settle(); return [saved().length, lastSaved().graph.edges.length]; })()', '[1,11]', "negative: пустой источник и петля — без записи; роль у узла не-очереди — as-is: saveRouters вызван, но граф не тронут (11 рёбер)"),
    ("add_edge_queue_role_replaces_and_points", '', 'await (async () => { m.addGraphEdge("rule:q1", "out:srv:22003", "spill"); await settle(); const g = lastSaved().graph; const q = g.nodes.find((n) => n.id === "q1"); const spill = g.edges.find((e) => e.id === q.config.spillEdge); return [g.edges.some((e) => e.id === "e2"), spill.to, q.config.admitEdge, g.edges.filter((e) => e.from === "rule:q1").length]; })()',
     '[false,"out:srv:22003","e1",2]', "роль очереди: прежнее ребро роли снято, новое записано в указатель роли, другая роль нетронута"),
    ("add_edge_sched_port_replaces_per_port", '', 'await (async () => { m.addGraphEdge("rule:s1", "out:srv:22003", null, "o1"); await settle(); const g = lastSaved().graph; return [g.edges.filter((e) => e.from === "rule:s1" && e.schedPortId === "o1").map((e) => e.to), g.edges.some((e) => e.id === "e4")]; })()', '[["out:srv:22003"],true]',
     "порт расписания: ровно одно ребро на порт, чужие порты нетронуты"),
    ("rewire_keeps_sched_port_and_role_pointer", '', 'await (async () => { m.rewireGraphEdge("rule:s1", "out:srv:22001", "out:srv:22003"); await settle(); const a = lastSaved().graph.edges.find((e) => e.from === "rule:s1" && e.to === "out:srv:22003"); m.rewireGraphEdge("rule:q1", "out:srv:22001", "out:srv:22003"); await settle(); const g = lastSaved().graph; const q = g.nodes.find((n) => n.id === "q1"); const admit = g.edges.find((e) => e.id === q.config.admitEdge); return [a.schedPortId, g.edges.some((e) => e.id === "e1"), admit.to, q.config.spillEdge]; })()',
     '["o1",false,"out:srv:22003","e2"]', "перецепка: тег порта расписания наследуется; указатель роли очереди переезжает на новое ребро"),
    ("rewire_noops_and_delete_between", '', 'await (async () => { m.rewireGraphEdge("rule:q1", "out:srv:22001", "out:srv:22001"); m.rewireGraphEdge("", "a", "b"); await settle(); const none = saved().length; m.deleteGraphEdgesBetween("inc:box-a::23001", "rule:q1"); await settle(); const g = lastSaved().graph; m.deleteGraphEdgesBetween("rule:q1", "out:srv:22001"); await settle(); const q = lastSaved().graph.nodes.find((n) => n.id === "q1"); return [none, g.edges.some((e) => e.id === "e0"), q.config.admitEdge, q.config.spillEdge]; })()',
     '[0,false,"","e2"]', "перецепка в ту же цель или без источника — ничего; удаление между inc: и узлом снимает рёбра всех портов клиента; удалённое ребро роли чистит её указатель"),
    ("heal_adopts_free_edge_and_converges", '', 'await (async () => { m.healQueueNodeEdges(); await settle(); const healthy = saved().length; st.topology.routers[0].graph.nodes[0].config = { spillEdge: "e2" }; m.healQueueNodeEdges(); await settle(); const q = lastSaved().graph.nodes.find((n) => n.id === "q1"); return [healthy, q.config.admitEdge]; })()', '[0,"e1"]',
     "лечение: здоровый граф не пишется; узел без admit принимает первое свободное ребро (не spill)"),
    ("sched_save_grid_queue", '', 'await (async () => { let resolve; globalThis.__stubReturns["routers.saveRouters"] = (mut) => new Promise((r) => { resolve = () => { const copy = JSON.parse(JSON.stringify(st.topology.routers)); mut(copy); globalThis.__calls.push(["saveRouters", copy[0]]); r(); }; }); m._cvSchedSaveGrid("s1", [["A"]]); m._cvSchedSaveGrid("s1", [["B"]]); m._cvSchedSaveGrid("s1", [["C"]]); const inflight = [saved().length, m._cvSchedSaveQueue.s1.pending[0][0]]; resolve(); await settle(); const after = [saved().length]; resolve(); await settle(); return [...inflight, ...after, saved().map((s) => s.graph.nodes.find((n) => n.id === "s1").config.grid[0][0])]; })()',
     '[0,"C",1,["A","C"]]', "очередь сохранений сетки: пока запрос в полёте, копится ТОЛЬКО последняя сетка и уходит следом — промежуточная B не пишется"),
    ("save_node_config_and_panel", '', 'await (async () => { m.saveNodeConfig("w1", (c) => { c.weights = [{ edge: "e5", pct: 60 }]; }); await settle(); st.ui.topologyRouterNodeCfgId = "w1"; const w = m.renderRouterNodeConfig(st.topology.routers[0]); st.ui.topologyRouterNodeCfgId = "f1"; const f = m.renderRouterNodeConfig(st.topology.routers[0]); st.ui.topologyRouterNodeCfgId = "q1"; const q = m.renderRouterNodeConfig(st.topology.routers[0]); st.ui.topologyRouterNodeCfgId = "zzz"; const none = m.renderRouterNodeConfig(st.topology.routers[0]); return [lastSaved().graph.nodes.find((n) => n.id === "w1").config.weights[0].pct, w.includes("data-cfg-weight") && w.includes(\'value="70"\'), (f.match(/data-cfg-ord-id=/g) || []).length, q.includes(\'data-cfg-q="spillPct"\'), none]; })()',
     '[60,true,0,false,""]', "конфиг узла сохраняется патчем; панель: веса по рёбрам, порядок failover (без рёбер — пусто), поля очереди; неизвестный узел — пусто"),
    # ── geometry and connectors ──
    ("world_point_sums_offsets", '', '(() => { const world = mkEl({ classList: (() => { const c = cls(); c.add("cv-world"); return c; })() }); const nodeEl = mkEl({ offsetLeft: 100, offsetTop: 50, offsetWidth: 200, offsetHeight: 80, offsetParent: world }); const port = mkEl({ offsetLeft: 190, offsetTop: 30, offsetWidth: 16, offsetHeight: 16, offsetParent: nodeEl }); return [m._cvWorldPoint(port, "right"), m._cvWorldPoint(port, "center"), m._cvWorldPoint(nodeEl, "left")]; })()',
     '[{"x":306,"y":88},{"x":298,"y":88},{"x":100,"y":90}]', "точка мира суммирует смещения до cv-world: правый край, центр, левый край"),
    # ── the backup node: output health and the ▶ for the next request come from proxy state, not a recomputation ──
    ("onerror_rows_default", '', '(() => { const h = node("rule:oe1").html; const rows = h.split(/class="cv-q-dest/).slice(1); const cls = (r) => (r.match(/cv-oe-state (\\w+)/) || [])[1]; const tip = (r) => (r.match(/cv-oe-state \\w+" title="([^"]*)"/) || [])[1]; return [rows.length, /cv-oe-next" title="the next request goes here">▶/.test(rows[0]), /cv-oe-next off/.test(rows[1]), cls(rows[0]), tip(rows[0]), cls(rows[1]), /data-cv-oe-live="oe1"/.test(h)]; })()',
     '[2,true,true,"unknown","not checked yet","unknown",true]',
     "без отчёта прокси: ▶ у main (это и есть правило прокси, когда он ничего не знает), оба выхода «ещё не проверялись», живая область помечена id узла"),
    ("onerror_rows_from_monitor", 'st.ui.latestSystemMonitor = { latest: { agentProxies: { outputHealth: { "srv:22001": { state: "error", status: 429, kind: "http 429", message: "quota gone", ageSec: 120, fresh: true, retryInSec: 180 }, "cb:terra": { state: "ok", ageSec: 5, fresh: true, retryInSec: 295 } }, onErrorNext: { oe1: { next: "backup", reason: "main is down: http 429" } } } } };', '(() => { const h = node("rule:oe1").html; const rows = h.split(/class="cv-q-dest/).slice(1); const cls = (r) => (r.match(/cv-oe-state (\\w+)/) || [])[1]; const tip = (r) => (r.match(/cv-oe-state \\w+" title="([^"]*)"/) || [])[1]; return [/cv-oe-next off/.test(rows[0]), /cv-oe-next" title="the next request goes here">▶/.test(rows[1]), cls(rows[0]), tip(rows[0]), cls(rows[1]), tip(rows[1])]; })()',
     '[true,true,"error","down (http 429: quota gone) — 2m ago; re-checked in 3m","ok","alive — checked 5s ago"]',
     "из отчёта: main мёртв (429, квота) — ▶ уходит на backup, точка красная с причиной, возрастом и сроком перепроверки; backup жив — зелёная с возрастом"),
    ("onerror_rows_stale", 'st.ui.latestSystemMonitor = { latest: { agentProxies: { outputHealth: { "srv:22001": { state: "error", status: 429, kind: "http 429", message: "quota gone", ageSec: 420, fresh: false, retryInSec: 0 } }, onErrorNext: { oe1: { next: "main", reason: "" } } } } };', '(() => { const h = node("rule:oe1").html; const rows = h.split(/class="cv-q-dest/).slice(1); const cls = (r) => (r.match(/cv-oe-state (\\w+)/) || [])[1]; const tip = (r) => (r.match(/cv-oe-state \\w+" title="([^"]*)"/) || [])[1]; return [/cv-oe-next" title/.test(rows[0]), cls(rows[0]), tip(rows[0])]; })()',
     '[true,"stale","last verdict: http 429: quota gone, 7m ago — re-checked on the next request"]',
     "истёкший вердикт: ▶ снова у main, точка янтарная — «последний вердикт … перепроверится на следующем запросе», а не мёртвый"),
    ("onerror_sync_live", 'const oeEl = mkEl({ getAttribute: () => "oe1", innerHTML: "" }); globalThis.__qa["[data-cv-oe-live]"] = [oeEl]; st.ui.latestSystemMonitor = { latest: { agentProxies: { outputHealth: { "srv:22001": { state: "error", status: 429, kind: "http 429", message: "quota gone", ageSec: 120, fresh: true, retryInSec: 180 }, "cb:terra": { state: "ok", ageSec: 5, fresh: true, retryInSec: 295 } }, onErrorNext: { oe1: { next: "backup", reason: "main is down: http 429" } } } } }; m.syncQueueNodesLive();', '(() => { const rows = oeEl.innerHTML.split(/class="cv-q-dest/).slice(1); return [rows.length, /cv-oe-next off/.test(rows[0]), /▶/.test(rows[1])]; })()',
     '[2,true,true]',
     "тик монитора перепатчивает только живую область узла: ▶ переехал на backup без полной перерисовки"),
    ("onerror_chained_exit", 'st.ui.latestSystemMonitor = { latest: { agentProxies: { outputHealth: { "srv:22010": { state: "ok", checkedAt: 1699999993, ageSec: 7, fresh: true, retryInSec: 293 }, "srv:22001": { state: "error", status: 429, kind: "http 429", message: "quota", ageSec: 10, fresh: true, retryInSec: 290 } }, onErrorNext: { oe1: { next: "main", reason: "", main: "srv:22010", mainChain: ["q1"], mainName: "Muse :22010" } } } } };',
     '(() => { const h = node("rule:oe1").html; const rows = h.split(/class="cv-q-dest/).slice(1); const cls = (r) => (r.match(/cv-oe-state (\\w+)/) || [])[1]; const label = (r) => (r.match(/cv-q-dt" title="([^"]*)"/) || [])[1]; return [cls(rows[0]), label(rows[0]), /cv-oe-cd/.test(rows[0])]; })()',
     '["ok","qwen → Muse :22010",true]',
     "выход в узел: здоровье и отсчёт берутся у КОНЕЧНОГО выхода, названного прокси (srv:22010 — жив), а подпись говорит через что: «… → Muse :22010»; вердикт выхода, куда ведёт само ребро (429), к этой строке отношения не имеет"),
    ("onerror_chain_named_by_the_board", 'st.ui.latestSystemMonitor = { latest: { agentProxies: { outputHealth: { "srv:22003": { state: "ok", checkedAt: 1699999993, ageSec: 7, fresh: true, retryInSec: 293 } }, onErrorNext: { oe1: { next: "main", reason: "", main: "srv:22003", mainChain: ["q1"], mainName: "srv:22003" } } } } };',
     '(() => { const rows = node("rule:oe1").html.split(/class="cv-q-dest/).slice(1); return (rows[0].match(/cv-q-dt" title="([^"]*)"/) || [])[1]; })()',
     '"qwen → embed"',
     "выход, который доска знает, называется её же словами («embed», как на канате), а не голым id из отчёта: одна модель — одно имя на экране"),
    ("onerror_chain_unnamed", 'st.ui.latestSystemMonitor = { latest: { agentProxies: { outputHealth: { "srv:22001": { state: "ok", ageSec: 7, fresh: true, retryInSec: 293 } }, onErrorNext: { oe1: { next: "main", reason: "", main: null, mainChain: ["rr1"], mainName: null } } } } };',
     '(() => { const h = node("rule:oe1").html; const rows = h.split(/class="cv-q-dest/).slice(1); const cls = (r) => (r.match(/cv-oe-state (\\w+)/) || [])[1]; const label = (r) => (r.match(/cv-q-dt" title="([^"]*)"/) || [])[1]; return [cls(rows[0]), label(rows[0])]; })()',
     '["ok","qwen"]',
     "negative: конец цепочки не назван (её решает round-robin) — стрелки в подписи нет, догадка тут хуже молчания; здоровье берётся у того, куда ведёт само ребро — для прямого выхода это он и есть"),
    ("onerror_warns_when_both_exits_are_one_output", '', '(() => { const r = st.topology.routers[0]; const oe = r.graph.nodes.find((n) => n.id === "oe1"); const warn = () => node("rule:oe1").html.includes(\'data-t="kanban-onerror-same"\'); const differ = warn(); oe.config.rescueEdge = "e7"; const one = warn(); oe.config.rescueEdge = "e8"; r.graph.edges.find((e) => e.id === "e8").to = "out:srv:22001"; const twoToOne = warn(); r.graph.edges.find((e) => e.id === "e8").to = "out:cb:terra"; st.ui.latestSystemMonitor = { latest: { agentProxies: { onErrorNext: { oe1: { next: "main", main: "srv:22010", backup: "srv:22010", mainChain: ["q1"], backupChain: ["q1"] } } } } }; const chained = warn(); st.ui.latestSystemMonitor = null; r.graph.edges.push({ id: "eX", from: "rule:oe1", to: "rule:q1" }); oe.config.mainEdge = "eX"; oe.config.rescueEdge = "eX"; const oneIntoRule = warn(); return [differ, one, twoToOne, chained, oneIntoRule, m.OnErrorNode.sameExitHtml(null, { to: "rule:q1" }, { to: "rule:w1" }) !== ""]; })()',
     '[false,true,true,true,true,false]',
     "🛟 предупреждает, когда main и backup кончаются одним выходом: один канат в обеих ролях (так было на живом канбане; и когда этот канат ведёт в узел правила), два каната в один выход, цепочки, которые прокси довёл до одной модели; negative: разные выходы — тихо; концы, которых никто не назвал (узлы без отчёта), — тихо, без догадки"),
    ("fit_all_measures_the_drawn_nodes", '', '(() => { const world = mkEl({ style: {}, qa: { ".cv-node": [mkEl({ offsetLeft: 0, offsetTop: 0, offsetWidth: 100, offsetHeight: 50 }), mkEl({ offsetLeft: 900, offsetTop: 400, offsetWidth: 100, offsetHeight: 100 }), mkEl({ offsetLeft: 5000, offsetTop: 5000, offsetWidth: 0, offsetHeight: 0 })] } });'
     ' globalThis.__q["[data-cv-world]"] = world; globalThis.__q["[data-cv-viewport]"] = mkEl({ clientWidth: 800, clientHeight: 600 }); m.board.fitAll(); const fitted = { ...m._cvView };'
     ' world.qa[".cv-node"] = []; m.board.view.tx = 7; m.board.fitAll(); return [fitted, world.style.transform, m._cvView.tx]; })()',
     '[{"tx":32,"ty":116,"scale":0.736},"translate(32px, 116px) scale(0.736)",7]',
     "⤢ Show all меряет узлы такими, как они нарисованы (смещения в мире), скрытый узел нулевого размера в рамку не идёт; "
     "вид меняется на месте — тот же объект _cvView, и мир получает его; negative: узлов нет — вид не трогается"),
    ("onerror_ago", '', '[m.OnErrorNode.ago(5), m.OnErrorNode.ago(59), m.OnErrorNode.ago(60), m.OnErrorNode.ago(150), m.OnErrorNode.ago(3600), m.OnErrorNode.ago(-3), m.OnErrorNode.ago("x")]',
     '["5s","59s","1m","3m","1h","0s","0s"]',
     "возраст: секунды до минуты, минуты до часа, часы; мусор и минус — 0s"),
    ("onerror_countdown", 'st.ui.latestSystemMonitor = { latest: { agentProxies: { outputHealth: { "srv:22001": { state: "error", status: 429, kind: "http 429", message: "quota", checkedAt: 1700000000, ageSec: 100, fresh: true, retryInSec: 200 }, "cb:terra": { state: "ok", checkedAt: 1699999600, ageSec: 500, fresh: false, retryInSec: 0 } }, onErrorNext: { oe1: { next: "main", reason: "" } } } } }; globalThis.__timers.length = 0;', '(() => { const h = node("rule:oe1").html; const rows = h.split(/class="cv-q-dest/).slice(1); const cd = (r) => (r.match(/cv-oe-cd" data-cv-oe-deadline="(\\d+)"[^>]*>([^<]*)</) || []).slice(1, 3); return [cd(rows[0]), cd(rows[1]), globalThis.__timers.includes("interval:1000")]; })()',
     '[["1700000300","3:20"],["1700000100","0:00"],true]',
     "отсчёт: дедлайн = checkedAt + возраст + срок перепроверки; свежий вердикт — «3:20», истёкший — «0:00»; тикер раз в секунду зарегистрирован при отрисовке"),
    ("onerror_countdown_unknown", '', '(() => { const h = node("rule:oe1").html; return [h.includes("cv-oe-cd"), m.OnErrorNode.countdownText(0), m.OnErrorNode.countdownText(1700000100 - 5), m.OnErrorNode.countdownText(1700000100 + 61), m.OnErrorNode.countdownText(1700000100 + 3600)]; })()',
     '[false,"","0:00","1:01","60:00"]',
     "без вердикта отсчёта нет; текст: пусто без дедлайна, «0:00» в прошлом, минуты без ограничения часом"),
    ("onerror_countdown_tick", 'const cdEl = mkEl({ textContent: "", dataset: { cvOeDeadline: "1700000300" } }); globalThis.__qa["[data-cv-oe-deadline]"] = [cdEl]; m.OnErrorNode.tick();', 'cdEl.textContent',
     '"3:20"',
     "тик патчит только текст отсчёта — строки узла не перестраиваются"),
    ("draw_connectors_groups_and_roles", '', '(() => { const world = mkEl({ classList: (() => { const c = cls(); c.add("cv-world"); return c; })() }); const el = (x, y, w = 100, h = 40) => mkEl({ offsetLeft: x, offsetTop: y, offsetWidth: w, offsetHeight: h, offsetParent: world }); const q = el(300, 100), s = el(300, 400), w1 = el(300, 700), oe = el(300, 900), rt = el(300, 1000), rs = el(300, 1100), f1 = el(300, 800); const admitPort = mkEl({ offsetLeft: 90, offsetTop: 10, offsetWidth: 10, offsetHeight: 10, offsetParent: q }); q.q = { \'.cv-port.out[data-cv-qrole="admit"]\': admitPort }; world.q = { \'[data-cv-node="rule:q1"]\': q, \'[data-cv-node="rule:s1"]\': s, \'[data-cv-node="rule:w1"]\': w1, \'[data-cv-node="rule:oe1"]\': oe, \'[data-cv-node="rule:rt1"]\': rt, \'[data-cv-node="rule:rs1"]\': rs, \'[data-cv-node="rule:f1"]\': f1 }; const dot = (left, top) => mkEl({ rect: { left, top, width: 16, height: 16 } }); const svg = mkEl({ classList: cls() }); globalThis.__q["[data-cv-world]"] = world; globalThis.__q["[data-cv-svg]"] = svg; globalThis.__q["[data-cv-viewport]"] = mkEl({ rect: { left: 0, top: 0 } }); globalThis.__q[\'.rw-servers [data-cv-out-port="out:srv:22001"]\'] = dot(1000, 120); globalThis.__q[\'.rw-servers [data-cv-out-port="out:cb:terra"]\'] = dot(1000, 160); globalThis.__q[\'.rw-servers [data-cv-out-port="out:srv:22003"]\'] = dot(1000, 200); globalThis.__q[\'.rw-clients .cv-port.out[data-cv-ref="in:skynet:proxy:23001"]\'] = dot(300, 130); m.drawCanvasConnectors(); const h = svg.innerHTML; return [(h.match(/class="cv-edge-grp"/g) || []).length, h.includes(\'data-t-id="in:skynet:proxy:23001-&gt;rule:q1"\'), h.includes("cv-cable cv-cable-admit"), h.includes("cv-cable cv-cable-spill"), h.includes("cv-cable cv-cable-main") && h.includes("cv-cable cv-cable-rescue"), h.includes("M 400 120 C"), (h.match(/data-cv-edge-del=/g) || []).length, h.includes("M 292 114 C"), h.includes(`984 104"`)]; })()',
     '[11,true,true,true,true,true,11,true,true]', "коннекторы: группа на ребро с data-t-id from->to, классы ролей очереди и onError, admit выходит из ролевого порта, ✕ на каждом; точки панелей лежат вне мира и берутся с экрана через вид: порт клиента — правым краем (292,114), точка выхода — центром (984,104)"),
    ("draw_connectors_marks_cables_into_a_stopped_cell", '', '(() => { const run = (phase) => { st.topology.nodes = [{ id: "m1", servers: [{ port: 22001, phase }, { port: 22003, phase: "running" }] }]; const world = mkEl({ classList: (() => { const c = cls(); c.add("cv-world"); return c; })() }); const el = (x, y, w = 100, h = 40) => mkEl({ offsetLeft: x, offsetTop: y, offsetWidth: w, offsetHeight: h, offsetParent: world }); const q = el(300, 100), s = el(300, 400), w1 = el(300, 700), oe = el(300, 900), rt = el(300, 1000), rs = el(300, 1100), f1 = el(300, 800); const admitPort = mkEl({ offsetLeft: 90, offsetTop: 10, offsetWidth: 10, offsetHeight: 10, offsetParent: q }); q.q = { \'.cv-port.out[data-cv-qrole="admit"]\': admitPort }; world.q = { \'[data-cv-node="rule:q1"]\': q, \'[data-cv-node="rule:s1"]\': s, \'[data-cv-node="rule:w1"]\': w1, \'[data-cv-node="rule:oe1"]\': oe, \'[data-cv-node="rule:rt1"]\': rt, \'[data-cv-node="rule:rs1"]\': rs, \'[data-cv-node="rule:f1"]\': f1 }; const dot = (left, top) => mkEl({ rect: { left, top, width: 16, height: 16 } }); const svg = mkEl({ classList: cls() }); globalThis.__q["[data-cv-world]"] = world; globalThis.__q["[data-cv-svg]"] = svg; globalThis.__q["[data-cv-viewport]"] = mkEl({ rect: { left: 0, top: 0 } }); globalThis.__q[\'.rw-servers [data-cv-out-port="out:srv:22001"]\'] = dot(1000, 120); globalThis.__q[\'.rw-servers [data-cv-out-port="out:cb:terra"]\'] = dot(1000, 160); globalThis.__q[\'.rw-servers [data-cv-out-port="out:srv:22003"]\'] = dot(1000, 200); globalThis.__q[\'.rw-clients .cv-port.out[data-cv-ref="in:skynet:proxy:23001"]\'] = dot(300, 130); m.drawCanvasConnectors(); const h = svg.innerHTML; return [(h.match(/cv-cable-down/g) || []).length, h.includes("cv-cable cv-cable-admit cv-cable-down"), /out:cb:terra[^>]*cv-cable-down/.test(h)]; }; return [run("stopped"), run("running")]; })()',
     '[[5,true,false],[0,false,false]]', "канат в ячейку, которая не работает, нарисован пунктиром (cv-cable-down, в конце классов — роль остаётся): пять канатов в остановленную :22001; канат в работающую :22003 и в облако — сплошные; negative: та же ячейка работает — ни одного пунктира"),
    ("draw_connectors_overflow_leaves_the_panel_to_the_left", '', '(() => { const r = st.topology.routers[0]; Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); const svg = mkEl({ classList: cls() }); const dot = (left, top) => mkEl({ rect: { left, top, width: 16, height: 16 } }); globalThis.__q["[data-cv-world]"] = mkEl({ classList: cls() }); globalThis.__q["[data-cv-svg]"] = svg; globalThis.__q["[data-cv-viewport]"] = mkEl({ rect: { left: 0, top: 0 } }); globalThis.__q[\'.rw-servers .cv-port.out[data-cv-node="rule:q1"]\'] = dot(1000, 300); globalThis.__q[\'.rw-servers [data-cv-out-port="out:cb:terra"]\'] = dot(1000, 160); m.drawCanvasConnectors(); const h = svg.innerHTML; return [(h.match(/class="cv-edge-grp"/g) || []).length, h.includes("cv-cable cv-cable-spill"), h.includes("M 976 284 C 928 284, 936 144, 984 144")]; })()',
     '[1,true,true]', "переход очереди модели — не узел мира: его точка на левой границе панели серверов, и канат уходит из неё влево (контрольная точка слева), огибает холст и входит в точку цели; внутренний основной канат не рисуется"),
    ("cable_curve_formula_one_for_drawn_and_dragged", '', '[m._cvPathD({ x: 100, y: 0, dir: -1 }, { x: 100, y: 50 }), m._cvPathD({ x: 0, y: 0, dir: -1 }, { x: 400, y: 0 }), m._cvPathD({ x: 0, y: 0 }, { x: 200, y: 100 }), m.Board.curve({ x: 0, y: 0 }, { x: 200, y: 100 }).mid, m.Board.curve({ x: 100, y: 0, dir: -1 }, { x: 100, y: 50 }).mid]',
     '["M 100 0 C 52 0, 52 50, 100 50","M 0 0 C -192 0, 208 0, 400 0","M 0 0 C 96 0, 104 100, 200 100",{"x":100,"y":50},{"x":64,"y":25}]', "кривая: уходит направо, а при dir -1 — налево, и входит слева; одна формула для нарисованных канатов и для протягиваемого; середина (где ✕) считается той же кривой"),
    ("draw_connectors_without_router_clears", 'st.ui.topologyCanvasRouterId = "router:zzz";', '(() => { const svg = mkEl({ innerHTML: "OLD" }); globalThis.__q["[data-cv-world]"] = mkEl(); globalThis.__q["[data-cv-svg]"] = svg; m.drawCanvasConnectors(); return svg.innerHTML; })()', '""', "negative: роутер не найден — холст очищен"),
    ("bind_node_drag_moves_and_persists_rule_position", '', 'await (async () => { const world = mkEl({ dataset: {}, classList: (() => { const c = cls(); c.add("cv-world"); return c; })() }); const viewport = mkEl({ rect: { left: 0, top: 0 } }); const nodeEl = mkEl({ dataset: { cvNode: "rule:q1" }, offsetLeft: 300, offsetTop: 100, style: {}, parentElement: world, q: {} }); nodeEl.closest = (sel) => (sel === "[data-cv-node]" ? nodeEl : null); world.qa = { "[data-cv-node]": [nodeEl], ".cv-node": [nodeEl] }; globalThis.__q["[data-cv-viewport]"] = viewport; globalThis.__q["[data-cv-world]"] = world; m.bindCanvasInteractions(); const bound = world.dataset.cvBound; m.bindCanvasInteractions(); nodeEl.listeners.pointerdown[0]({ button: 0, clientX: 10, clientY: 10, target: { closest: () => null }, stopPropagation() {}, preventDefault() {} }); const dragging = nodeEl.classList.has("dragging"); winListeners.pointermove.at(-1)({ clientX: 60, clientY: 30 }); const moved = [nodeEl.style.left, nodeEl.style.top, m._cvPos["rule:q1"]]; winListeners.pointerup.at(-1)({}); await settle(); const persisted = lastSaved().graph.nodes.find((n) => n.id === "q1"); return [bound, nodeEl.listeners.pointerdown.length, dragging, moved, nodeEl.classList.has("dragging"), [persisted.x, persisted.y], "rule:q1" in m._cvPos]; })()',
     '["1",1,true,["350px","120px",{"x":350,"y":120}],false,[350,120],false]', "перетаскивание узла: биндер одной привязкой на поколение мира, движение в мировых единицах, позиция rule-узла пишется в граф при отпускании; когда сохранение пришло, память страницы место отпускает — дом места только сервер"),
    ("bind_pan_and_wheel_zoom", '', '(() => { const world = mkEl({ dataset: {}, classList: cls() }); const viewport = mkEl({ rect: { left: 0, top: 0 }, classList: cls() }); globalThis.__q["[data-cv-viewport]"] = viewport; globalThis.__q["[data-cv-world]"] = world; m.cvSetViewport({}, { tx: 24, ty: 24, scale: 1 }); m.bindCanvasInteractions(); viewport.listeners.pointerdown[0]({ button: 0, clientX: 100, clientY: 100, target: { closest: () => null } }); const panning = viewport.classList.has("panning"); winListeners.pointermove.at(-1)({ clientX: 130, clientY: 90 }); const panned = [m._cvView.tx, m._cvView.ty, world.style.transform]; winListeners.pointerup.at(-1)({}); let p = 0; viewport.listeners.wheel[0]({ deltaY: -100, clientX: 54, clientY: 14, target: { closest: () => null }, preventDefault: () => p++ }); const zoomed = [Math.round(m._cvView.scale * 1000) / 1000, Math.round(m._cvView.tx * 10) / 10, Math.round(m._cvView.ty * 10) / 10]; for (let i = 0; i < 20; i++) viewport.listeners.wheel[0]({ deltaY: -100, clientX: 0, clientY: 0, target: { closest: () => null }, preventDefault() {} }); const max = m._cvView.scale; for (let i = 0; i < 40; i++) viewport.listeners.wheel[0]({ deltaY: 100, clientX: 0, clientY: 0, target: { closest: () => null }, preventDefault() {} }); return [panning, panned, viewport.classList.has("panning"), p, zoomed, max, m._cvView.scale]; })()',
     '[true,[54,14,"translate(54px, 14px) scale(1)"],false,1,[1.1,54,14],2.2,0.35]', "пан фоном двигает мир; колесо — зум к курсору (точка под курсором на месте), зажат в 0.35…2.2"),
    # ── the panels' port dots ──
    ("panel_dot_placement_clamps_to_the_visible_span", '', '(() => { const panel = mkEl({ rect: { left: 0, top: 100, width: 300, height: 500 }, q: { ".rw-side-body": mkEl({ rect: { left: 0, top: 150, width: 300, height: 300 } }) } }); globalThis.__q[".rw-clients"] = panel; const ports = m.PanelPorts.of(".rw-clients"); const row = (top, height) => mkEl({ rect: { left: 0, top, width: 100, height } }); const place = (top, height = 30) => { const dot = mkEl(); ports.place(dot, row(top, height)); return [dot.style.top, dot.style.marginTop, dot.classList.contains("clamped")]; }; const cases = [place(200), place(120, 20), place(700), place(150), place(420)]; panel.clientTop = 1; const bordered = m.PanelPorts.of(".rw-clients"); const dot = mkEl(); bordered.place(dot, row(200, 30)); return [cases, dot.style.top, m.PanelPorts.of(".rw-nothing")]; })()',
     '[[["107px","0",false],["50px","0",true],["334px","0",true],["57px","0",false],["327px","0",false]],"106px",null]', "точка стоит центром на центре своей строки; строка над видимой частью тела или под ней — точка прижата на 8 px внутрь края и помечена clamped (её канаты кончаются у края панели); граница панели сдвигает отсчёт; нет панели — нет и порта"),
    ("client_dots_one_per_row_stale_pruned_hidden_skipped", '', '(() => { const old = document.createElement; document.createElement = () => mkEl(); try { const row = (ref, top, height = 30) => mkEl({ dataset: { cvInRow: ref }, rect: { left: 0, top, width: 100, height } }); const keep = mkEl({ dataset: { cvRef: "in:keep" } }), gone = mkEl({ dataset: { cvRef: "in:gone" } }); const panel = mkEl({ rect: { left: 0, top: 100, width: 300, height: 500 }, appended: [], appendChild(d) { this.appended.push(d); }, q: { ".rw-side-body": mkEl({ rect: { left: 0, top: 150, width: 300, height: 300 } }), [`:scope > .cv-port.out[data-cv-ref="in:keep"]`]: keep }, qa: { "[data-cv-in-row]": [row("in:keep", 200), row("in:new", 260), row("in:hidden", 300, 0)], ":scope > .cv-port.out[data-cv-ref]": [keep, gone] } }); globalThis.__q[".rw-clients"] = panel; m.InputsBlock.syncPortDots(); const [fresh] = panel.appended; return [panel.appended.length, fresh.dataset.cvRef, fresh.className, fresh.title === i18n.t("cvDragPort"), keep.style.top, fresh.style.top, gone.removed === true, keep.removed === true]; } finally { document.createElement = old; } })()',
     '[1,"in:new","cv-port out",true,"107px","167px",true,false]', "точки клиентов: одна на строку-порт — найденная переставляется, недостающая делается (ссылка in:…, подсказка), скрытая строка (высота 0) точки не получает, точка ушедшей строки убирается"),
    ("server_dots_outputs_folded_groups_and_overflow_ports", '', '(() => { const old = document.createElement; document.createElement = () => mkEl(); try { const rect = (top, height = 30) => ({ left: 0, top, width: 100, height }); const row = (id, top, height = 30) => mkEl({ dataset: { routerOutRow: id }, rect: rect(top, height) }); const group = mkEl({ dataset: { cvGroupOuts: "srv:5, srv:6, srv:1" }, q: { "[data-router-group-fold]": mkEl({ rect: rect(500, 24) }) } }); const lane = (ref, top, unset) => mkEl({ dataset: { cvNode: ref }, q: { ".cv-mq-line": mkEl({ rect: rect(top, 22) }), ".cv-mq-ov.unset": unset ? mkEl() : null } }); const keepOut = mkEl({ dataset: { cvOutPort: "out:srv:1" } }), staleOut = mkEl({ dataset: { cvOutPort: "out:srv:9" } }), staleSpill = mkEl({ dataset: { cvQrole: "spill", cvNode: "rule:gone" } }); const panel = mkEl({ rect: rect(100, 500), appended: [], appendChild(d) { this.appended.push(d); }, q: { ".rw-side-body": mkEl({ rect: rect(150, 300) }), [`:scope > [data-cv-out-port="out:srv:1"]`]: keepOut }, qa: { "[data-router-out-row]": [row("srv:1", 200), row("srv:2", 300), row("srv:3", 400, 0)], "[data-cv-group-outs].folded": [group], "[data-cv-model-queue]": [lane("rule:q1", 240, true), lane("rule:q2", 340, false)], ":scope > [data-cv-out-port]": [keepOut, staleOut], ":scope > .cv-port.out[data-cv-qrole]": [staleSpill] } }); globalThis.__q[".rw-servers"] = panel; m.ServersBlock.syncPortDots(); const outs = panel.appended.filter((d) => d.dataset.cvOutPort).map((d) => [d.dataset.cvOutPort, d.className, d.style.top, d.dataset.cvNode]); const spills = panel.appended.filter((d) => d.dataset.cvQrole === "spill").map((d) => [d.dataset.cvNode, d.className, d.classList.contains("unset"), d.dataset.cvPort, d.style.top]); return [outs, spills, keepOut.style.top, staleOut.removed === true, staleSpill.removed === true, keepOut.removed === true]; } finally { document.createElement = old; } })()',
     '[[["out:srv:2","cv-port in","207px","out:srv:2"],["out:srv:5","cv-port in","334px","out:srv:5"],["out:srv:6","cv-port in","334px","out:srv:6"]],[["rule:q1","cv-port out",true,"out","143px"],["rule:q2","cv-port out",false,"out","243px"]],"107px",true,true,false]', "точки серверов: по входной точке на строку (скрытая без точки), выходы свёрнутой группы — у её заголовка и прижаты к краю, повтор выхода из строки не дублируется; по точке перехода на дорожку на уровне её строки — «unset», пока нет каната; устаревшие точки убраны, нужные остались"),
    # ── the workspace around the panels: where the handlers live ──
    ("panel_dot_starts_a_cable_without_a_node_around_it", '', 'await (async () => { const cols = mkEl({ classList: cls() }); const world = mkEl({ dataset: {}, classList: cls(), closest: (sel) => (sel === "[data-cv-cols]" ? cols : null) }); globalThis.__q["[data-cv-viewport]"] = mkEl({ rect: { left: 0, top: 0 } }); globalThis.__q["[data-cv-world]"] = world; m.bindCanvasInteractions(); const dot = mkEl({ dataset: { cvRef: "in:skynet:proxy:23001" }, rect: { left: 300, top: 130, width: 16, height: 16 } }); dot.closest = (sel) => (sel === ".cv-port.out" ? dot : null); const spill = mkEl({ dataset: { cvNode: "rule:q1", cvQrole: "spill" }, rect: { left: 1000, top: 300, width: 16, height: 16 } }); spill.closest = (sel) => (sel === ".cv-port.out" || sel === "[data-cv-node]" || sel === ".rw-servers" ? spill : null); const bare = mkEl({ dataset: {} }); bare.closest = (sel) => (sel === ".cv-port.out" ? bare : null); const down = (port) => cols.listeners.pointerdown.forEach((fn) => fn({ button: 0, target: port, stopPropagation() {}, preventDefault() {} })); down(dot); const client = JSON.parse(JSON.stringify(m._cvDrag)); winListeners.pointerup.at(-1)({}); down(spill); const over = JSON.parse(JSON.stringify(m._cvDrag)); winListeners.pointerup.at(-1)({}); down(bare); return [world.listeners.pointerdown === undefined, client.kind, client.id, client.replaceFrom, client.from, over.id, over.qrole, over.from, m._cvDrag]; })()',
     '[true,"connect","in:skynet:proxy:23001","in:skynet:proxy:23001",{"x":292,"y":114},"rule:q1","spill",{"x":976,"y":284,"dir":-1},null]', "порт-обработчик висит на рабочем поле вокруг холста и панелей, не на мире: точка клиента без узла вокруг начинает канат под своей ссылкой in:… из правого края, точка перехода — из левого края панели серверов влево (dir -1), порт без ссылки и без узла не начинает ничего"),
    ("panel_scroll_redraws_once_per_frame", '', '(() => { const body = mkEl(); globalThis.__qa[".rw-side-body"] = [body]; globalThis.__q["[data-cv-viewport]"] = mkEl(); globalThis.__q["[data-cv-world]"] = mkEl({ dataset: {}, classList: cls() }); m.bindCanvasInteractions(); const n0 = globalThis.__raf.length; const scroll = body.listeners.scroll[0]; scroll(); scroll(); scroll(); const queued = globalThis.__raf.length - n0; let draws = 0; Object.defineProperty(globalThis.__q, "[data-cv-svg]", { get() { draws++; return null; }, configurable: true, enumerable: true }); globalThis.__raf.splice(n0)[0](); const drawn = draws > 0; scroll(); return [queued, drawn, globalThis.__raf.length - n0, body._cvPortSyncBound]; })()',
     '[1,true,1,true]', "прокрутка панели: сколько бы событий ни пришло, канаты и точки перерисовываются раз за кадр; после кадра можно просить снова; обработчик вешается один раз на тело"),
    ("pan_and_zoom_redraw_cables_without_syncing_the_panels", '', '(() => { let panelAsks = 0, svgAsks = 0; Object.defineProperty(globalThis.__q, ".rw-clients", { get() { panelAsks++; return null; }, configurable: true, enumerable: true }); Object.defineProperty(globalThis.__q, "[data-cv-svg]", { get() { svgAsks++; return null; }, configurable: true, enumerable: true }); const world = mkEl({ dataset: {}, classList: cls() }); const viewport = mkEl({ rect: { left: 0, top: 0 }, classList: cls() }); globalThis.__q["[data-cv-viewport]"] = viewport; globalThis.__q["[data-cv-world]"] = world; m.cvSetViewport({}, { tx: 24, ty: 24, scale: 1 }); m.bindCanvasInteractions(); const base = panelAsks, svgBase = svgAsks; viewport.listeners.pointerdown[0]({ button: 0, clientX: 100, clientY: 100, target: { closest: () => null } }); winListeners.pointermove.at(-1)({ clientX: 130, clientY: 90 }); winListeners.pointerup.at(-1)({}); const panned = [panelAsks - base, svgAsks - svgBase > 0]; const svgAfterPan = svgAsks; viewport.listeners.wheel[0]({ deltaY: -100, clientX: 54, clientY: 14, target: { closest: () => null }, preventDefault() {} }); const zoomed = [panelAsks - base, svgAsks - svgAfterPan > 0]; m.drawCanvasConnectors(); return [panned, zoomed, panelAsks - base > 0]; })()',
     '[[0,true],[0,true],true]', "пан и зум двигают мир под неподвижными панелями — канаты рисуются заново (их концы на панелях сменили место в мире), а точки панелей не пересчитываются; обычная перерисовка их пересчитывает"),
    ("bind_port_drag_connects_on_drop", '', 'await (async () => { const world = mkEl({ dataset: {}, classList: (() => { const c = cls(); c.add("cv-world"); return c; })() }); const viewport = mkEl({ rect: { left: 0, top: 0 } }); const nodeEl = mkEl({ dataset: { cvNode: "rule:w1" }, offsetParent: world, offsetLeft: 300, offsetTop: 700 }); const port = mkEl({ dataset: { cvRef: "" }, offsetParent: nodeEl, offsetLeft: 90, offsetTop: 10, offsetWidth: 10, offsetHeight: 10 }); port.closest = (sel) => (sel === ".cv-port.out" ? port : sel === "[data-cv-node]" ? nodeEl : null); globalThis.__q["[data-cv-viewport]"] = viewport; globalThis.__q["[data-cv-world]"] = world; m.bindCanvasInteractions(); world.listeners.pointerdown[0]({ button: 0, target: port, stopPropagation() {}, preventDefault() {} }); const target = mkEl({ dataset: { cvNode: "out:srv:22003" }, classList: cls() }); target.closest = (sel) => (sel === "[data-cv-node]" ? target : null); globalThis.__atPoint = target; globalThis.__qa[".cv-node.cv-drop-ok"] = [target]; winListeners.pointermove.at(-1)({ clientX: 500, clientY: 500 }); const dropOk = target.classList.has("cv-drop-ok"); winListeners.pointerup.at(-1)({ clientX: 500, clientY: 500 }); await settle(); const g = lastSaved().graph; return [dropOk, g.edges.some((e) => e.from === "rule:w1" && e.to === "out:srv:22003"), target.classList.has("cv-drop-ok")]; })()',
     '[true,true,false]', "протяжка из порта: цель под курсором подсвечивается, отпускание над выходом создаёт ребро, подсветка снята"),
    ("bind_queue_cfg_input_clamps", '', 'await (async () => { const world = mkEl({ dataset: {}, classList: cls() }); const viewport = mkEl(); const nodeEl = mkEl({ dataset: { cvNode: "rule:q1" } }); const slots = mkEl({ dataset: { cvQ: "maxSlots" }, value: "99", min: "1", max: "64" }); slots.closest = () => nodeEl; const pct = mkEl({ dataset: { cvQ: "maxTokensAt" }, value: "150000", min: "1", max: "100000" }); pct.closest = () => nodeEl; world.qa = { ".cv-q-cfg-in[data-cv-q]": [slots, pct] }; globalThis.__q["[data-cv-viewport]"] = viewport; globalThis.__q["[data-cv-world]"] = world; m.bindCanvasInteractions(); slots.listeners.change[0](); pct.listeners.change[0](); slots.value = ""; slots.listeners.change[0](); await settle(); const cfgs = saved().map((s) => s.graph.nodes.find((n) => n.id === "q1").config); return [cfgs[0].maxSlots, cfgs[1].maxTokensAt, cfgs[2].maxSlots]; })()',
     '[64,100000,null]', "поля очереди на карточке: слоты зажаты 1…64 (пусто — null = авто), порог размера 1…100000"),
    ("bind_sched_paint_saves_grid", '', 'await (async () => { const world = mkEl({ dataset: {}, classList: cls() }); const cell = mkEl({ dataset: { cvSchedCell: "s1", schedD: "2", schedH: "5" }, style: {}, classList: cls() }); const cell2 = mkEl({ dataset: { cvSchedCell: "s1", schedD: "2", schedH: "6" }, style: {}, classList: cls() }); world.qa = { "[data-cv-sched-cell]": [cell, cell2] }; globalThis.__q["[data-cv-viewport]"] = mkEl(); globalThis.__q["[data-cv-world]"] = world; globalThis.__q[\'[data-cv-sched-cell="s1"][data-sched-d="2"][data-sched-h="5"]\'] = cell; globalThis.__q[\'[data-cv-sched-cell="s1"][data-sched-d="2"][data-sched-h="6"]\'] = cell2; m.bindCanvasInteractions(); cell.listeners.pointerdown[0]({ button: 0, stopPropagation() {}, preventDefault() {} }); const painting = [m._cvSchedPainting, cell.style.background, cell.classList.has("painted")]; cell2.listeners.pointerover[0]({}); winListeners.pointerup.find((fn) => fn.length === 0 || true); for (const fn of winListeners.pointerup) fn({}); await settle(); const grid = lastSaved().graph.nodes.find((n) => n.id === "s1").config.grid; return [painting, cell2.classList.has("painted"), grid[2][5], grid[2][6], grid[0][1], m._cvSchedPainting]; })()',
     '[[true,"#60a5fa",true],true,"o1","o1","o1",false]', "рисование сетки: pointerdown красит кистью (первый выход), pointerover продолжает, pointerup сохраняет сетку целиком (старые клетки на месте)"),
    ("drop_waits_for_its_save_then_lets_go", '', 'await (async () => { let land; globalThis.__stubReturns["routers.saveRouters"] = (mut) => new Promise((r) => { land = () => { const copy = JSON.parse(JSON.stringify(st.topology.routers)); mut(copy); globalThis.__calls.push(["saveRouters", copy[0]]); r(); }; });'
     ' const node = () => mkEl({ classList: cls(), dataset: { cvNode: "rule:q1" } }); const first = { x: 1, y: 1 }; m.board.pos["rule:q1"] = first; m.board.drag = { kind: "node", node: node(), id: "rule:q1" }; m.board.onUp({});'
     ' const inFlight = m.board.pos["rule:q1"] === first; const second = { x: 2, y: 2 }; m.board.pos["rule:q1"] = second; land(); await settle();'
     ' const keptSecond = m.board.pos["rule:q1"] === second; m.board.drag = { kind: "node", node: node(), id: "rule:q1" }; m.board.onUp({}); land(); await settle();'
     ' return [inFlight, keptSecond, "rule:q1" in m.board.pos, saved().map((r) => [r.graph.nodes.find((n) => n.id === "q1").x, r.graph.nodes.find((n) => n.id === "q1").y])]; })()',
     '[true,true,false,[[1,1],[2,2]]]',
     "бросок держит своё место в памяти, пока сохранение не пришло, и отпускает его после — дом места сервер; "
     "negative: второй бросок того же узла, начатый до ответа на первый, первым ответом не стирается (иначе перерисовка "
     "дёрнула бы узел назад)"),
    ("a_nudged_drop_saves_where_it_ended", '', 'await (async () => { const world = mkEl({ classList: cls() }); const a = mkEl({ classList: cls(), dataset: { cvNode: "rule:q1" }, offsetLeft: 100, offsetTop: 100, offsetWidth: 100, offsetHeight: 40, style: {}, parentElement: world });'
     ' const b = mkEl({ dataset: { cvNode: "rule:w1" }, offsetLeft: 150, offsetTop: 100, offsetWidth: 100, offsetHeight: 40, style: {} }); world.qa = { ".cv-node": [a, b] };'
     ' m.board.pos["rule:q1"] = { x: 100, y: 100 }; m.board.drag = { kind: "node", node: a, id: "rule:q1" }; m.board.onUp({}); await settle();'
     ' const q = lastSaved().graph.nodes.find((n) => n.id === "q1"); return [q.x, q.y, a.style.top]; })()',
     '[100,188,"188px"]',
     "брошенный на соседа узел сдвигается и сохраняется там, где встал после сдвига, а не там, где его отпустили"),
    ("resolve_overlap_pushes_dragged_node_only", '', '(() => { const world = mkEl({ classList: cls() }); const a = mkEl({ dataset: { cvNode: "rule:q1" }, offsetLeft: 100, offsetTop: 100, offsetWidth: 100, offsetHeight: 40, style: {}, parentElement: world }); const b = mkEl({ dataset: { cvNode: "rule:w1" }, offsetLeft: 150, offsetTop: 100, offsetWidth: 100, offsetHeight: 40, style: {} }); world.qa = { ".cv-node": [a, b] }; const moved = m._cvResolveOverlap(a); return [a.style.left, a.style.top, b.style.left, moved, "rule:q1" in m._cvPos]; })()',
     '["100px","188px",null,{"x":100,"y":188},false]', "раздвижка: сдвигается только перетащенный узел, по оси меньшего сдвига (dy 88 < dx 98), с зазором 48 и без зажима к нулю; сдвиг только рисуется и не становится местом узла (место — на сервере)"),
]


PINS += [
    ("shared_queue_settings_contract", '', 'qs.QueueSettings.FIELDS.map(f => [f.key, f.spec, f.fallback, f.max])', json.dumps([[field[0], spec, field[1], field[3]] for spec, field in SharedQueuePolicy.FIELDS.items()], separators=(",", ":")), "названия полей, умолчания и границы браузера совпадают с общим правилом сервера"),
    ("shared_queue_settings_once", '', '(() => { st.topology.proxyPolicy = { cloudFallbackPct: 5, stickySlotSec: 20, loadingModelWaitSec: 60 }; const h = qs.QUEUE_SETTINGS.html(); return [(h.match(/data-cv-queue-policy=/g) || []).length, h.includes(\'value="5"\'), h.includes(\'value="20"\'), h.includes(\'value="60"\'), qs.QUEUE_SETTINGS.values()]; })()', '[3,true,true,true,{"spillPct":5,"stickySlotSec":20,"loadingModelWaitSec":60}]', "одна общая панель содержит ровно три поля"),
    ("shared_queue_settings_save_patch", '', 'await (async () => { globalThis.__fetchReply["/api/agent-proxies/policy"] = { ok: true, config: { policy: { cloudFallbackPct: 17, stickySlotSec: 20, loadingModelWaitSec: 60 } } }; await qs.QUEUE_SETTINGS.save("cloudFallbackPct", "17"); return [globalThis.__fetchCalls.map(c => [c.path, JSON.parse(c.body)]), qs.QUEUE_SETTINGS.values(), qs.QUEUE_SETTINGS.saving]; })()', '[[["/api/agent-proxies/policy",{"policy":{"cloudFallbackPct":17}}]],{"spillPct":17,"stickySlotSec":20,"loadingModelWaitSec":60},false]', "запись отправляет только изменённое поле; после ответа все очереди читают новую политику"),
    ("shared_queue_settings_zero_and_invalid", '', 'await (async () => { globalThis.__fetchReply["/api/agent-proxies/policy"] = { config: { policy: { cloudFallbackPct: 0, stickySlotSec: 0, loadingModelWaitSec: 0 } } }; await qs.QUEUE_SETTINGS.save("stickySlotSec", "0"); const results = []; for (const raw of ["", "-1", "1.5", "121", "bad"]) { try { await qs.QUEUE_SETTINGS.save("stickySlotSec", raw); results.push(false); } catch (_) { results.push(true); } } return [qs.QUEUE_SETTINGS.values(), results, globalThis.__fetchCalls.length]; })()', '[{"spillPct":0,"stickySlotSec":0,"loadingModelWaitSec":0},[true,true,true,true,true],1]', "ноль сохраняется; пустое, дробное и выход за границы не уходят на сервер"),
    ("shared_queue_settings_failure_unlocks", '', 'await (async () => { globalThis.__fetchReply["/api/agent-proxies/policy"] = { __status: 500, error: "save failed" }; let message = ""; try { await qs.QUEUE_SETTINGS.save("cloudFallbackPct", "7"); } catch (e) { message = e.message; } return [message, qs.QUEUE_SETTINGS.saving, qs.QUEUE_SETTINGS.values().spillPct]; })()', '["save failed",false,20]', "отказ записи снимает блокировку и сохраняет подтверждённые значения"),
    ("model_queue_controls", '', '(() => { const r = ROUTER(); Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); const h = m.ModelQueueNode.cards(r)["srv:22001"]; return [h.includes("kanban-model-queue"), h.includes(\'data-cv-node="rule:q1"\'), h.includes(\'data-cv-qrole="admit"\'), (h.match(/data-cv-qrole="spill"/g) || []).length, h.includes("data-cv-delnode"), h.includes(\'data-cv-q="spillPct"\'), h.includes("cv-q-hist-toggle"), h.includes(\'data-cv-mq-activity="q1"\'), h.includes(\'data-cv-mq-state="q1"\'), h.includes("data-cv-mq-toggle")]; })()',
     '[true,true,false,0,false,false,true,true,true,true]', "очередь модели: закреплённый main без своего порта, порта перехода в самой дорожке тоже нет (это точка панели серверов), история, живые области (счётчик и список) и кнопка строки; удаления нет"),
    ("model_queue_hidden_when_disconnected", 'Object.assign(st.topology.routers[0].graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: false });', '(() => { const r = st.topology.routers[0]; return [Object.keys(m.ModelQueueNode.cards(r)), nodesOf().some((n) => n.id === "rule:q1"), m.ModelQueueNode.internalEdge(r, r.graph.edges[1]), m.ModelQueueNode.internalEdge(r, r.graph.edges[2])]; })()',
     '[[],false,true,false]', "отключённая очередь скрыта; внутренний основной канат скрыт, переход остаётся обычным канатом"),
    ("two_model_queues", '', '(() => { const r = ROUTER(); Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); r.graph.nodes.push({ id: "q2", type: "queue", modelOutputId: "srv:22003", modelQueueActive: true, config: {} }); const cards = m.ModelQueueNode.cards(r); return [Object.keys(cards), cards["srv:22001"].includes(\'data-cv-mq-activity="q1"\'), cards["srv:22003"].includes(\'data-cv-mq-activity="q2"\'), cards["srv:22001"].includes(\'data-cv-mq-state="q2"\')]; })()',
     '[["srv:22001","srv:22003"],true,true,false]', "две модели имеют отдельные дорожки с собственными идентификаторами; живая область одной не называет другую"),
    ("model_queue_rejects_manual_lifecycle_and_main_change", '', '(() => { const r = ROUTER(); r.graph.nodes[0].modelOutputId = "srv:22001"; const g = new m.Graph(r); return [() => g.addNode("queue", {x:0,y:0}), () => g.removeNode("q1"), () => g.addEdge("rule:q1", "out:srv:22003", "admit")].map((operation) => { try { operation(); return false; } catch (e) { return e.message === i18n.t("cvQueueAutomatic"); } }); })()',
     '[true,true,true]', "ручное создание, удаление и смена основной модели автоматической очереди запрещены"),
    ("model_queue_history_is_scoped", 'st.topology.routers[0].graph.nodes[0].modelOutputId = "srv:22001"; m._cvQueueHistData.q1 = { ts: Date.now(), rows: [{ item: { port: 23001, group: "127.0.0.1:22001", model: "OWN" } }, { item: { port: 23001, group: "127.0.0.1:22003", model: "OTHER" } }, { item: { port: 23001, upstreamType: "cloud", model: "SPILLED", queue: { nodeIds: ["q1"] } } }] };', '(() => { const h = m.History.queueHtml("q1"); return [h.includes("OWN"), h.includes("OTHER"), h.includes("SPILLED")]; })()',
     '[true,false,true]', "история очереди содержит свою модель и её переходы; запросы другой модели исключены"),
    # ── a model's queue is a lane under its row ──
    ("model_queue_lane_is_a_line", '', '(() => { const r = ROUTER(); Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); const h = m.ModelQueueNode.cards(r)["srv:22001"]; const shut = h.indexOf("cv-mq-detail"); return [h.startsWith(`<section class="cv-model-queue" `), h.includes(`aria-expanded="false"`), h.includes(`data-t-state="idle"`), h.includes("cv-q-dest"), h.includes("cv-rule-head"), (h.match(/class="cv-port /g) || []).length, h.indexOf("cv-mq-ov") < shut, h.includes(`data-cv-qrole`), h.includes("☁ terra")]; })()',
     '[true,true,true,false,false,0,true,false,true]', "дорожка закрыта: одна строка — счётчик слева, цель перехода справа; ни шапки, ни строки main, ни порта (он точка панели), подробности ниже строки"),
    ("model_queue_lane_states", '', '(() => { const r = ROUTER(); Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); const state = (ov) => { globalThis.__overview = ov; const h = m.ModelQueueNode.cards(r)["srv:22001"]; return h.match(/data-t-state="([a-z]+)"/)[1] + (h.includes("cv-q-qd idle") ? "+idle" : "") + (h.includes("cv-q-qd waiting") ? "+waiting" : ""); }; const mine = { group: "127.0.0.1:22001", port: 23001, startedAt: 1 }, line = { group: "127.0.0.1:22001", port: 23101, queue: { position: 0 } }, other = { group: "other", port: 23001, startedAt: 1 }; return [state(null), state({ running: [mine], queued: [] }), state({ running: [], queued: [line] }), state({ running: [mine], queued: [line] }), state({ running: [other], queued: [{ ...line, group: "other" }] }), state({ running: [{ group: "", port: 23001, upstreamType: "cloud", startedAt: 1 }], queued: [] })]; })()',
     '["idle+idle","running","waiting+waiting","waiting+waiting","idle+idle","running"]', "состояние дорожки: пусто — idle и слово «idle» у счётчика, идёт запрос — running и слова «idle» нет (занятую модель не назовут простаивающей), кто-то в очереди — waiting со счётчиком ожидающих и это сильнее running; чужая модель не красит; запрос, ушедший в облако через эту очередь, — running"),
    ("model_queue_lane_open_survives_render", '', '(() => { const r = ROUTER(); Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); const html = () => m.ModelQueueNode.cards(r)["srv:22001"]; const open = (h) => h.includes(`class="cv-model-queue open"`); const shut = html(); m.ModelQueueNode.open.add("q1"); const opened = html(); m.ModelQueueNode.open.delete("q1"); const again = html(); return [open(shut), open(opened), opened.includes(`aria-expanded="true"`), open(again)]; })()',
     '[false,true,true,false]', "открытая оператором дорожка остаётся открытой после перерисовки; закрытая — закрытой"),
    ("model_queue_lane_toggle_in_place", '', '(() => { const attrs = { setAttribute(k, v) { this.attrs = { ...(this.attrs || {}), [k]: v }; } }; const btn = mkEl(attrs); const lane = mkEl({ dataset: { cvNode: "rule:q1" }, q: { "[data-cv-mq-toggle]": btn } }); const read = () => [m.ModelQueueNode.open.has("q1"), lane.classList.contains("open"), btn.attrs["aria-expanded"]]; const first = m.ModelQueueNode.toggle(lane); const afterFirst = read(); const second = m.ModelQueueNode.toggle(lane); const afterSecond = read(); const next = mkEl({ dataset: { cvNode: "rule:q2" }, q: { "[data-cv-mq-toggle]": mkEl(attrs) } }); m.ModelQueueNode.toggle(next); return [first, afterFirst, second, afterSecond, [m.ModelQueueNode.open.has("q1"), m.ModelQueueNode.open.has("q2")]]; })()',
     '[true,[true,true,"true"],false,[false,false,"false"],[false,true]]', "щелчок по строке открывает и закрывает дорожку на месте: запоминает, ставит класс и aria-expanded; другая дорожка не затронута"),
    ("model_queue_lane_click_is_delegated", '', 'await (async () => { let draws = 0; Object.defineProperty(globalThis.__q, "[data-cv-svg]", { get() { draws++; return null; }, configurable: true, enumerable: true }); const cols = mkEl({ classList: cls() }); const world = mkEl({ dataset: {}, classList: cls(), closest: (sel) => (sel === "[data-cv-cols]" ? cols : null) }); globalThis.__q["[data-cv-viewport]"] = mkEl(); globalThis.__q["[data-cv-world]"] = world; m.bindCanvasInteractions(); const base = draws; const lane = mkEl({ dataset: { cvNode: "rule:q1" } }); const hit = { target: { closest: (sel) => (sel === "[data-cv-mq-toggle]" ? { closest: (s2) => (s2 === "[data-cv-model-queue]" ? lane : null) } : null) } }; const miss = { target: { closest: () => null } }; const click = (e) => (cols.listeners.click || []).forEach((fn) => fn(e)); click(miss); const afterMiss = [m.ModelQueueNode.open.has("q1"), draws - base]; click(hit); return [(cols.listeners.click || []).length > 0, (world.listeners.click || []).length, afterMiss, [m.ModelQueueNode.open.has("q1"), lane.classList.contains("open"), draws - base > 0]]; })()',
     '[true,0,[false,0],[true,true,true]]', "один слушатель на рабочее поле вокруг холста и панелей (дорожки стоят в панели, а не в мире): щелчок мимо строки ничего не делает; щелчок по строке открывает дорожку и заново рисует канаты (блок серверов сменил высоту)"),
    ("model_queue_lane_flags_a_dead_overflow_target", '', '(() => { const make = (mut) => { const r = ROUTER(); Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); mut(r); return m.ModelQueueNode.cards(r)["srv:22001"]; }; const ok = make(() => {}); const gone = make((r) => { r.outputs = r.outputs.filter((o) => o.id !== "cb:terra"); }); const unlisted = make(() => { st.topology.cloudProviders[0].unlisted = true; }); const unwired = make((r) => { r.graph.edges = r.graph.edges.filter((e) => e.id !== "e2"); }); const warn = (h) => h.includes("cv-mq-warn"); return [warn(ok), warn(gone), warn(unlisted), warn(unwired), ok.includes(`class="cv-mq-ov unset"`), unwired.includes(`class="cv-mq-ov unset"`), unwired.includes("cv-port"), (unwired.match(/data-cv-qrole/g) || []).length, gone.includes("cv-q-warn"), ok.includes("cv-q-warn")]; })()',
     '[false,true,true,false,false,true,false,0,true,false]', "цель перехода пропала или ушла из списка провайдера — ⚠ на самой строке (закрытой дорожки) и строка с причиной внутри; без каната цель названа «не подключено» (unset), а порта в дорожке нет и тут; здоровая дорожка чиста"),
    ("model_queue_lane_history_fold", '', '(() => { const r = ROUTER(); Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); const shut = m.ModelQueueNode.cards(r)["srv:22001"]; m._cvQueueHistOpen.q1 = true; m._cvQueueHistData.q1 = { ts: Date.now(), rows: [] }; const open = m.ModelQueueNode.cards(r)["srv:22001"]; return [shut.includes("cv-q-hist-body"), open.includes("cv-q-hist-body"), shut.includes("history ▾"), open.includes("history ▴")]; })()',
     '[false,true,true,true]', "складка истории внутри дорожки: закрыта — кнопка, открыта — строки"),
    ("queue_sync_live_patches_every_region", '', '(() => { const r = st.topology.routers[0]; Object.assign(r.graph.nodes[0], { modelOutputId: "srv:22001", modelQueueActive: true }); globalThis.__overview = { running: [{ group: "127.0.0.1:22001", port: 23001, startedAt: 1 }], queued: [] }; const lane = mkEl({ dataset: { tState: "idle" } }), other = mkEl({ dataset: { tState: "idle" } }); const region = (attr, id, owner) => mkEl({ innerHTML: "stale", getAttribute: (a) => (a === attr ? id : null), hasAttribute: (a) => a === attr, closest: () => owner }); const card = region("data-cv-q-live", "q1", other), meter = region("data-cv-mq-state", "q1", lane), list = region("data-cv-mq-activity", "q1", lane), ghost = region("data-cv-mq-state", "zzz", other); const els = [card, meter, list, ghost]; globalThis.__qa = new Proxy({}, { get: (_, sel) => (typeof sel === "string" && sel.includes("data-cv-mq-state") ? els : undefined) }); m.QueueNode.syncLive(); const onChange = globalThis.__raf.length; globalThis.__raf.splice(0).forEach((f) => f()); m.QueueNode.syncLive(); const whenQuiet = globalThis.__raf.length; return [card.innerHTML.includes("cv-q-meter") && card.innerHTML.includes("cv-q-now"), meter.innerHTML.includes("cv-q-meter") && !meter.innerHTML.includes("cv-q-now"), list.innerHTML.includes("cv-q-now") && !list.innerHTML.includes("cv-q-meter"), ghost.innerHTML, lane.dataset.tState, other.dataset.tState, onChange, whenQuiet]; })()',
     '[true,true,true,"stale","running","idle",1,0]', "фоновый тик: карточка очереди получает счётчик и списки, строка дорожки — только счётчик, внутренность дорожки — только списки; чужой идентификатор не тронут; состояние красит дорожку, а карточку и чужую дорожку — нет; изменившееся содержимое просит перерисовать точки и канаты (строки под открытой дорожкой едут), неизменившееся — нет"),
    # ── the queue policy is one line at the head of the Servers block ──
    ("queue_settings_line_summary_and_fields", '', '(() => { st.topology.proxyPolicy = { cloudFallbackPct: 5, stickySlotSec: 20, loadingModelWaitSec: 60 }; const q = qs.QUEUE_SETTINGS; const shut = q.html(); q.editing = true; const open = q.html(); q.editing = false; const want = [i18n.t("cvLabelOverflowAt") + " 5%", i18n.t("cvLabelReserve") + " 20s", i18n.t("cvLabelLoadWait") + " 60s"].join(" · "); return [q.summary() === want, q.summary(), shut.includes(`data-cv-qs-text>${want}<`), (shut.match(/data-cv-qs-toggle/g) || []).length, shut.includes(`aria-expanded="false"`), /class="cv-queue-settings"/.test(shut), open.includes(`aria-expanded="true"`), /class="cv-queue-settings open"/.test(open), (open.match(/data-cv-queue-policy=/g) || []).length]; })()',
     '[true,"overflow at 5% · reserve 20s · Loading wait 60s",true,1,true,true,true,true,3]', "строка политики: названия полей из словаря, значения и единицы через « · »; закрыта — без open, открыта — с open и aria-expanded; поля те же три в обоих состояниях"),
    ("queue_settings_pencil_opens_in_place", '', '(() => { let draws = 0; Object.defineProperty(globalThis.__q, "[data-cv-svg]", { get() { draws++; return null; }, configurable: true, enumerable: true }); const first = mkEl({ value: "5", dataset: { cvQueuePolicy: "cloudFallbackPct" }, focus() { this.focused = true; } }); const toggle = mkEl({ setAttribute(k, v) { this.attrs = { ...(this.attrs || {}), [k]: v }; } }); const text = mkEl(); const panel = mkEl({ q: { "[data-cv-qs-toggle]": toggle, "[data-cv-queue-policy]": first }, qa: { "[data-cv-queue-policy]": [first] } }); const lists = { "[data-cv-queue-settings]": [panel], "[data-cv-qs-text]": [text], "[data-cv-queue-policy]": [first] }; qs.QUEUE_SETTINGS.bind({ querySelectorAll: (sel) => lists[sel] || [] }); const base = draws; toggle.listeners.click[0](); const open = [qs.QUEUE_SETTINGS.editing, panel.classList.contains("open"), toggle.attrs["aria-expanded"], first.focused === true, draws - base > 0, text.textContent]; toggle.listeners.click[0](); return [open, [qs.QUEUE_SETTINGS.editing, panel.classList.contains("open"), toggle.attrs["aria-expanded"]], toggle.listeners.pointerdown.length]; })()',
     '[[true,true,"true",true,true,"overflow at 20% · reserve 0s · Loading wait 90s"],[false,false,"false"],1]', "карандаш открывает поля на месте: класс open, aria-expanded, фокус в первое поле, канаты нарисованы заново (блок сменил высоту); второй щелчок закрывает; нажатие на кнопку не начинает перетаскивание блока"),
    ("queue_settings_sync_leaves_unchanged_words_alone", '', '(() => { let writes = 0, value = ""; const text = mkEl(); Object.defineProperty(text, "textContent", { get() { return value; }, set(v) { writes++; value = v; }, configurable: true }); const root = { querySelectorAll: (sel) => (sel === "[data-cv-qs-text]" ? [text] : []) }; st.topology.proxyPolicy = { cloudFallbackPct: 5, stickySlotSec: 20, loadingModelWaitSec: 60 }; qs.QUEUE_SETTINGS.sync(root); const first = writes; qs.QUEUE_SETTINGS.sync(root); qs.QUEUE_SETTINGS.sync(root); const same = writes; st.topology.proxyPolicy = { cloudFallbackPct: 7, stickySlotSec: 20, loadingModelWaitSec: 60 }; qs.QUEUE_SETTINGS.sync(root); return [first, same, writes, value.startsWith(i18n.t("cvLabelOverflowAt") + " 7%")]; })()',
     '[1,1,2,true]', "строка политики переписывается только когда слова изменились: sync идёт из bind(), а bind() — из наблюдателя за любым изменением страницы, и пустая перезапись текста будила его снова и снова (страница зависала)"),
    ("servers_panel_carries_queue_settings_line", '', '(() => { const h = panels().right; const at = h.indexOf("data-cv-queue-settings"); return [(h.match(/data-cv-queue-settings/g) || []).length, h.indexOf("rw-side-head") < at, at < h.indexOf("rw-side-body")]; })()',
     '[1,true,true]', "панель серверов несёт строку политики очередей — одну, между шапкой и прокручиваемым телом"),
]

_fail = []


def check(cond, msg):
    print(("  ok  " if cond else " FAIL ") + msg)
    if not cond:
        _fail.append(msg)


def main():
    if len(PINS) < 40:
        print(f"js canvas FAILED: всего {len(PINS)} пинов — снимок урезан")
        return 1
    node = find_node()
    if node is None:
        print("js canvas: SKIPPED — node не найден: " + ", ".join(node_search_paths()))
        return 0

    def blocks(pins, sink):
        return [f"try {{ reset(); {setup}\n  {sink}[{json.dumps(pid)}] = {expr}; }} "
                f"catch (e) {{ {sink}[{json.dumps(pid)}] = {{ __threw: String(e && e.message || e) }}; }}"
                for pid, setup, expr, _exp, _msg in pins]

    # Pins don't depend on each other: the same set run in reverse order
    # must give the same values.
    probe = (PREAMBLE + "\n".join(blocks(PINS, "out")) + "\nconst rev = {};\n"
             + "\n".join(blocks(list(reversed(PINS)), "rev"))
             + "\nconsole.log(JSON.stringify({ out, rev })); process.exit(0);\n")
    harness = ROOT / "scripts" / "_js_harness.mjs"
    path = ROOT / "scripts" / ".probe_js_canvas.tmp.mjs"
    path.write_text(probe)
    try:
        env = {**os.environ, "JS_ROOT": str(ROOT / "static" / "js"), "JS_STUBS": STUBS,
               "LANG": "en_US.UTF-8", "LC_ALL": "en_US.UTF-8", "TZ": "UTC"}
        run = subprocess.run(
            [node, "--import",
             f"data:text/javascript,import {{ register }} from 'node:module'; register('{harness.as_uri()}');",
             str(path)], capture_output=True, text=True, env=env, cwd=ROOT, timeout=120)
    finally:
        path.unlink(missing_ok=True)
    if run.returncode != 0:
        print(run.stdout); print(run.stderr)
        print(f"js canvas FAILED: node вышел с кодом {run.returncode}")
        return 1
    both = json.loads(run.stdout.strip().splitlines()[-1])
    got, rev = both["out"], both["rev"]
    print("канбан: узлы, рёбра графа, геометрия, перетаскивание:")
    for pid, _s, _e, expected, msg in PINS:
        want, have = json.loads(expected), got.get(pid, "\0missing")
        check(have == want, msg if have == want else
              f"{msg}\n        ожидалось {json.dumps(want, ensure_ascii=False)[:200]}"
              f"\n        получено  {json.dumps(have, ensure_ascii=False)[:200]}")
        if have != rev.get(pid, "\0missing"):
            _fail.append(f"пин {pid} зависит от порядка")
    print(f"порядок: {len(PINS)} пинов дают те же значения в обратном порядке" if not _fail else "")
    print()
    if _fail:
        print(f"FAILED ({len(_fail)}):")
        for m in _fail:
            print("  - " + m.splitlines()[0])
        return 1
    print(f"js canvas OK: настоящий модуль в node, {len(PINS)} пинов канбана значениями")
    return 0


if __name__ == "__main__":
    sys.exit(main())
