#!/usr/bin/env python3
"""Снимок static/js/topology-dnd.js — делегированный биндер доски.

`bindTopologyDragAndDrop` вешает слушатели на ~сотню селекторов после каждого
рендера. Снимок заполняет словарь селекторов элементами, зовёт биндер и
дёргает слушатели, а пинит СЛЕДСТВИЯ: вызовы соседей (заглушки с записью),
состояние `ui`, модульные флаги модалов, тексты общего confirm и что делает
его подтверждение. Что здесь важно: ключ порта — «не требовать ключ»
очищает поле, а снятие галки с пустым полем ГЕНЕРИРУЕТ ключ (пустое поле
сохранилось бы как «открыто»); удаление блока облака перечисляет, кто на
него ссылается (мосты, роли очереди, правила, кабели) — и не зависит от
отказа этого перечисления; удаление прокси называет привязанных агентов;
радио «default» откатывается до подтверждения, а подтверждение снимает
`dormantDefault`; ползунки порогов: мышь/клавиши, минимум 1% у abort,
живая подпись секундами; перетаскивание строк приоритета выше/ниже;
расписание — сетка из правил, кисть, очистка, сохранение через saveRouters,
рисование pointerdown/over; failover — цепочка с default первым или
выключение; вход/выход прокси в роутер — с подтверждением; hover-подсветка
кабелей; детали маршрута сохраняют диапазон при том же маршруте.

DOM — словарь селекторов; elementFromPoint — стаб; rAF синхронный.

Запуск: python3 scripts/test_js_topology_dnd.py
"""
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _node import find_node, node_search_paths  # noqa: E402

STUBS = ("dialogs,cables,canvas,charts,cloud,remote-cells,history,llama-edit,routers,topology-activity,topology-modals,"
         "topology-nodes,topology-proxies,topology-render,usage-stats,favorites,config-locator,system-panels,onboarding,"
         "onboarding-tours,dialog-llamas,models-page,system-page,memory,command-preview,llama-edit,polling,form,model-meta")

PREAMBLE = r"""
import "./_js_globals.mjs";
import { pathToFileURL } from "node:url";
const st = await import(pathToFileURL(process.env.JS_ROOT + "/state.js").href);
st.setState({ config: {} }); st.setTopology({ proxies: [], clients: [], routers: [], assignments: {} });
globalThis.requestAnimationFrame = (fn) => { fn(); return 0; }; globalThis.CSS = { escape: (s) => String(s) };
globalThis.__opened = []; globalThis.open = (u) => { globalThis.__opened.push(String(u)); };
const G = () => Array.from({ length: 7 }, () => Array(24).fill(""));
globalThis.__stubValues = { "canvas._cvQueueHistOpen": {}, "canvas._cvQueueHistData": {}, "canvas._cvSchedHistOpen": {}, "canvas._cvSchedHistData": {}, "canvas._cvPos": {}, "canvas._cvView": {},
  "cloud.topologyCloudBlockForm": { blockId: "cb:x", model: "gpt-x" }, "routers.topologyOutputsCloudExpanded": {}, "routers.topologyOutputsFolded": {},
  "topology-modals.topologyPriorityOrder": [], "topology-modals.topologyQueuePriorityEdits": {}, "topology-modals.topologyAgentConfigClientId": "box-a", "topology-modals.topologyAgentConfigAgentId": "hermes",
  "usage-stats.subscriptionUsageCache": new Map(), "usage-stats.apiCostsCache": new Map(), "usage-stats.openrouterLimitsCache": new Map(), "usage-stats.usageStatsApiPriceEdit": {}, "usage-stats.usageStatsData": { rate: { inputPer1M: 1, outputPer1M: 2 } } };
const cls = () => { const s = new Set(); return { add: (...c) => c.forEach((x) => s.add(x)), remove: (...c) => c.forEach((x) => s.delete(x)), toggle: (c, on) => (on === undefined ? (s.has(c) ? s.delete(c) : s.add(c)) : (on ? s.add(c) : s.delete(c))), has: (c) => s.has(c), list: () => [...s].sort() } };
const mkEl = (props = {}) => { const e = { tagName: "DIV", dataset: {}, listeners: {}, classList: cls(), style: {}, value: "", checked: false, hidden: false, textContent: "", children: [], parent: null, rect: { left: 0, top: 0, width: 100, height: 20 },
  addEventListener(t, fn) { (this.listeners[t] ||= []).push(fn); }, getBoundingClientRect() { return this.rect; }, closest(sel) { return this.q?.[sel] ?? (this.parent ? this.parent.closest(sel) : null); }, querySelector(sel) { return this.q?.[sel] ?? null; }, querySelectorAll(sel) { return this.qa?.[sel] ?? []; }, remove() { this.removed = true; }, ...props }; return e; };
globalThis.__q = {}; globalThis.__qa = {};
document.querySelector = (sel) => (Object.prototype.hasOwnProperty.call(globalThis.__q, sel) ? globalThis.__q[sel] : null);
document.querySelectorAll = (sel) => globalThis.__qa[sel] || [];
document.getElementById = (id) => (Object.prototype.hasOwnProperty.call(globalThis.__fields, id) ? globalThis.__fields[id] : null);
const docListeners = {}; document.addEventListener = (t, fn) => { (docListeners[t] ||= []).push(fn); if (t === "pointerup") globalThis.__pointerUp = fn; }; document.removeEventListener = (t, fn) => { const l = docListeners[t] || []; const i = l.indexOf(fn); if (i >= 0) l.splice(i, 1); };
globalThis.__atPoint = null; document.elementFromPoint = () => globalThis.__atPoint;
const m = await import(pathToFileURL(process.env.JS_ROOT + "/topology-dnd.js").href);
const V = (key) => globalThis.__stubValues[key];
globalThis.__calls = []; const isEventLike = (x) => x && typeof x === "object" && (x.listeners || "target" in x || typeof x.preventDefault === "function" || "currentTarget" in x);
const arg = (x) => (typeof x === "function" ? "fn" : isEventLike(x) ? null : x);
const rec = (name, ret) => (...a) => { globalThis.__calls.push([name, ...a.map(arg)]); return ret; }; const arec = (name, ret) => async (...a) => { globalThis.__calls.push([name, ...a.map(arg)]); return ret; };
const calls = () => globalThis.__calls; const names = () => globalThis.__calls.map((c) => c[0]);
const one = (sel, props = {}) => { const e = mkEl(props); globalThis.__q[sel] = e; return e; };
const many = (sel, ...list) => { const els = list.map((p) => mkEl(p)); globalThis.__qa[sel] = els; return els; };
const F = () => globalThis.__fields; const fire = (el, type, ev = {}) => (el.listeners[type] || []).forEach((fn) => fn(ev));
const confirmState = () => ({ title: F().confirmTitle.textContent, text: F().confirmText.textContent, path: F().confirmPath.textContent, ok: F().confirmDelete.textContent, danger: F().confirmDelete.classList.has("danger"), shown: !F().confirmOverlay.hidden });
const settle = async () => { for (let i = 0; i < 4; i++) await new Promise((r) => setImmediate(r)); };
const ROUTERS = () => [{ id: "router:a", outputs: [{ id: "srv:1" }, { id: "cb:x" }, { id: "srv:2" }], rules: { default: "cb:x", dormantDefault: "srv:1", schedule: [{ days: ["mon"], from: "09:00", to: "10:59", output: "srv:1" }], bySource: [{ proxyId: "p1", output: "srv:1" }, { proxyId: "p2", output: "srv:2" }], failover: [] } }];
const reset = () => { st.setTopology({ proxies: [{ id: "skynet:proxy:23001", port: 23001, label: "hermes", priority: 2 }, { id: "skynet:proxy:23002", port: 23002, label: "" }], clients: [{ id: "box-a", agents: [{ id: "hermes", name: "Hermes" }] }], routers: ROUTERS(), assignments: { "box-a": { assignments: [{ agentId: "hermes", routes: [{ role: "primary", proxyId: "skynet:proxy:23001" }] }] } }, cloudAccounts: [{ id: "acct", name: "OpenAI" }], cloudProviders: [{ id: "cb:x", accountId: "acct", exposed: true, unlisted: true }, { id: "cb:y", accountId: "acct", exposed: false }], proxyPolicy: { cloudFallbackPct: 20, priorityPreemptPct: 50, queueAbortPct: 85 } });
  st.ui.pendingConfirm = null; st.ui.topologyCloudForm = null; st.ui.topologyProxyFormOpen = true; st.ui.topologyProxyEditingId = "skynet:proxy:23001"; st.ui.topologyRouterDetailId = "router:a"; st.ui.topologyCanvasRouterId = ""; st.ui.topologyAgentConfigMode = "ports"; st.ui.usageStatsModalOpen = true; st.ui.usageStatsExpanded = ""; st.ui.usageStatsRateEdit = null; st.ui.topologyRouterInputsExpanded = false; st.ui.topologyCloudPickerOpen = false; st.ui.topologyCloudModalOpen = true;
  globalThis.__q = {}; globalThis.__qa = {}; globalThis.__calls = []; globalThis.__opened.length = 0; globalThis.__atPoint = null; for (const k of Object.keys(docListeners)) delete docListeners[k];
  globalThis.__fields = { confirmTitle: mkEl(), confirmText: mkEl(), confirmPath: mkEl(), confirmMeta: mkEl(), confirmDelete: mkEl(), confirmOverlay: mkEl({ hidden: true }), toast: mkEl(), topologyCables: mkEl() };
  globalThis.__fetchCalls.length = 0; globalThis.__fetchReply = {};
  for (const k of ["canvas._cvQueueHistOpen", "canvas._cvQueueHistData", "canvas._cvSchedHistOpen", "canvas._cvSchedHistData", "routers.topologyOutputsCloudExpanded", "routers.topologyOutputsFolded", "topology-modals.topologyQueuePriorityEdits", "usage-stats.usageStatsApiPriceEdit"]) for (const kk of Object.keys(V(k))) delete V(k)[kk];
  V("topology-modals.topologyPriorityOrder").length = 0; V("usage-stats.subscriptionUsageCache").clear(); V("usage-stats.apiCostsCache").clear(); V("usage-stats.openrouterLimitsCache").clear(); Object.assign(V("cloud.topologyCloudBlockForm"), { blockId: "cb:x", model: "gpt-x" });
  globalThis.__stubReturns = { "topology-render.renderTopology": rec("renderTopology"), "topology-render.flushPendingTopologyRender": rec("flushPendingTopologyRender"), "llama-edit.closeConfirmModal": rec("closeConfirmModal"), "dialogs.appConfirm": arec("appConfirm", true),
    "topology-modals.openAgentConfigModal": arec("openAgentConfigModal"), "topology-modals.closeAgentConfigModal": rec("closeAgentConfigModal"), "topology-modals.openClientDetail": rec("openClientDetail"), "topology-modals.closeClientDetail": rec("closeClientDetail"), "topology-modals.refreshClientDetail": arec("refreshClientDetail"), "topology-modals.openQueuePriorityModal": rec("openQueuePriorityModal"), "topology-modals.closeQueuePriorityModal": rec("closeQueuePriorityModal"), "topology-modals.saveQueuePriorityModal": arec("saveQueuePriorityModal"), "topology-modals.openRawConfigViewer": arec("openRawConfigViewer"), "topology-modals.closeRawConfigViewer": rec("closeRawConfigViewer"), "topology-modals.closePriorityModal": rec("closePriorityModal"), "topology-modals.savePriorityModal": arec("savePriorityModal"), "topology-modals.setTopologyProxyRoutePolicy": arec("setTopologyProxyRoutePolicy"), "topology-modals.editTopologyClientAlias": arec("editTopologyClientAlias"), "topology-modals._fmtSec": (s) => s + "s", "topology-modals._queuePctExampleText": (a, b, c) => `ex ${a}/${b}/${c}`, "topology-modals.scheduleRulesToGrid": (r) => { const g = G(); for (const rule of (r?.rules?.schedule || [])) g[0][9] = rule.output; return g; }, "topology-modals.scheduleGridToRules": rec("scheduleGridToRules", [{ days: ["mon"], from: "09:00", to: "09:59", output: "srv:1" }]),
    "topology-proxies.saveTopologyProxyForm": arec("saveTopologyProxyForm"), "topology-proxies.editTopologyProxy": rec("editTopologyProxy"), "topology-proxies.deleteTopologyProxy": arec("deleteTopologyProxy"), "history.openRequestHistory": rec("openRequestHistory"), "charts.openRouteActivityModal": rec("openRouteActivityModal"), "charts.closeRouteActivityModal": rec("closeRouteActivityModal"), "charts.openChartModal": rec("openChartModal"), "charts.closeChartModal": rec("closeChartModal"), "topology-nodes.closeIncidentsModal": rec("closeIncidentsModal"),
    "cloud.closeCloudProviderModal": rec("closeCloudProviderModal"), "cloud.saveCloudAccount": arec("saveCloudAccount"), "cloud.deleteCloudAccount": arec("deleteCloudAccount"), "cloud.startCloudOauthLogin": arec("startCloudOauthLogin"), "cloud.closeCloudBlockModal": rec("closeCloudBlockModal"), "cloud.saveCloudBlock": arec("saveCloudBlock"), "cloud.deleteCloudBlock": arec("deleteCloudBlock"), "cloud.selectCloudProviderType": rec("selectCloudProviderType"),
    "usage-stats.fetchSubscriptionUsage": rec("fetchSubscriptionUsage"), "usage-stats.fetchApiCosts": rec("fetchApiCosts"), "usage-stats.fetchOpenRouterLimits": rec("fetchOpenRouterLimits"), "usage-stats.fetchUsageStats": rec("fetchUsageStats"), "usage-stats.saveLocalPricing": rec("saveLocalPricing"), "usage-stats.saveApiPrice": rec("saveApiPrice"),
    "routers.routerById": (routers, id) => routers.find((r) => r.id === id), "routers.saveRouters": async (mut) => { const copy = JSON.parse(JSON.stringify(st.topology.routers)); mut(copy); globalThis.__calls.push(["saveRouters", copy]); }, "routers.setCloudModelExposed": rec("setCloudModelExposed"),
    "topology-activity.proxyEffectiveWaitTimeout": () => 1800, "topology-activity.loadRouteTokenHistory": rec("loadRouteTokenHistory"), "cables.highlightTopologyCable": rec("highlightTopologyCable"), "cables.scheduleClearTopologyCableHighlight": rec("scheduleClearTopologyCableHighlight"), "cables.topologyRouteClass": (h, a, r) => `route-${h}-${a}-${r}`, "cables.topologyProxyClass": (id) => `proxy-${id}`,
    "canvas.cvSetViewport": rec("cvSetViewport"), "canvas.canvasLoadPositions": rec("canvasLoadPositions", { n: 1 }), "canvas.drawCanvasConnectors": rec("drawCanvasConnectors"), "canvas.bindCanvasInteractions": rec("bindCanvasInteractions"), "canvas._fetchQueueHist": rec("_fetchQueueHist"), "canvas._fetchSchedHist": rec("_fetchSchedHist"), "canvas.scheduleOutputColor": (r, o) => (o ? "#c0ffee" : ""),
    "remote-cells.addTopologyAgent": arec("addTopologyAgent"), "remote-cells.renameTopologyAgent": arec("renameTopologyAgent") }; };
reset();
const bind = () => m.bindTopologyDragAndDrop();
const out = {};
"""

PINS = [
    ("agent_config_open_close_refresh_mode", '', 'await (async () => { const [btn] = many("[data-agent-config-open]", { dataset: { agentConfigOpen: "raw", clientId: "box-a", agentId: "hermes" } }); const close = one("[data-agent-config-close]"); const ov = one("[data-agent-config-overlay]"); const rf = one("[data-agent-config-refresh]"); const [mode] = many("[data-agent-config-mode]", { dataset: { agentConfigMode: "ports" } }); bind(); let sp = 0; fire(btn, "click", { stopPropagation: () => sp++ }); fire(close, "click"); fire(ov, "click", { target: { dataset: { agentConfigOverlay: "" } } }); fire(ov, "click", { target: { dataset: {} } }); fire(rf, "click"); st.ui.topologyAgentConfigMode = ""; fire(rf, "click"); fire(mode, "click"); await settle(); return [sp, calls().filter((c) => c[0] === "openAgentConfigModal").map((c) => c.slice(1)), names().filter((x) => x === "closeAgentConfigModal").length, st.ui.topologyAgentConfigMode, names().at(-1)]; })()',
     '[1,[["box-a","hermes","raw"],["box-a","hermes","ports"]],2,"ports","renderTopology"]', "конфиг агента: открыть в режиме, закрыть кнопкой и подложкой (не содержимым), обновить только при открытом режиме, смена режима перерисовывает"),
    ("proxy_nokey_clears_and_regenerates_key", '', '(() => { const nokey = one("[data-proxy-nokey]"); const label = one("[data-topology-proxy-form] .proxy-apikey-label"); const input = one(\'[data-topology-proxy-form] [name="apiKey"]\', { value: "lcv1_old" }); bind(); fire(nokey, "change", { target: { checked: true } }); const a = [label.hidden, input.value]; fire(nokey, "change", { target: { checked: false } }); const b = [label.hidden, /^lcv1_[0-9a-f]{32}$/.test(input.value)]; input.value = "keep"; fire(nokey, "change", { target: { checked: false } }); return [...a, ...b, input.value]; })()',
     '[true,"",false,true,"keep"]', "«не требовать ключ»: поле очищено и спрятано; снятие галки с ПУСТЫМ полем генерирует ключ (пустое сохранилось бы как «открыто»); непустое не трогается"),
    ("proxy_genkey_and_overlay", '', '(() => { const gen = one("[data-proxy-genkey]"); const input = one(\'[data-topology-proxy-form] [name="apiKey"]\'); const ov = one("[data-topology-proxy-overlay]"); bind(); fire(gen, "click"); const key = input.value; fire(ov, "click", { target: { dataset: {} } }); const still = st.ui.topologyProxyFormOpen; fire(ov, "click", { target: { dataset: { topologyProxyOverlay: "" } } }); return [/^lcv1_[0-9a-f]{48}$/.test(key), still, st.ui.topologyProxyFormOpen, st.ui.topologyProxyEditingId, names().includes("renderTopology")]; })()',
     '[true,true,false,"",true]', "генерация ключа — 24 байта hex с префиксом; подложка формы прокси закрывает форму и сбрасывает редактируемый id"),
    ("history_route_activity_chart_incidents", '', '(() => { F().topologyRequestHistoryBtn = mkEl(); const [ra] = many("[data-open-route-activity]", { dataset: { routeNode: "box-a" } }); F().routeActivityClose = mkEl(); F().routeActivityOverlay = mkEl(); const [ch] = many("[data-open-chart]", { dataset: { openChart: "gpu" } }); F().chartExpandClose = mkEl(); F().chartExpandOverlay = mkEl(); F().incidentsModalClose = mkEl(); F().incidentsModalOverlay = mkEl(); bind(); fire(F().topologyRequestHistoryBtn, "click"); fire(ra, "click"); fire(F().routeActivityClose, "click"); fire(F().routeActivityOverlay, "click", { target: F().routeActivityOverlay }); fire(F().routeActivityOverlay, "click", { target: {} }); fire(ch, "click"); fire(F().chartExpandOverlay, "click", { target: F().chartExpandOverlay }); fire(F().incidentsModalClose, "click"); return [names(), calls().find((c) => c[0] === "openRouteActivityModal")[1], calls().find((c) => c[0] === "openChartModal")[1]]; })()',
     '[["openRequestHistory","openRouteActivityModal","closeRouteActivityModal","closeRouteActivityModal","openChartModal","closeChartModal","closeIncidentsModal"],"box-a","gpu"]', "история, активность маршрутов узла, графики, инциденты: открытие с аргументом, закрытие кнопкой и подложкой (не содержимым)"),
    ("cloud_account_modal_and_delete_confirm", '', 'await (async () => { one("[data-cloud-close]"); const cancel = one("[data-cloud-cancel]"); const ov = one("[data-topology-cloud-overlay]"); const save = one("[data-cloud-save]"); const del = one("[data-cloud-delete-account]"); bind(); fire(cancel, "click"); fire(ov, "click", { target: { dataset: { topologyCloudOverlay: "" } } }); fire(save, "click"); st.ui.topologyCloudForm = { accountId: "acct" }; fire(del, "click"); const c = confirmState(); st.ui.pendingConfirm(); await settle(); return [names().filter((x) => x === "closeCloudProviderModal").length, names().includes("saveCloudAccount"), c.text.includes("OpenAI"), c.danger, c.shown, names().slice(-2)]; })()',
     '[2,true,true,true,true,["closeConfirmModal","deleteCloudAccount"]]', "модал аккаунта: отмена и подложка закрывают, сохранение; удаление — красный confirm с именем аккаунта, подтверждение закрывает confirm и удаляет"),
    ("usage_refresh_delegation_clears_caches", '', '(() => { const lane = mkEl(); F().topologyCloudProviders = lane; bind(); V("usage-stats.subscriptionUsageCache").set("acct", 1); V("usage-stats.apiCostsCache").set("acct", 1); V("usage-stats.openrouterLimitsCache").set("acct", 1); let sp = 0; const ev = (kind, id) => ({ stopPropagation: () => sp++, target: { closest: (s) => (s === kind ? { dataset: { usageRefresh: id, apiCostsRefresh: id, orLimitsRefresh: id } } : null) } }); fire(lane, "click", ev("[data-usage-refresh]", "acct")); fire(lane, "click", ev("[data-api-costs-refresh]", "acct")); fire(lane, "click", ev("[data-or-limits-refresh]", "acct")); fire(lane, "click", ev("nothing", "acct")); return [sp, V("usage-stats.subscriptionUsageCache").size, V("usage-stats.apiCostsCache").size, V("usage-stats.openrouterLimitsCache").size, calls().map((c) => c.join(":"))]; })()',
     '[3,0,0,0,["fetchSubscriptionUsage:acct","fetchApiCosts:acct","fetchOpenRouterLimits:acct"]]', "обновление расходов по клику в лейне: кэш сброшен и перезапрошен для своего вида, клик мимо — ничего"),
    ("cloud_fields_and_oauth", '', '(() => { const [auth, cid, port, name] = many("[data-cloud-field]", { tagName: "SELECT", dataset: { cloudField: "authMode" }, value: "oauth" }, { tagName: "INPUT", dataset: { cloudField: "oauthClientId" }, value: "cid" }, { tagName: "INPUT", dataset: { cloudField: "oauthRedirectPort" }, value: "1455" }, { tagName: "INPUT", dataset: { cloudField: "name" }, value: "N" }); const login = one("[data-cloud-oauth-login]"); bind(); fire(name, "input"); const noForm = st.ui.topologyCloudForm; st.ui.topologyCloudForm = {}; fire(auth, "change"); fire(cid, "input"); fire(port, "input"); fire(name, "input"); fire(login, "click"); return [noForm, st.ui.topologyCloudForm, names().includes("renderTopology"), names().includes("startCloudOauthLogin"), !!auth.listeners.change, !!name.listeners.input]; })()',
     '[null,{"authMode":"oauth","oauthConfig":{"clientId":"cid","redirectPort":1455},"name":"N"},true,true,true,true]', "поля аккаунта: select — change, input — input; без формы игнор; authMode перерисовывает; oauth-поля в oauthConfig, порт числом; вход по OAuth"),
    ("block_modal_delete_preflight_lists_refs", 'globalThis.__fetchReply["/api/cloud-blocks/refs?id=cb%3Ax"] = { refs: { bridges: [{ port: 8083, label: "voice" }], queueRoles: [{ role: "spill" }], rules: [{ rule: "schedule" }], edges: [1, 2] } };', 'await (async () => { const del = one("[data-cloud-delete-block]"); one("[data-cloud-block-close]"); const save = one("[data-cloud-block-save]"); bind(); fire(save, "click"); await fire(del, "click"); await settle(); const c = confirmState(); st.ui.pendingConfirm(); await settle(); return [names().includes("saveCloudBlock"), c.text.includes("gpt-x"), c.path.includes("⚠"), c.path.includes("8083") && c.path.includes("voice"), c.path.includes("spill"), c.path.includes("schedule"), c.path.split("•").length - 1, c.danger, names().slice(-2)]; })()',
     '[true,true,true,true,true,true,4,true,["closeConfirmModal","deleteCloudBlock"]]', "удаление блока: преflight перечисляет мосты, роли очереди, правила и число кабелей; блок не в списке провайдера — ⚠; подтверждение удаляет"),
    ("block_delete_preflight_failure_tolerated", 'globalThis.__fetchReply["/api/cloud-blocks/refs?id=cb%3Ax"] = { __status: 500, error: "boom" };', 'await (async () => { const del = one("[data-cloud-delete-block]"); bind(); await fire(del, "click"); await settle(); const c = confirmState(); return [c.shown, c.path.includes("•"), c.path.length > 0]; })()',
     '[true,false,true]', "negative: отказ перечисления ссылок не мешает удалению — confirm показан с «ссылок нет»"),
    ("block_fields_picker_and_change", '', '(() => { const [f] = many("[data-block-field]", { tagName: "INPUT", dataset: { blockField: "model" }, value: "m2" }); const [tile] = many("[data-pick-type]", { dataset: { pickType: "ollama" } }); const change = one("[data-cloud-picker-change]"); one("[data-cloud-picker-close]"); bind(); fire(f, "input"); fire(tile, "click"); fire(change, "click"); return [V("cloud.topologyCloudBlockForm").model, calls().find((c) => c[0] === "selectCloudProviderType")?.[1], st.ui.topologyCloudPickerOpen, st.ui.topologyCloudModalOpen, st.ui.topologyCloudForm]; })()',
     '["m2","ollama",true,false,null]', "поля блока пишут в форму блока; плитка пикера выбирает тип; «сменить тип» открывает пикер и сбрасывает форму"),
    ("client_detail_open_resolves_agent_name", '', '(() => { const [row, btn] = many("[data-topology-client-detail]", { tagName: "DIV", dataset: { topologyClientDetail: "box-a", agentId: "hermes" } }, { tagName: "BUTTON", dataset: { topologyClientDetail: "box-a" } }); one("[data-topology-client-detail-close]"); const rf = one("[data-topology-client-detail-refresh]"); bind(); fire(row, "click"); let p = 0; fire(row, "keydown", { key: "Enter", preventDefault: () => p++ }); fire(row, "keydown", { key: "x", preventDefault: () => p++ }); fire(btn, "click"); fire(rf, "click"); return [calls().filter((c) => c[0] === "openClientDetail").map((c) => c.slice(1)), p, !!btn.listeners.keydown, names().includes("refreshClientDetail")]; })()',
     '[[["box-a","Hermes"],["box-a","Hermes"],["box-a",""]],1,false,true]', "детали клиента: имя агента по id из topology; Enter/пробел на не-кнопке, кнопка без keydown; обновление"),
    ("gpu_and_llama_detail_flags", '', '(() => { const [g] = many("[data-topology-gpu-modal]", {}); const gc = one("[data-topology-gpu-modal-close]"); const [l] = many("[data-topology-llama-detail]", {}); const lo = one("[data-topology-llama-detail-overlay]"); bind(); fire(g, "keydown", { key: " ", preventDefault() {} }); const a = m.topologyGpuModalOpen; fire(gc, "click"); fire(l, "click"); const b = m.topologyLlamaDetailOpen; fire(lo, "click", { target: { dataset: {} } }); const c = m.topologyLlamaDetailOpen; fire(lo, "click", { target: { dataset: { topologyLlamaDetailOverlay: "" } } }); return [a, m.topologyGpuModalOpen, b, c, m.topologyLlamaDetailOpen, names().filter((x) => x === "renderTopology").length]; })()',
     '[true,false,true,true,false,4]', "флаги модалов GPU и модели: открыть (клавиатурой тоже), закрыть кнопкой/подложкой, содержимое не закрывает; каждая смена перерисовывает"),
    ("usage_stats_controls", '', '(() => { const close = one("[data-usage-stats-close]"); const [d7] = many("[data-usage-stats-days]", { dataset: { usageStatsDays: "7" } }); const [sc] = many("[data-usage-stats-scope]", { dataset: { usageStatsScope: "cloud" } }); const [mdl] = many("[data-usage-stats-model]", { dataset: { usageStatsModel: "gpt" } }); const [rate] = many("[data-usage-stats-rate]", { dataset: { usageStatsRate: "inputPer1M" }, value: "3" }); const rs = one("[data-usage-stats-rate-save]"); const [ap] = many("[data-us-apiprice]", { dataset: { usApipriceModel: "gpt", usApiprice: "outputPer1M" }, value: "9" }); const [aps] = many("[data-us-apiprice-save]", { dataset: { usApipriceSave: "gpt" } }); bind(); st.ui.usageStatsExpanded = "x"; fire(d7, "click"); const days = [st.ui.usageStatsDays, st.ui.usageStatsExpanded]; fire(sc, "click"); fire(mdl, "click"); const exp1 = st.ui.usageStatsExpanded; fire(mdl, "click"); fire(rate, "input"); fire(rs, "click"); let sp = 0; fire(ap, "input"); fire(ap, "click", { stopPropagation: () => sp++ }); fire(aps, "click", { stopPropagation: () => sp++ }); fire(close, "click"); return [days, st.ui.usageStatsScope, exp1, st.ui.usageStatsExpanded, st.ui.usageStatsRateEdit, JSON.parse(JSON.stringify(V("usage-stats.usageStatsApiPriceEdit"))), sp, calls().filter((c) => ["fetchUsageStats", "saveLocalPricing", "saveApiPrice"].includes(c[0])).map((c) => c[0] + (typeof c[1] === "string" ? ":" + c[1] : "")), st.ui.usageStatsModalOpen]; })()',
     '[[7,""],"cloud","gpt","",{"inputPer1M":3,"outputPer1M":2},{"gpt":{"outputPer1M":9}},2,["fetchUsageStats","saveLocalPricing","saveApiPrice:gpt"],false]',
     "статистика расходов: дни (сброс раскрытия) → запрос, область, раскрытие модели туда-обратно, правка курса поверх текущего, цена API по модели без сворачивания строки, закрытие"),
    ("queue_priority_raw_priority_modals", '', 'await (async () => { const [qp] = many("[data-topology-queue-priority-open]", {}); const qc = one("[data-topology-queue-priority-close]"); const qs = one("[data-topology-queue-priority-save]"); const raw = one("[data-topology-raw-config]"); one("[data-topology-raw-close]"); const pc = one("[data-topology-priority-cancel]"); const ps = one("[data-topology-priority-save]"); bind(); fire(qp, "keydown", { key: "Enter", preventDefault() {} }); fire(qc, "click"); fire(qs, "click"); fire(raw, "click"); fire(pc, "click"); fire(ps, "click"); await settle(); return [names(), calls()[0][1]]; })()',
     '[["openQueuePriorityModal","closeQueuePriorityModal","saveQueuePriorityModal","openRawConfigViewer","closePriorityModal","savePriorityModal"],null]', "модалы очереди/сырого конфига/приоритетов: открыть, закрыть, сохранить — через свои функции"),
    ("priority_remove_and_drag_reorder", '', '(() => { const order = V("topology-modals.topologyPriorityOrder"); order.push("a", "b", "c"); const [rm] = many("[data-priority-remove]", { dataset: { priorityRemove: "b" } }); const [ra, rc] = many("[data-priority-row]", { dataset: { priorityRow: "a" }, rect: { top: 0, height: 20 } }, { dataset: { priorityRow: "c" }, rect: { top: 100, height: 20 } }); bind(); fire(rm, "click"); const afterRemove = [...order]; fire(rm, "click"); const dt = { data: "", setData(_, v) { this.data = v; }, getData() { return this.data; } }; fire(ra, "dragstart", { dataTransfer: dt }); fire(rc, "dragover", { preventDefault() {}, dataTransfer: dt, clientY: 115 }); const marks = [rc.classList.has("drop-below"), rc.classList.has("drop-above")]; fire(rc, "drop", { preventDefault() {}, dataTransfer: dt, clientY: 115 }); const below = [...order]; fire(ra, "dragstart", { dataTransfer: dt }); fire(ra, "drop", { preventDefault() {}, dataTransfer: dt, clientY: 0 }); const self = [...order]; fire(ra, "dragstart", { dataTransfer: dt }); fire(rc, "drop", { preventDefault() {}, dataTransfer: dt, clientY: 101 }); return [afterRemove, marks, below, self, [...order], ra.classList.has("dragging")]; })()',
     '[["a","c"],[true,false],["c","a"],["c","a"],["a","c"],true]', "приоритеты: удаление из списка (повтор — ничего), бросок ниже цели ставит после неё, на себя — ничего, ВЫШЕ цели — перед ней"),
    ("qp_proxy_handle_mouse_keys_and_reset", '', '(() => { const edits = V("topology-modals.topologyQueuePriorityEdits"); const fill = mkEl(); const track = mkEl({ rect: { left: 100, width: 200 }, q: { "[data-qp-proxy-fill]": fill } }); const timeEl = mkEl(); const [h] = many("[data-qp-proxy-handle]", { dataset: { qpProxyHandle: "23001", qpPctKey: "queueAbortPct" }, style: { left: "85%" }, q: { "[data-qp-proxy-track]": track, ".qp-handle-time": timeEl } }); const [rst] = many("[data-qp-proxy-reset]", { dataset: { qpProxyReset: "23001" } }); bind(); fire(h, "mousedown", { preventDefault() {} }); docListeners.mousemove[0]({ clientX: 100 }); const atMin = [edits.routes[23001].queueAbortPct, h.style.left, timeEl.textContent, fill.style.width]; docListeners.mousemove[0]({ clientX: 250 }); docListeners.mouseup[0](); const after = [edits.routes[23001].queueAbortPct, docListeners.mousemove.length]; fire(h, "keydown", { key: "ArrowRight", preventDefault() {} }); fire(h, "keydown", { key: "ArrowLeft", preventDefault() {} }); fire(h, "keydown", { key: "ArrowLeft", preventDefault() {} }); const keys = edits.routes[23001].queueAbortPct; fire(rst, "click"); return [atMin, after, keys, edits.routes[23001], names().includes("renderTopology")]; })()',
     '[[1,"1%","18s","1%"],[75,0],74,{"cloudFallbackPct":null,"priorityPreemptPct":null,"queueAbortPct":null},true]', "ползунок прокси: мышь — процент от трека с минимумом 1% у abort, живая подпись секундами (1800 с × 1%) и заливка; отпускание снимает слушатели; стрелки ±1; сброс — три null и перерисовка"),
    ("qp_policy_inputs_and_global_handles", '', '(() => { const edits = V("topology-modals.topologyQueuePriorityEdits"); const [num, chk] = many("[data-topology-qp-policy]", { type: "number", dataset: { topologyQpPolicy: "stickySlotSec" }, value: "15" }, { type: "checkbox", dataset: { topologyQpPolicy: "preemptEnabled" }, checked: false }); const fill = mkEl(); const pctEl = mkEl(); const hc = mkEl({ dataset: { qpHandle: "cloudFallbackPct" }, style: {}, q: { ".qp-handle-pct": pctEl } }); const ha = mkEl({ dataset: { qpHandle: "queueAbortPct" }, style: {}, q: {} }); const track = one("[data-qp-track]", { rect: { left: 0, width: 100 }, q: { "[data-qp-fill]": fill }, qa: { "[data-qp-handle]": [hc, ha] } }); const ex = one("[data-qp-example]"); bind(); fire(num, "input"); num.value = "abc"; fire(num, "input"); fire(chk, "change", { target: chk }); chk.checked = true; fire(chk, "change"); fire(hc, "keydown", { key: "ArrowUp", preventDefault() {} }); const a = [edits.cloudFallbackPct, hc.style.left, pctEl.textContent, ex.textContent, fill.style.width]; fire(ha, "mousedown", { preventDefault() {} }); docListeners.mousemove.at(-1)({ clientX: -50 }); docListeners.mouseup.at(-1)(); return [edits.stickySlotSec, edits.preemptEnabled, a, edits.queueAbortPct, fill.style.width]; })()',
     '[15,true,[21,"21%","21%","ex 21/50/85","85%"],1,"1%"]', "политика: число только конечное, галка; глобальные ползунки: стрелка от политики (+1), подпись/пример/заливка живые; мышь левее трека — минимум 1% у abort"),
    ("route_detail_open_keeps_range_for_same_route", '', '(() => { const [row] = many("[data-topology-route-detail]", { dataset: { topologyRouteDetail: "skynet:proxy:23001", clientIp: "10.0.0.7", clientName: "box" } }); const [row2] = [mkEl({ dataset: { topologyRouteDetail: "skynet:proxy:29999" } })]; globalThis.__qa["[data-topology-route-detail]"].push(row2); const [rng] = many("[data-token-range]", { dataset: { tokenRange: "24h" } }); const close = one("[data-topology-route-detail-close]"); bind(); fire(row, "click", { target: { closest: () => null } }); const first = { ...m.topologyRouteDetail }; fire(rng, "click"); const ranged = m.topologyRouteDetail.range; fire(row, "click", { target: { closest: () => null } }); const kept = m.topologyRouteDetail.range; fire(row2, "click", { target: { closest: () => null } }); const other = { port: m.topologyRouteDetail.port, range: m.topologyRouteDetail.range }; fire(row, "click", { target: { closest: () => ({}) } }); fire(close, "click"); return [first, ranged, kept, other, m.topologyRouteDetail, names().filter((x) => x === "loadRouteTokenHistory").length]; })()',
     '[{"proxyId":"skynet:proxy:23001","port":23001,"routeLabel":"hermes","clientIp":"10.0.0.7","clientName":"box","range":"all"},"24h","24h",{"port":29999,"range":"all"},null,4]',
     "детали маршрута: порт из прокси или из id, диапазон сохраняется при том же маршруте и сбрасывается при другом; клик по ручке не открывает; закрытие"),
    ("proxy_form_cancel_and_delete_names_bound_agents", 'globalThis.__fetchReply["/api/agent-proxies/route-delete"] = { ok: true, topology: { proxies: [], clients: [], routers: [], assignments: {} } };', 'await (async () => { const cancel = one("[data-topology-proxy-cancel]"); const del = one("[data-topology-proxy-delete]"); bind(); let opts = null; globalThis.__stubReturns["dialogs.appConfirm"] = async (_m, o) => { opts = o; return false; }; await fire(del, "click"); await settle(); const refused = [opts.detail, opts.danger, globalThis.__fetchCalls.length]; globalThis.__stubReturns["dialogs.appConfirm"] = async () => true; await fire(del, "click"); await settle(); const done = [JSON.parse(globalThis.__fetchCalls[0].body), st.topology.proxies.length, st.ui.topologyProxyFormOpen, F().toast.textContent.includes("23001")]; st.ui.topologyProxyFormOpen = true; fire(cancel, "click"); return [refused, done, st.ui.topologyProxyFormOpen]; })()',
     '[[":23001 hermes\\nstill used by: box-a/hermes",true,0],[{"port":23001},0,false,true],false]', "удаление прокси: confirm называет порт и привязанных агентов; отказ — ни запроса; согласие — POST порта, topology из ответа, форма закрыта, тост; отмена закрывает форму"),
    ("router_card_opens_kanban_unless_on_handle", '', '(() => { const [card] = many("[data-topology-router]", { dataset: { topologyRouter: "router:a" } }); const close = one("[data-topology-router-close]"); bind(); fire(card, "click", { target: { closest: (s) => (s.includes(".topology-handle") ? {} : null) } }); const onHandle = globalThis.__opened.length; fire(card, "keydown", { key: "Enter", preventDefault() {}, target: { closest: () => null } }); fire(close, "click"); return [onHandle, [...globalThis.__opened], st.ui.topologyRouterDetailId, st.ui.topologyCanvasRouterId]; })()',
     '[0,["/kanban"],"",""]', "карточка роутера открывает канбан в новой вкладке (не с ручки/подсказки); закрытие сбрасывает id"),
    ("set_default_reverts_radio_until_confirmed", '', 'await (async () => { const prev = one(\'[data-router-set-default="router:a"][data-output-id="cb:x"]\'); const [radio] = many("[data-router-set-default]", { dataset: { routerSetDefault: "router:a", outputId: "srv:2" }, checked: true, q: { "[data-router-out-row]": { querySelector: () => ({ textContent: " Second " }) } } }); bind(); fire(radio, "change"); const c = confirmState(); const reverted = [radio.checked, prev.checked]; st.ui.pendingConfirm(); await settle(); const saved = calls().find((x) => x[0] === "saveRouters")?.[1][0].rules; return [reverted, c.text.includes("Second"), c.danger, c.shown, saved.default, "dormantDefault" in saved]; })()',
     '[[false,true],true,false,true,"srv:2",false]', "радио «default»: откат до подтверждения (прежнее снова отмечено), не-красный confirm с подписью выхода; подтверждение ставит default и снимает dormantDefault"),
    ("hist_toggles_and_refresh", '', '(() => { const qo = V("canvas._cvQueueHistOpen"), qd = V("canvas._cvQueueHistData"), so = V("canvas._cvSchedHistOpen"), sd = V("canvas._cvSchedHistData"); const [qt] = many("[data-cv-q-hist-toggle]", { dataset: { cvQHistToggle: "n1" } }); const [qr] = many("[data-cv-q-hist-refresh]", { dataset: { cvQHistRefresh: "n1" } }); const [stg] = many("[data-cv-sched-hist-toggle]", { dataset: { cvSchedHistToggle: "n2" } }); bind(); let sp = 0; const ev = { stopPropagation: () => sp++ }; fire(qt, "click", ev); const a = [qo.n1, names().at(-1)]; qd.n1 = { x: 1 }; fire(qt, "click", ev); fire(qt, "click", ev); const b = [qo.n1, names().at(-1)]; fire(qr, "click", ev); const c = [qd.n1, names().at(-1)]; sd.n2 = { y: 1 }; fire(stg, "click", ev); return [a, b, c, so.n2, names().at(-1), sp]; })()',
     '[[true,"_fetchQueueHist"],[true,"renderTopology"],[null,"_fetchQueueHist"],true,"renderTopology",5]', "история очереди/расписания: открыть без данных — запрос; с данными — только перерисовка; обновить — данные сброшены и запрошены"),
    ("provider_toggle_fold_expose_rules", '', 'await (async () => { const [pt] = many("[data-router-prov-toggle]", { dataset: { routerProvToggle: "acct" } }); const [fold] = many("[data-router-group-fold]", { dataset: { routerGroupFold: "host:x" } }); const [cb] = many("[data-router-expose]", { dataset: { routerExpose: "cb:y" }, checked: true }); const [add] = many("[data-router-add-rule]", { dataset: { routerAddRule: "router:a" } }); one(\'[data-router-rule-source="router:a"]\', { value: "p1" }); one(\'[data-router-rule-output="router:a"]\', { value: "srv:2" }); const [del] = many("[data-router-del-rule]", { dataset: { routerDelRule: "router:a", ruleIndex: "0" } }); bind(); fire(pt, "click"); const exp1 = V("routers.topologyOutputsCloudExpanded").acct; fire(pt, "click"); fire(fold, "click", { stopPropagation() {} }); fire(cb, "change"); fire(add, "click"); await settle(); const added = calls().filter((c) => c[0] === "saveRouters").at(-1)[1][0].rules.bySource; fire(del, "click"); await settle(); const deleted = calls().filter((c) => c[0] === "saveRouters").at(-1)[1][0].rules.bySource; return [exp1, V("routers.topologyOutputsCloudExpanded").acct, V("routers.topologyOutputsFolded")["host:x"], calls().find((c) => c[0] === "setCloudModelExposed")?.slice(1), added, deleted.map((r) => r.proxyId)]; })()',
     '[true,false,true,["cb:y",true],[{"proxyId":"p2","output":"srv:2"},{"proxyId":"p1","clientId":"","output":"srv:2"}],["p2"]]',
     "раскрытие провайдера (у аккаунта с открытым блоком список по умолчанию свёрнут → первый клик раскрывает, второй сворачивает), сворачивание группы, галка экспорта модели, правило по источнику заменяет прежнее для того же прокси, удаление по индексу"),
    ("attach_detach_with_confirm", '', 'await (async () => { const [at, atc] = many("[data-router-attach]", { dataset: { routerAttach: "skynet:proxy:23002" } }, { dataset: { routerAttach: "skynet:proxy:23001", confirm: "1" } }); const [dt] = many("[data-router-detach]", { dataset: { routerDetach: "skynet:proxy:23001" } }); bind(); fire(at, "click"); await settle(); globalThis.__stubReturns["dialogs.appConfirm"] = async () => false; fire(atc, "click"); await settle(); const refused = calls().filter((c) => c[0] === "setTopologyProxyRoutePolicy").length; globalThis.__stubReturns["dialogs.appConfirm"] = async () => true; fire(atc, "keydown", { key: " ", preventDefault() {} }); await settle(); fire(dt, "click", { stopPropagation() {} }); await settle(); return [refused, calls().filter((c) => c[0] === "setTopologyProxyRoutePolicy").map((c) => c.slice(1))]; })()',
     '[1,[["skynet:proxy:23002",{"routerId":"router:a"}],["skynet:proxy:23001",{"routerId":"router:a"}],["skynet:proxy:23001",{"routerId":""}]]]', "вход прокси в роутер: без подтверждения для свободного, с подтверждением для чужого (отказ — ничего); выход — с подтверждением, routerId пустой"),
    ("open_canvas_failover_inputs_toggle", '', 'await (async () => { const oc = one("[data-router-open-canvas]", { dataset: { routerOpenCanvas: "router:a" } }); const cc = one("[data-topology-canvas-close]"); const fo = one("[data-router-failover-toggle]", { dataset: { routerFailoverToggle: "router:a" } }); const it = one("[data-router-inputs-toggle]"); bind(); fire(oc, "click", { currentTarget: oc }); const opened = [st.ui.topologyCanvasRouterId, names().slice(-5)]; fire(cc, "click"); fire(fo, "click", { currentTarget: fo }); await settle(); const chain = calls().filter((c) => c[0] === "saveRouters").at(-1)[1][0].rules.failover; st.topology.routers[0].rules.failover = ["cb:x"]; fire(fo, "click", { currentTarget: fo }); await settle(); const off = calls().filter((c) => c[0] === "saveRouters").at(-1)[1][0].rules.failover; fire(it, "click"); return [opened, st.ui.topologyCanvasRouterId, chain, off, st.ui.topologyRouterInputsExpanded]; })()',
     '[["router:a",["canvasLoadPositions","cvSetViewport","renderTopology","drawCanvasConnectors","bindCanvasInteractions"]],"",["cb:x","srv:1","srv:2"],[],true]', "открыть канбан-вставку: позиции → вьюпорт → рендер → коннекторы (+бинд); закрыть; failover: цепочка с default первым, повторно — выключение; входы раскрываются"),
    ("hover_links_and_search", '', '(() => { const outRow = one(\'[data-router-out-row="srv:1"]\'); const [link] = many("[data-router-link-out]", { dataset: { routerLinkOut: "srv:1" } }); globalThis.__qa[\'[data-router-link-out="srv:1"]\'] = [link]; const search = one("[data-router-input-search]", { value: "her" }); const [pa, pb] = many("[data-router-pill-wrap] [data-pill-name]", { dataset: { pillName: "hermes", pillPort: "23001" } }, { dataset: { pillName: "crane", pillPort: "23101" } }); bind(); fire(link, "mouseenter"); const on = [outRow.classList.has("link-hi"), link.classList.has("link-hi")]; fire(link, "mouseleave"); fire(search, "input"); const a = [pa.style.display, pb.style.display]; search.value = "231"; fire(search, "input"); return [on, outRow.classList.has("link-hi"), st.ui.topologyRouterInputSearch, a, [pa.style.display, pb.style.display]]; })()',
     '[[true,true],false,"231",["","none"],["none",""]]', "hover подсвечивает строку выхода и его ссылки; поиск по входам фильтрует пилюли по имени или порту"),
    ("schedule_editor_flow", '', 'await (async () => { const open = one("[data-router-open-schedule]", { dataset: { routerOpenSchedule: "router:a" } }); const [p1, p2] = many("[data-sched-paint]", { dataset: { schedPaint: "" } }, { dataset: { schedPaint: "srv:2" } }); const clear = one("[data-schedule-clear]"); const save = one("[data-schedule-save]"); bind(); fire(open, "click", { currentTarget: open }); const opened = [m.topologyScheduleRouterId, m.topologyScheduleGrid[0][9], m.topologySchedulePaintOutput]; fire(p2, "click"); const paint = [m.topologySchedulePaintOutput, p2.classList.has("active"), p1.classList.has("active")]; const cell = mkEl({ dataset: { day: "1", hour: "3" } }); globalThis.__qa["[data-sched-cell]"] = [cell]; const grid = one("[data-schedule-grid]"); bind(); fire(grid, "pointerdown", { target: { closest: () => cell }, preventDefault() {} }); const painted = [m.topologyScheduleGrid[1][3], cell.style.background, cell.classList.has("painted")]; const cell2 = mkEl({ dataset: { day: "1", hour: "4" } }); fire(grid, "pointerover", { target: { closest: () => cell2 } }); globalThis.__pointerUp(); fire(grid, "pointerover", { target: { closest: () => mkEl({ dataset: { day: "1", hour: "5" } }) } }); const drag = [m.topologyScheduleGrid[1][4], m.topologyScheduleGrid[1][5]]; fire(clear, "click"); const cleared = [m.topologyScheduleGrid.flat().filter(Boolean).length, cell.classList.has("painted")]; m.topologyScheduleGrid[0][0] = "srv:1"; fire(save, "click"); await settle(); const saved = calls().filter((c) => c[0] === "saveRouters").at(-1)[1][0].rules.schedule; return [opened, paint, painted, drag, cleared, [m.topologyScheduleRouterId, m.topologyScheduleGrid], saved.length]; })()',
     '[["router:a","srv:1","srv:1"],["srv:2",true,false],["srv:2","#c0ffee",true],["srv:2",""],[0,false],["",null],1]',
     "расписание: открытие берёт сетку из правил и кисть — первый выход; выбор кисти; pointerdown красит клетку, pointerover — пока не отпущено; очистка; сохранение через saveRouters и закрытие (pointerup документа биндится один раз на процесс)"),
    ("agent_client_proxy_buttons", '', 'await (async () => { const [rn] = many("[data-agent-rename]", { dataset: { agentRenameClient: "box-a", agentRename: "hermes", agentRenameName: "Hermes" } }); const [ad] = many("[data-client-agent-add]", { dataset: { clientAgentAdd: "box-a" } }); const [cr] = many("[data-client-rename]", { dataset: { clientRename: "box-a", clientName: "Box" } }); const [pe] = many("[data-topology-proxy-edit]", { dataset: { topologyProxyEdit: "skynet:proxy:23001" } }); const [pd] = many("[data-topology-proxy-delete]", { dataset: { topologyProxyDelete: "skynet:proxy:23001" } }); const [ce] = many("[data-topology-client-edit]", { dataset: { hostId: "box-a", currentName: "Box" } }); bind(); let sp = 0; fire(rn, "click", { stopPropagation: () => sp++ }); fire(ad, "click"); fire(cr, "click"); fire(pe, "click"); fire(pd, "click"); fire(ce, "click"); await settle(); return [sp, calls().map((c) => c.join(":"))]; })()',
     '[1,["renameTopologyAgent:box-a:hermes:Hermes","addTopologyAgent:box-a","editTopologyClientAlias:box-a:Box","editTopologyProxy:skynet:proxy:23001","deleteTopologyProxy:skynet:proxy:23001","editTopologyClientAlias:box-a:Box"]]', "кнопки агента/клиента/прокси зовут свои функции с данными из dataset"),
    ("route_handle_and_proxy_card_hover", '', '(() => { const [h] = many("[data-topology-route-handle]", { dataset: { hostId: "box-a", agentId: "hermes", routeRole: "primary" } }); const [card] = many("[data-topology-proxy]", { dataset: { proxyId: "skynet:proxy:23001" } }); const [pin] = many("[data-topology-proxy-input]", {}); bind(); fire(h, "mouseenter"); fire(h, "mouseleave"); fire(card, "mouseenter"); fire(pin, "dragover", { preventDefault() {}, dataTransfer: {} }); const over = pin.classList.has("drag-over"); fire(pin, "drop", { preventDefault() {} }); return [calls().map((c) => c[0] + (typeof c[1] === "string" ? ":" + c[1] : "")), over, pin.classList.has("drag-over")]; })()',
     '[["highlightTopologyCable:route-box-a-hermes-primary","scheduleClearTopologyCableHighlight","highlightTopologyCable:proxy-skynet:proxy:23001"],true,false]', "наведение на ручку маршрута и карточку прокси подсвечивает их кабель, уход — отложенное снятие; drag-over на входе прокси ставится и снимается"),
    ("at_point_helpers", '', '(() => { globalThis.__atPoint = { closest: (s) => ({ kind: s }) }; const a = [m.topologyLlamaAtPoint(1, 1)?.kind, m.topologyRouterInputAtPoint(1, 1)?.kind, m.topologyCloudAtPoint(1, 1)?.kind]; globalThis.__atPoint = null; return [a, m.topologyLlamaAtPoint(1, 1) ?? null]; })()',
     '[["[data-topology-llama-input]","[data-topology-router-input]","[data-topology-cloud-input]"],null]', "попадания: ближайший вход нужного вида под точкой; ничего под точкой — null"),
    ("clear_pointer_drag", '', '(() => { const src = mkEl(); src.classList.add("dragging"); globalThis.__stubSetters; m.topologyPointerDrag; const live = mkEl(); F().topologyCables = mkEl({ q: { ".topology-cable.live": live } }); const inp = mkEl(); inp.classList.add("drag-over"); globalThis.__qa["[data-topology-router-input]"] = [inp]; m.clearTopologyPointerDrag(); return [inp.classList.has("drag-over"), live.removed, names().includes("flushPendingTopologyRender"), m.topologyPointerDrag]; })()',
     '[false,true,true,null]', "снятие перетаскивания: drag-over убраны, живой кабель удалён, отложенный рендер сброшен"),
]


_fail = []


def check(cond, msg):
    print(("  ok  " if cond else " FAIL ") + msg)
    if not cond:
        _fail.append(msg)


def main():
    if len(PINS) < 28:
        print(f"js topology-dnd FAILED: всего {len(PINS)} пинов — снимок урезан")
        return 1
    node = find_node()
    if node is None:
        print("js topology-dnd: SKIPPED — node не найден: " + ", ".join(node_search_paths()))
        return 0

    def blocks(pins, sink):
        return [f"try {{ reset(); {setup}\n  {sink}[{json.dumps(pid)}] = {expr}; }} "
                f"catch (e) {{ {sink}[{json.dumps(pid)}] = {{ __threw: String(e && e.message || e) }}; }}"
                for pid, setup, expr, _exp, _msg in pins]

    # Пины не опираются друг на друга: тот же набор в обратном порядке обязан
    # дать те же значения.
    probe = (PREAMBLE + "\n".join(blocks(PINS, "out")) + "\nconst rev = {};\n"
             + "\n".join(blocks(list(reversed(PINS)), "rev"))
             + "\nconsole.log(JSON.stringify({ out, rev })); process.exit(0);\n")
    harness = ROOT / "scripts" / "_js_harness.mjs"
    path = ROOT / "scripts" / ".probe_js_topology_dnd.tmp.mjs"
    path.write_text(probe)
    try:
        env = {**os.environ, "JS_ROOT": str(ROOT / "static" / "js"), "JS_STUBS": STUBS,
               "LANG": "en_US.UTF-8", "LC_ALL": "en_US.UTF-8", "TZ": "UTC"}
        run = subprocess.run(
            [node, "--import",
             f"data:text/javascript,import {{ register }} from 'node:module'; register('{harness.as_uri()}');",
             str(path)], capture_output=True, text=True, env=env, cwd=ROOT, timeout=120)
    finally:
        path.unlink(missing_ok=True)
    if run.returncode != 0:
        print(run.stdout); print(run.stderr)
        print(f"js topology-dnd FAILED: node вышел с кодом {run.returncode}")
        return 1
    both = json.loads(run.stdout.strip().splitlines()[-1])
    got, rev = both["out"], both["rev"]
    print("биндер доски: модалы, ползунки очереди, расписание, роутер, перетаскивание:")
    for pid, _s, _e, expected, msg in PINS:
        want, have = json.loads(expected), got.get(pid, "\0missing")
        check(have == want, msg if have == want else
              f"{msg}\n        ожидалось {json.dumps(want, ensure_ascii=False)[:200]}"
              f"\n        получено  {json.dumps(have, ensure_ascii=False)[:200]}")
        if have != rev.get(pid, "\0missing"):
            _fail.append(f"пин {pid} зависит от порядка")
    print(f"порядок: {len(PINS)} пинов дают те же значения в обратном порядке" if not _fail else "")
    print()
    if _fail:
        print(f"FAILED ({len(_fail)}):")
        for m in _fail:
            print("  - " + m.splitlines()[0])
        return 1
    print(f"js topology-dnd OK: настоящий модуль в node, {len(PINS)} пинов биндера значениями")
    return 0


if __name__ == "__main__":
    sys.exit(main())
