#!/usr/bin/env python3
"""Снимок static/js/llama-edit.js — редактор ячейки: что она запустит.

18 починок в истории модуля, четыре из них — в DOM-свободном
_buildCommandExecPreview: превью показывает команду, которую Apply запишет
(2062ee8, ed5d4d3), знает moonshine и seamless (395664a, 6858617), говорит,
что реально запустится (f28e409). Пинятся ЗНАЧЕНИЯ: восемь веток раннеров
превью с умолчаниями и правилами путей, разбор ENV (запятая и перевод строки,
комментарии, невалидные ключи), effectiveRunnerId по старшинству, сборка
команды vLLM, artifactKind по метаданным модели, таблица compute capability,
устройство из ENV/COMMAND и его запись обратно, реестр раннеров, метки бэкапов.

Форма — словарь globalThis.__fields (F({...})); поля с префиксом "te-"/"tr-".
Пины лежат данными в PINS; каждый — в своём try/catch после reset(). Время
заморожено. Модуль грузится НАСТОЯЩИЙ (_js_harness.mjs).

Запуск: python3 scripts/test_js_llama_edit.py
"""

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _node import find_node, node_search_paths  # noqa: E402

STUBS = ("topology-render,topology-modals,cables,routers,cloud,history,dialogs,favorites,config-locator,system-panels,"
         "onboarding,topology-dnd,canvas,usage-stats,dialog-llamas,models-page,system-page,onboarding-tours")

PREAMBLE = r"""
import "./_js_globals.mjs";
import { pathToFileURL } from "node:url";
const st = await import(pathToFileURL(process.env.JS_ROOT + "/state.js").href);
st.setState({ config: {}, runners: [], artifacts: [], models: [], paths: {} });
st.setTopology({ proxies: [], clients: [], routers: [], assignments: {}, nodes: [] });
Date.now = () => 1_700_000_100_000;
globalThis.__stubReturns = { "dialogs.appConfirm": async () => true };
const le = await import(pathToFileURL(process.env.JS_ROOT + "/llama-edit.js").href);
const rc = await import(pathToFileURL(process.env.JS_ROOT + "/remote-cells.js").href);
const cst = await import(pathToFileURL(process.env.JS_ROOT + "/constants.js").href);
const ui = st.ui;
const norm = (s) => String(s).replace(/\s+/g, " ").trim();
const toastEl = () => ({ textContent: "", classList: { add() {}, remove() {} } });
const F = (fields) => { globalThis.__fields = { toast: toastEl(), ...fields }; };
const reset = () => { st.setState({ config: {}, runners: [], artifacts: [], models: [], paths: {} });
  st.setTopology({ proxies: [], clients: [], routers: [], assignments: {}, nodes: [] });
  F({}); globalThis.__fetchCalls.length = 0; globalThis.__fetchReply = {}; globalThis.__stubReturns = { "dialogs.appConfirm": async () => true };
  // Порт открытой ячейки — module-level `export let` внутри llama-edit; извне
  // его сбрасывает только openTopologyLlamaEdit, и присваивание стоит ПЕРВОЙ
  // строкой функции, до любого обращения к DOM. Поэтому try/catch: словарный
  // DOM обрывает вызов дальше, но порт уже очищен.
  try { le.openTopologyLlamaEdit("edit", ""); } catch { /* см. выше */ }
  for (const c of [rc._stoppingHosts, rc._stoppingCells, rc._deletingSlots, rc._newReservedCells, rc._pendingRemoteStarts, rc._pendingCellActions, rc._reservingCells]) c.clear(); };
const calls = () => globalThis.__fetchCalls.map((c) => ({ path: c.path, method: c.method, body: c.body }));
const toastText = () => globalThis.__fields.toast.textContent;
const out = {};
"""

# (id, setup, expression, expected JSON string, message). Filled from the pin
# workflow; see docs/oop-rewrite.md, phase 7, snapshot 6.
PINS = [
    # ── exec_preview ──
    ('er_explicit_trimmed',
     'F({ "te-RUNNER": { value: "  whisper  " } });',
     'le.effectiveRunnerId("te-")',
     '"whisper"',
     'positive: явный RUNNER берётся с обрезкой пробелов'),
    ('er_explicit_beats_kind',
     'F({ "te-RUNNER": { value: "vllm" }, "te-CELL_KIND": { value: "command" } });',
     'le.effectiveRunnerId("te-")',
     '"vllm"',
     'positive: явный RUNNER важнее CELL_KIND=command'),
    ('er_kind_command_custom',
     'F({ "te-CELL_KIND": { value: "command" } });',
     'le.effectiveRunnerId("te-")',
     '"custom"',
     'positive: без RUNNER: CELL_KIND=command → custom'),
    ('er_kind_command_runner_ws',
     'F({ "te-RUNNER": { value: "   " }, "te-CELL_KIND": { value: "command" } });',
     'le.effectiveRunnerId("te-")',
     '"custom"',
     'boundary: RUNNER из одних пробелов = пустой → решает CELL_KIND'),
    ('er_kind_other_llama',
     'F({ "te-CELL_KIND": { value: "llama" } });',
     'le.effectiveRunnerId("te-")',
     '"llama-server"',
     'negative: CELL_KIND≠command → llama-server'),
    ('er_no_fields_llama',
     'F({});',
     'le.effectiveRunnerId("te-")',
     '"llama-server"',
     'negative: полей нет вовсе → llama-server'),
    ('er_tr_prefix',
     'F({ "tr-RUNNER": { value: "moonshine" } });',
     'le.effectiveRunnerId("tr-")',
     '"moonshine"',
     'positive: префикс tr- читает поле tr-RUNNER'),
    ('er_prefix_isolation',
     'F({ "tr-RUNNER": { value: "moonshine" }, "tr-CELL_KIND": { value: "command" } });',
     'le.effectiveRunnerId("te-")',
     '"llama-server"',
     'negative: поля tr- не протекают в te-'),
    ('vllm_no_fields',
     'F({});',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve … --host 0.0.0.0 --port \\"$PORT\\""',
     'negative: без модели: многоточие вместо модели, без served-model-name'),
    ('vllm_served_from_path',
     'F({ "te-VLLM_MODEL": { value: " Qwen/Qwen2.5-7B-Instruct " } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve Qwen/Qwen2.5-7B-Instruct --host 0.0.0.0 --port \\"$PORT\\" --served-model-name qwen2.5-7b-instruct"',
     'positive: served-model-name = последний сегмент пути в нижнем регистре'),
    ('vllm_served_no_slash',
     'F({ "te-VLLM_MODEL": { value: "GPT-OSS" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve GPT-OSS --host 0.0.0.0 --port \\"$PORT\\" --served-model-name gpt-oss"',
     'boundary: модель без слэша: served-model-name = вся строка в нижнем регистре'),
    ('vllm_alias_wins',
     'F({ "te-VLLM_MODEL": { value: "Qwen/Qwen2.5-7B" }, "te-ALIAS": { value: " MyAlias " } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve Qwen/Qwen2.5-7B --host 0.0.0.0 --port \\"$PORT\\" --served-model-name MyAlias"',
     'positive: ALIAS важнее сегмента пути и регистр не меняется'),
    ('vllm_alias_ws_ignored',
     'F({ "te-VLLM_MODEL": { value: "Qwen/Qwen2.5-7B" }, "te-ALIAS": { value: "   " } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve Qwen/Qwen2.5-7B --host 0.0.0.0 --port \\"$PORT\\" --served-model-name qwen2.5-7b"',
     'negative: ALIAS из пробелов = пустой → имя из пути'),
    ('vllm_alias_without_model',
     'F({ "te-ALIAS": { value: "solo" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve … --host 0.0.0.0 --port \\"$PORT\\" --served-model-name solo"',
     'boundary: ALIAS без модели: многоточие + served-model-name'),
    ('vllm_maxlen_gpu_set',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-MAX_MODEL_LEN": { value: " 8192 " }, "te-GPU_MEMORY_UTILIZATION": { value: "0.9" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --max-model-len 8192 --gpu-memory-utilization 0.9"',
     'positive: MAX_MODEL_LEN и GPU_MEMORY_UTILIZATION попадают в команду обрезанными'),
    ('vllm_maxlen_gpu_ws_omitted',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-MAX_MODEL_LEN": { value: "  " }, "te-GPU_MEMORY_UTILIZATION": { value: "" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m"',
     'negative: пустые/пробельные MAX_MODEL_LEN и GPU_MEMORY_UTILIZATION опускаются'),
    ('vllm_quant_set_lowercased',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-QUANTIZATION": { value: "Awq" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --quantization awq"',
     'positive: QUANTIZATION печатается в нижнем регистре'),
    ('vllm_quant_auto_omitted',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-QUANTIZATION": { value: "AUTO" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m"',
     'negative: QUANTIZATION=AUTO (любой регистр) опускается'),
    ('vllm_dtype_set_lowercased',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-DTYPE": { value: "BF16" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --dtype bf16"',
     'positive: DTYPE печатается в нижнем регистре'),
    ('vllm_dtype_auto_omitted',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-DTYPE": { value: "Auto" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m"',
     'negative: DTYPE=Auto (любой регистр) опускается'),
    ('vllm_tp_variants',
     'F({});',
     '["", "0", "1", "2", " 4 "].map((v) => { F({ "te-VLLM_MODEL": { value: "m" }, "te-TENSOR_PARALLEL": { value: v } }); return le.buildVllmCommandPreview("te-"); })',
     '["$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m","$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m","$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m","$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --tensor-parallel-size 2","$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --tensor-parallel-size 4"]',
     'boundary: TENSOR_PARALLEL: пусто/0/1 опускаются, 2 и 4 печатаются'),
    ('vllm_tr_prefix',
     'F({ "tr-VLLM_MODEL": { value: "org/Big-Model" }, "tr-DTYPE": { value: "half" } });',
     'le.buildVllmCommandPreview("tr-")',
     '"$HOME/vllm-venv/bin/vllm serve org/Big-Model --host 0.0.0.0 --port \\"$PORT\\" --served-model-name big-model --dtype half"',
     'positive: префикс tr- читает поля tr-VLLM_MODEL/tr-DTYPE'),
    ('vllm_prefix_isolation',
     'F({ "tr-VLLM_MODEL": { value: "org/Big-Model" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve … --host 0.0.0.0 --port \\"$PORT\\""',
     'negative: tr-VLLM_MODEL не виден превью te-'),
    ('exec_port_fallback_literal',
     'F({ "te-RUNNER": { value: "vllm" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=PORT\\n# first start on a host provisions ~/vllm-venv (several minutes)\\nexec $HOME/vllm-venv/bin/vllm serve … --host 0.0.0.0 --port \\"$PORT\\""',
     'as-is: нет поля PORT и порта ячейки → буквальное «export PORT=PORT» (некрасиво, но так)'),
    ('exec_port_field_empty_fallback',
     'F({ "te-RUNNER": { value: "vllm" }, "te-PORT": { value: "" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[0]',
     '"export PORT=PORT"',
     'boundary: поле PORT есть, но пустое → тот же буквальный PORT'),
    ('exec_port_field_used',
     'F({ "te-RUNNER": { value: "vllm" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[0]',
     '"export PORT=22005"',
     'positive: поле PORT задано → export PORT=22005'),
    ('exec_port_tr_fallback_literal',
     'F({ "tr-RUNNER": { value: "vllm" } });',
     'le._buildCommandExecPreview("tr-").split("\\n")[0]',
     '"export PORT=PORT"',
     'as-is: tr- без порта: тот же буквальный PORT'),
    ('exec_port_from_open_cell',
     'try { le.openTopologyLlamaEdit("edit", 22007); } catch (e) {} F({ "te-RUNNER": { value: "vllm" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[0]',
     '"export PORT=22007"',
     'positive: без поля PORT берётся порт открытой ячейки (_teCellPort) — openTopologyLlamaEdit бросает после его установки, поэтому try/catch'),
    ('exec_port_field_beats_open_cell',
     'try { le.openTopologyLlamaEdit("edit", 22007); } catch (e) {} F({ "te-RUNNER": { value: "vllm" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[0]',
     '"export PORT=22005"',
     'positive: поле PORT важнее порта открытой ячейки'),
    ('exec_port_from_open_cell_cleared',
     'try { le.openTopologyLlamaEdit("edit", ""); } catch (e) {} F({ "te-RUNNER": { value: "vllm" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[0]',
     '"export PORT=PORT"',
     'negative: после открытия без порта _teCellPort сброшен → буквальный PORT (и чистит состояние за предыдущими пинами)'),
    ('exec_vllm_te',
     'F({ "te-RUNNER": { value: "vllm" }, "te-PORT": { value: "22005" }, "te-VLLM_MODEL": { value: "Qwen/Qwen2.5-7B" }, "te-MAX_MODEL_LEN": { value: "4096" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# first start on a host provisions ~/vllm-venv (several minutes)\\nexec $HOME/vllm-venv/bin/vllm serve Qwen/Qwen2.5-7B --host 0.0.0.0 --port \\"$PORT\\" --served-model-name qwen2.5-7b --max-model-len 4096"',
     'positive: ветка vllm: export, комментарий о venv, exec с командой vllm'),
    ('exec_vllm_tr',
     'F({ "tr-RUNNER": { value: "vllm" }, "tr-PORT": { value: "22011" }, "tr-VLLM_MODEL": { value: "org/M" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=22011\\n# first start on a host provisions ~/vllm-venv (several minutes)\\nexec $HOME/vllm-venv/bin/vllm serve org/M --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m"',
     'positive: ветка vllm для префикса tr-'),
    ('exec_whisper_default_size',
     'F({ "te-RUNNER": { value: "whisper" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# model downloads on first start into <models root>/whisper\\nexec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/whisper\\" bash $HOME/run_whisper.sh \\"$PORT\\" large-v3"',
     'positive: whisper без размера: large-v3 и строка HUGGINGFACE_HUB_CACHE'),
    ('exec_whisper_size_trimmed',
     'F({ "te-RUNNER": { value: "whisper" }, "te-PORT": { value: "22005" }, "te-WHISPER_MODEL": { value: " small " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# model downloads on first start into <models root>/whisper\\nexec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/whisper\\" bash $HOME/run_whisper.sh \\"$PORT\\" small"',
     'positive: whisper: WHISPER_MODEL обрезается и подставляется'),
    ('exec_whisper_size_ws_default',
     'F({ "te-RUNNER": { value: "whisper" }, "te-PORT": { value: "22005" }, "te-WHISPER_MODEL": { value: "   " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/whisper\\" bash $HOME/run_whisper.sh \\"$PORT\\" large-v3"',
     'negative: whisper: пробельный WHISPER_MODEL → large-v3'),
    ('exec_whisper_tr',
     'F({ "tr-RUNNER": { value: "whisper" }, "tr-PORT": { value: "22011" }, "tr-WHISPER_MODEL": { value: "medium" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=22011\\n# model downloads on first start into <models root>/whisper\\nexec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/whisper\\" bash $HOME/run_whisper.sh \\"$PORT\\" medium"',
     'positive: ветка whisper для префикса tr-'),
    ('exec_transcribe_relative',
     'F({ "te-RUNNER": { value: "transcribe" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: " stt/gigaam-v2.gguf " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# the engine and its venv come from scripts/install-transcribe.sh\\nexec bash $HOME/run_transcribe.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/stt/gigaam-v2.gguf"',
     'defect-history: f28e409: transcribe с относительным MODEL_FILE → "${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}"/<mf>'),
    ('exec_transcribe_absolute',
     'F({ "te-RUNNER": { value: "transcribe" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "/opt/models/x.gguf" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_transcribe.sh \\"$PORT\\" \\"/opt/models/x.gguf\\""',
     'defect-history: f28e409: абсолютный MODEL_FILE цитируется как есть без корня моделей'),
    ('exec_transcribe_dollar',
     'F({ "te-RUNNER": { value: "transcribe" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "$HOME/models/x.gguf" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_transcribe.sh \\"$PORT\\" \\"$HOME/models/x.gguf\\""',
     'defect-history: f28e409: MODEL_FILE с $ в начале цитируется как есть'),
    ('exec_transcribe_empty',
     'F({ "te-RUNNER": { value: "transcribe" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "  " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_transcribe.sh \\"$PORT\\" \\"…\\""',
     'negative: transcribe без MODEL_FILE → многоточие в кавычках'),
    ('exec_transcribe_tr',
     'F({ "tr-RUNNER": { value: "transcribe" }, "tr-PORT": { value: "22011" }, "tr-MODEL_FILE": { value: "a.gguf" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=22011\\n# the engine and its venv come from scripts/install-transcribe.sh\\nexec bash $HOME/run_transcribe.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/a.gguf"',
     'positive: ветка transcribe для префикса tr-'),
    ('exec_moonshine_default_en',
     'F({ "te-RUNNER": { value: "moonshine" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# first start provisions ~/moonshine-venv and fetches the model\\nexec bash $HOME/run_moonshine.sh \\"$PORT\\" en"',
     'defect-history: 395664a: moonshine получил свою ветку (раньше показывал чужую llama-строку); без MOONSHINE_MODEL → en'),
    ('exec_moonshine_blank_en',
     'F({ "te-RUNNER": { value: "moonshine" }, "te-PORT": { value: "22005" }, "te-MOONSHINE_MODEL": { value: "   " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_moonshine.sh \\"$PORT\\" en"',
     'defect-history: 395664a: пробельный MOONSHINE_MODEL → en'),
    ('exec_moonshine_lang_trimmed',
     'F({ "te-RUNNER": { value: "moonshine" }, "te-PORT": { value: "22005" }, "te-MOONSHINE_MODEL": { value: " ru " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_moonshine.sh \\"$PORT\\" ru"',
     'positive: moonshine: язык из поля с обрезкой'),
    ('exec_moonshine_tr',
     'F({ "tr-RUNNER": { value: "moonshine" }, "tr-PORT": { value: "22025" }, "tr-MOONSHINE_MODEL": { value: "es" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=22025\\n# first start provisions ~/moonshine-venv and fetches the model\\nexec bash $HOME/run_moonshine.sh \\"$PORT\\" es"',
     'positive: ветка moonshine для префикса tr-'),
    ('exec_translate_defaults',
     'F({ "te-RUNNER": { value: "translate" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# model downloads on first start into <models root>/translate\\nexec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-distilled-600M eng_Latn rus_Cyrl"',
     'positive: translate по умолчанию: nllb-200-distilled-600M, eng_Latn → rus_Cyrl'),
    ('exec_translate_all_set',
     'F({ "te-RUNNER": { value: "translate" }, "te-PORT": { value: "22005" }, "te-TRANSLATE_MODEL": { value: " facebook/nllb-200-1.3B " }, "te-TRANSLATE_SRC_LANG": { value: " deu_Latn " }, "te-TRANSLATE_TGT_LANG": { value: " fra_Latn " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-1.3B deu_Latn fra_Latn"',
     'positive: translate: модель и оба языка из полей, обрезанные'),
    ('exec_translate_model_ws_default',
     'F({ "te-RUNNER": { value: "translate" }, "te-PORT": { value: "22005" }, "te-TRANSLATE_MODEL": { value: "   " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-distilled-600M eng_Latn rus_Cyrl"',
     'negative: translate: пробельная модель → дефолт (trim до ||)'),
    ('exec_translate_langs_ws_empty',
     'F({ "te-RUNNER": { value: "translate" }, "te-PORT": { value: "22005" }, "te-TRANSLATE_SRC_LANG": { value: "  " }, "te-TRANSLATE_TGT_LANG": { value: "  " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-distilled-600M  "',
     'as-is: НЕКРАСИВО: пробельные языки НЕ падают в дефолт (|| до trim) — команда заканчивается двумя пробелами без языков'),
    ('exec_translate_tr',
     'F({ "tr-RUNNER": { value: "translate" }, "tr-PORT": { value: "22011" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=22011\\n# model downloads on first start into <models root>/translate\\nexec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-distilled-600M eng_Latn rus_Cyrl"',
     'positive: ветка translate для префикса tr-'),
    ('exec_seamless_relative_default_tgt',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "seamless/m4t.pt" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# first start provisions ~/seamless-venv (torch + transformers)\\nexec bash $HOME/run_seamless.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/seamless/m4t.pt rus"',
     'defect-history: 6858617/395664a: ветка seamless есть; относительный MODEL_FILE под корнем моделей, SEAMLESS_TGT_LANG по умолчанию rus'),
    ('exec_seamless_absolute',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "/opt/m4t" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_seamless.sh \\"$PORT\\" \\"/opt/m4t\\" rus"',
     'defect-history: 395664a: seamless с абсолютным MODEL_FILE цитирует его как есть'),
    ('exec_seamless_dollar',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "$MODELS/m4t" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_seamless.sh \\"$PORT\\" \\"$MODELS/m4t\\" rus"',
     'defect-history: 395664a: seamless с $-путём цитирует его как есть'),
    ('exec_seamless_empty',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_seamless.sh \\"$PORT\\" \\"…\\" rus"',
     'negative: seamless без MODEL_FILE → многоточие в кавычках, язык rus'),
    ('exec_seamless_tgt_trimmed',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "m" }, "te-SEAMLESS_TGT_LANG": { value: " eng " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_seamless.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/m eng"',
     'defect-history: 395664a: seamless сохраняет свой язык — SEAMLESS_TGT_LANG обрезается и подставляется'),
    ('exec_seamless_tgt_ws_default',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "m" }, "te-SEAMLESS_TGT_LANG": { value: "   " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_seamless.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/m rus"',
     'negative: seamless: пробельный SEAMLESS_TGT_LANG → rus (в отличие от translate тут trim после ||)'),
    ('exec_seamless_tr',
     'F({ "tr-RUNNER": { value: "seamless" }, "tr-PORT": { value: "22011" }, "tr-MODEL_FILE": { value: "m4t" }, "tr-SEAMLESS_TGT_LANG": { value: "deu" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=22011\\n# first start provisions ~/seamless-venv (torch + transformers)\\nexec bash $HOME/run_seamless.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/m4t deu"',
     'positive: ветка seamless для префикса tr-'),
    ('exec_custom_full',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: " python serve.py --port $PORT " }, "te-ENV": { value: "A=1\\nB=two" }, "te-WORKDIR": { value: " /srv/app " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1\\"\\nexport B=\\"two\\"\\ncd /srv/app\\nexec python serve.py --port $PORT"',
     'defect-history: 2062ee8/ed5d4d3: custom показывает то, что запишет Apply — export PORT, export ENV, cd WORKDIR, exec COMMAND'),
    ('exec_custom_runner_explicit',
     'F({ "te-RUNNER": { value: "custom" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "python x.py" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec python x.py"',
     'positive: RUNNER=custom явно → та же custom-ветка'),
    ('exec_custom_exec_stripped_once',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "exec exec python x.py" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[1]',
     '"exec exec python x.py"',
     'defect-history: ed5d4d3: ведущий «exec » снимается ровно один раз (двойной exec остаётся одним лишним)'),
    ('exec_custom_exec_leading_ws',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "   exec    python x.py" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[1]',
     '"exec python x.py"',
     'positive: COMMAND обрезается, «exec» с любым числом пробелов после снимается'),
    ('exec_custom_exec_prefix_word_kept',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "executor x.py" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[1]',
     '"exec executor x.py"',
     'negative: слово «executor» не считается за exec — остаётся целиком'),
    ('exec_custom_only_exec_word',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "exec" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[1]',
     '"exec exec"',
     'as-is: НЕКРАСИВО: COMMAND=«exec» без пробела после не снимается (регексп требует \\s+) → «exec exec»'),
    ('exec_custom_empty_command',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "   " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec …"',
     'defect-history: ed5d4d3: пустой COMMAND → «exec …»'),
    ('exec_custom_env_comma_split',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-ENV": { value: "A=1, B=2,C=3" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1\\"\\nexport B=\\"2\\"\\nexport C=\\"3\\"\\nexec …"',
     'defect-history: ed5d4d3: ENV делится и по запятой, элементы обрезаются'),
    ('exec_custom_env_comment_skipped',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-ENV": { value: "# comment=1\\nA=1" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1\\"\\nexec …"',
     'defect-history: ed5d4d3: строка-комментарий ENV (даже с «=») пропускается'),
    ('exec_custom_env_no_eq_skipped',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-ENV": { value: "FOO\\n\\n  \\nA=1" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1\\"\\nexec …"',
     'defect-history: ed5d4d3: строки без «=» и пустые строки ENV пропускаются'),
    ('exec_custom_env_bad_keys_skipped',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-ENV": { value: "9X=1\\nB C=2\\nA-B=3\\n=4\\nA=1" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1\\"\\nexec …"',
     'defect-history: ed5d4d3: невалидные ключи ENV (9X, «B C», A-B, пустой) пропускаются'),
    ('exec_custom_env_key_trailing_space_kept',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-ENV": { value: "B =2" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport B=\\"2\\"\\nexec …"',
     'as-is: ключ «B » с пробелом перед «=» НЕ пропускается — обрезается до B (вопреки ожиданию из истории дефекта)'),
    ('exec_custom_env_value_trim_quote',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-ENV": { value: "A=  hello world  \\nB=x=y=z\\nC=\\"quoted\\"\\nD=" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"hello world\\"\\nexport B=\\"x=y=z\\"\\nexport C=\\"\\"quoted\\"\\"\\nexport D=\\"\\"\\nexec …"',
     'as-is: значения ENV обрезаются и берутся в кавычки; НЕКРАСИВО: уже закавыченное значение даёт ""quoted"" без экранирования; split по первому «=»; пустое значение → ""'),
    ('exec_custom_workdir_absent',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-WORKDIR": { value: "  " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec x"',
     'negative: пробельный WORKDIR → строки cd нет'),
    ('exec_default_llama_server_falls_to_custom',
     'F({ "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec …"',
     'as-is: НЕКРАСИВО: runner llama-server не имеет ветки — проваливается в custom и печатает «exec …» (вызывающий код не зовёт превью для llama-server)'),
    ('exec_unknown_runner_falls_to_custom',
     'F({ "te-RUNNER": { value: "sherpa" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "run.sh" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec run.sh"',
     'as-is: НЕКРАСИВО: неизвестный runner молча трактуется как custom'),
    ('exec_custom_tr',
     'F({ "tr-CELL_KIND": { value: "command" }, "tr-PORT": { value: "22011" }, "tr-COMMAND": { value: "exec bash go.sh" }, "tr-ENV": { value: "X=1" }, "tr-WORKDIR": { value: "/w" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=22011\\nexport X=\\"1\\"\\ncd /w\\nexec bash go.sh"',
     'positive: custom-ветка для префикса tr-: exec снят и добавлен один раз'),
    ('exec_custom_prefix_isolation',
     'F({ "tr-CELL_KIND": { value: "command" }, "tr-PORT": { value: "22011" }, "tr-COMMAND": { value: "bash go.sh" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec …"',
     'negative: поля tr-COMMAND/tr-PORT не видны превью te-'),
    ('exec_port_tr_from_open_cell',
     'try { rc.openLlamaRemoteEdit("h1", "gpu0", [], 22031); } catch (e) {} F({ "tr-RUNNER": { value: "vllm" } });',
     '(() => { const r = le._buildCommandExecPreview("tr-").split("\\n")[0]; try { rc.openLlamaRemoteEdit("h1", "gpu0", [], ""); } catch (e) {} return r; })()',
     '"export PORT=22031"',
     'positive: tr-: без поля PORT порт берётся из открытой удалённой ячейки (_trCellPort=22031); выражение само сбрасывает порт после чтения'),
    ('exec_port_tr_field_beats_open_cell',
     'try { rc.openLlamaRemoteEdit("h1", "gpu0", [], 22031); } catch (e) {} F({ "tr-RUNNER": { value: "vllm" }, "tr-PORT": { value: "22077" } });',
     '(() => { const r = le._buildCommandExecPreview("tr-").split("\\n")[0]; try { rc.openLlamaRemoteEdit("h1", "gpu0", [], ""); } catch (e) {} return r; })()',
     '"export PORT=22077"',
     'negative: tr-: заполненное поле PORT побеждает порт открытой ячейки (22077, не 22031)'),
    ('exec_port_tr_from_open_cell_cleared',
     'try { rc.openLlamaRemoteEdit("h1", "gpu0", [], 22031); } catch (e) {} try { rc.openLlamaRemoteEdit("h1", "gpu0", [], ""); } catch (e) {} F({ "tr-RUNNER": { value: "vllm" } });',
     'le._buildCommandExecPreview("tr-").split("\\n")[0]',
     '"export PORT=PORT"',
     'negative: tr-: повторное открытие с пустым портом стирает _trCellPort — снова литерал PORT'),
    ('exec_port_tr_open_cell_not_te',
     'try { rc.openLlamaRemoteEdit("h1", "gpu0", [], 22031); } catch (e) {} F({ "te-RUNNER": { value: "vllm" } });',
     '(() => { const r = le._buildCommandExecPreview("te-").split("\\n")[0]; try { rc.openLlamaRemoteEdit("h1", "gpu0", [], ""); } catch (e) {} return r; })()',
     '"export PORT=PORT"',
     'negative: порт открытой удалённой ячейки (tr) не просачивается в te-превью — там литерал PORT'),
    ('exec_port_te_open_cell_not_tr',
     'try { le.openTopologyLlamaEdit("edit", 22040); } catch (e) {} F({ "tr-RUNNER": { value: "vllm" } });',
     '(() => { const r = le._buildCommandExecPreview("tr-").split("\\n")[0]; try { le.openTopologyLlamaEdit("edit", ""); } catch (e) {} return r; })()',
     '"export PORT=PORT"',
     'negative: порт открытой контроллерной ячейки (te) не просачивается в tr-превью — там литерал PORT'),
    ('exec_port_field_untrimmed',
     'F({ "te-RUNNER": { value: "vllm" }, "te-PORT": { value: " 22005 " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[0]',
     '"export PORT= 22005 "',
     'as-is: как есть: поле PORT НЕ тримится — пробелы попадают в export PORT= 22005 (единственное поле без trim)'),
    ('exec_port_field_zero',
     'F({ "te-RUNNER": { value: "vllm" }, "te-PORT": { value: "0" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[0]',
     '"export PORT=0"',
     'boundary: граница: PORT="0" — истинная строка, литерального PORT-фолбэка нет'),
    ('er_kind_command_ws_llama',
     'F({ "te-CELL_KIND": { value: " command " } });',
     'le.effectiveRunnerId("te-")',
     '"llama-server"',
     'as-is: как есть: CELL_KIND сравнивается без trim — " command " даёт llama-server, а не custom'),
    ('er_kind_command_case_llama',
     'F({ "te-CELL_KIND": { value: "Command" } });',
     'le.effectiveRunnerId("te-")',
     '"llama-server"',
     'as-is: как есть: CELL_KIND регистрозависим — "Command" даёт llama-server'),
    ('er_kind_command_exact_custom',
     'F({ "te-CELL_KIND": { value: "command" } });',
     'le.effectiveRunnerId("te-")',
     '"custom"',
     'positive: точное "command" в CELL_KIND даёт custom (контроль к двум as-is выше)'),
    ('vllm_model_trailing_slash_no_served',
     'F({ "te-VLLM_MODEL": { value: "Qwen/" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve Qwen/ --host 0.0.0.0 --port \\"$PORT\\""',
     'as-is: как есть: модель со слэшем на конце теряет --served-model-name целиком (split(\'/\').pop() = "")'),
    ('vllm_model_trailing_slash_alias_rescues',
     'F({ "te-VLLM_MODEL": { value: "Qwen/" }, "te-ALIAS": { value: "q" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve Qwen/ --host 0.0.0.0 --port \\"$PORT\\" --served-model-name q"',
     'negative: ALIAS возвращает --served-model-name даже при модели со слэшем на конце'),
    ('vllm_tp_string_compare_01',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-TENSOR_PARALLEL": { value: "01" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --tensor-parallel-size 01"',
     'as-is: как есть: TENSOR_PARALLEL сравнивается как строка — "01" не равно "1" и печатается'),
    ('vllm_tp_ws_one_omitted',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-TENSOR_PARALLEL": { value: " 1 " } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m"',
     'boundary: граница: " 1 " тримится до "1" и --tensor-parallel-size опускается'),
    ('vllm_tp_ws_two_kept',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-TENSOR_PARALLEL": { value: " 2 " } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --tensor-parallel-size 2"',
     'positive: " 2 " тримится и печатается как --tensor-parallel-size 2'),
    ('vllm_maxlen_zero_kept',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-MAX_MODEL_LEN": { value: "0" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --max-model-len 0"',
     'boundary: граница: MAX_MODEL_LEN="0" — истинная строка, флаг печатается с нулём'),
    ('vllm_gpu_zero_kept',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-GPU_MEMORY_UTILIZATION": { value: "0" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m --gpu-memory-utilization 0"',
     'boundary: граница: GPU_MEMORY_UTILIZATION="0" печатается как --gpu-memory-utilization 0'),
    ('vllm_maxlen_gpu_empty_omitted',
     'F({ "te-VLLM_MODEL": { value: "m" }, "te-MAX_MODEL_LEN": { value: "" }, "te-GPU_MEMORY_UTILIZATION": { value: "" } });',
     'le.buildVllmCommandPreview("te-")',
     '"$HOME/vllm-venv/bin/vllm serve m --host 0.0.0.0 --port \\"$PORT\\" --served-model-name m"',
     'negative: пустые MAX_MODEL_LEN и GPU_MEMORY_UTILIZATION — оба флага опущены (пара к нулевым границам)'),
    ('exec_whisper_tr_comment_line',
     'F({ "tr-RUNNER": { value: "whisper" }, "tr-PORT": { value: "22006" } });',
     'le._buildCommandExecPreview("tr-").split("\\n")[1]',
     '"# model downloads on first start into <models root>/whisper"',
     'positive: tr- whisper: строка [1] — комментарий про загрузку модели в <models root>/whisper'),
    ('exec_whisper_tr_exec_line',
     'F({ "tr-RUNNER": { value: "whisper" }, "tr-PORT": { value: "22006" } });',
     'le._buildCommandExecPreview("tr-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/whisper\\" bash $HOME/run_whisper.sh \\"$PORT\\" large-v3"',
     'positive: tr- whisper: строка [2] — exec с HUGGINGFACE_HUB_CACHE и размером large-v3 по умолчанию'),
    ('exec_whisper_tr_port_fallback_literal',
     'F({ "tr-RUNNER": { value: "whisper" } });',
     'le._buildCommandExecPreview("tr-").split("\\n")[0]',
     '"export PORT=PORT"',
     'negative: tr- whisper без поля PORT и без открытой ячейки — литерал PORT'),
    ('exec_whisper_te_not_tr',
     'F({ "te-RUNNER": { value: "whisper" }, "te-PORT": { value: "22006" } });',
     'le._buildCommandExecPreview("tr-")',
     '"export PORT=PORT\\nexec …"',
     'negative: whisper-поля с префиксом te- не видны tr-превью — оно падает в custom с литералом PORT'),
    ('exec_translate_tr_comment_line',
     'F({ "tr-RUNNER": { value: "translate" }, "tr-PORT": { value: "22006" } });',
     'le._buildCommandExecPreview("tr-").split("\\n")[1]',
     '"# model downloads on first start into <models root>/translate"',
     'positive: tr- translate: строка [1] — комментарий про <models root>/translate'),
    ('exec_whisper_lines_count',
     'F({ "te-RUNNER": { value: "whisper" }, "te-PORT": { value: "22006" } });',
     'le._buildCommandExecPreview("te-").split("\\n").length',
     '3',
     'positive: whisper-превью — ровно три строки (export, комментарий, exec)'),
    ('exec_seamless_model_ws_ellipsis',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "  " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# first start provisions ~/seamless-venv (torch + transformers)\\nexec bash $HOME/run_seamless.sh \\"$PORT\\" \\"…\\" rus"',
     'boundary: seamless: MODEL_FILE из одних пробелов тримится в пусто → "…" и tgt rus'),
    ('exec_transcribe_model_ws_ellipsis',
     'F({ "te-RUNNER": { value: "transcribe" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "  " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# the engine and its venv come from scripts/install-transcribe.sh\\nexec bash $HOME/run_transcribe.sh \\"$PORT\\" \\"…\\""',
     'boundary: transcribe: MODEL_FILE из одних пробелов → "…"'),
    ('exec_seamless_model_ws_trimmed',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: " m4t " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_seamless.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/m4t rus"',
     'negative: seamless: пробелы вокруг непустого MODEL_FILE тримятся, относительный путь под models-dir'),
    ('exec_transcribe_tilde_relative',
     'F({ "te-RUNNER": { value: "transcribe" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "~/m/x.gguf" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_transcribe.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/~/m/x.gguf"',
     'as-is: как есть: transcribe считает ~/… относительным путём (исключены только / и $) — получается models-dir/~/m/x.gguf'),
    ('exec_seamless_tilde_relative',
     'F({ "te-RUNNER": { value: "seamless" }, "te-PORT": { value: "22005" }, "te-MODEL_FILE": { value: "~/m4t" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec bash $HOME/run_seamless.sh \\"$PORT\\" \\"${LLAMA_MODELS_DIR:-$HOME/llama.cpp/models}\\"/~/m4t rus"',
     'as-is: как есть: seamless тот же тильда-дефект — models-dir/~/m4t'),
    ('exec_translate_src_ws_double_space',
     'F({ "te-RUNNER": { value: "translate" }, "te-PORT": { value: "22005" }, "te-TRANSLATE_SRC_LANG": { value: " " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-distilled-600M  rus_Cyrl"',
     'as-is: как есть: пробельный SRC_LANG тримится в пусто без дефолта — двойной пробел посреди команды'),
    ('exec_translate_tgt_ws_trailing_space',
     'F({ "te-RUNNER": { value: "translate" }, "te-PORT": { value: "22005" }, "te-TRANSLATE_TGT_LANG": { value: " " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-distilled-600M eng_Latn "',
     'as-is: как есть: пробельный TGT_LANG → команда заканчивается висячим пробелом, дефолт rus_Cyrl не срабатывает'),
    ('exec_translate_src_trimmed',
     'F({ "te-RUNNER": { value: "translate" }, "te-PORT": { value: "22005" }, "te-TRANSLATE_SRC_LANG": { value: " deu_Latn " } });',
     'le._buildCommandExecPreview("te-").split("\\n")[2]',
     '"exec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/translate\\" bash $HOME/run_translate.sh \\"$PORT\\" facebook/nllb-200-distilled-600M deu_Latn rus_Cyrl"',
     'negative: непустой SRC_LANG тримится и печатается одним пробелом (пара к as-is двойного пробела)'),
    ('exec_custom_env_comma_value_truncated',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-ENV": { value: "LIST=a,b" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport LIST=\\"a\\"\\nexec x"',
     'as-is: как есть: запятая в значении ENV режет его — LIST="a", хвост b без \'=\' молча выброшен (значение с запятой невыразимо)'),
    ('exec_custom_env_comma_value_both_eq',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-ENV": { value: "LIST=a,B=b" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport LIST=\\"a\\"\\nexport B=\\"b\\"\\nexec x"',
     'negative: запятая как разделитель двух пар — обе экспортируются (контроль к усечению)'),
    ('exec_custom_workdir_spaces_unquoted',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-WORKDIR": { value: "/srv/my app" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\ncd /srv/my app\\nexec x"',
     'as-is: как есть: WORKDIR с пробелом печатается без кавычек — cd /srv/my app'),
    ('exec_custom_workdir_trimmed',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-WORKDIR": { value: "  /srv/app  " } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\ncd /srv/app\\nexec x"',
     'positive: WORKDIR тримится по краям перед cd'),
    ('exec_custom_exec_uppercase_kept',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "EXEC python x.py" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[1]',
     '"exec EXEC python x.py"',
     'negative: срез ведущего exec регистрозависим — EXEC не срезается и дублируется'),
    ('exec_custom_exec_tab_stripped',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "exec\\tpython x.py" } });',
     'le._buildCommandExecPreview("te-").split("\\n")[1]',
     '"exec python x.py"',
     'positive: exec с табом после слова срезается (\\s+ покрывает таб)'),
    ('exec_custom_env_lower_underscore_keys',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-ENV": { value: "_x1=a\\nab_C9=b" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport _x1=\\"a\\"\\nexport ab_C9=\\"b\\"\\nexec x"',
     'positive: ключи с ведущим подчёркиванием и строчными буквами валидны и экспортируются'),
    ('exec_custom_env_key_dash_skipped',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-ENV": { value: "a-b=1\\nA=1" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1\\"\\nexec x"',
     'negative: ключ с дефисом отбрасывается, соседняя валидная пара остаётся'),
    ('exec_custom_env_comment_leading_ws_skipped',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-ENV": { value: "   # x=1\\nA=1" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1\\"\\nexec x"',
     "positive: комментарий с ведущими пробелами пропускается (trim до startsWith('#'))"),
    ('exec_custom_env_hash_inside_kept',
     'F({ "te-CELL_KIND": { value: "command" }, "te-PORT": { value: "22005" }, "te-COMMAND": { value: "x" }, "te-ENV": { value: "A=1 # note" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexport A=\\"1 # note\\"\\nexec x"',
     'negative: решётка не в начале строки — не комментарий, попадает в значение целиком'),
    ('exec_runner_case_sensitive_whisper',
     'F({ "te-RUNNER": { value: "Whisper" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec …"',
     'as-is: как есть: RUNNER регистрозависим — "Whisper" проваливается через все ветки в custom'),
    ('exec_runner_lowercase_whisper',
     'F({ "te-RUNNER": { value: "whisper" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\n# model downloads on first start into <models root>/whisper\\nexec env HUGGINGFACE_HUB_CACHE=\\"${LLAMA_MODELS_DIR:-$HOME/llama-model-cache}/whisper\\" bash $HOME/run_whisper.sh \\"$PORT\\" large-v3"',
     'negative: строчный "whisper" попадает в свою ветку (контроль к регистрозависимости)'),
    ('exec_runner_case_sensitive_vllm',
     'F({ "te-RUNNER": { value: "VLLM" }, "te-PORT": { value: "22005" } });',
     'le._buildCommandExecPreview("te-")',
     '"export PORT=22005\\nexec …"',
     'as-is: как есть: "VLLM" тоже не распознаётся — custom-ветка с exec …'),
    # ── artifacts_devices ──
    ('ak_moonshine',
     '',
     'le.artifactKind("moonshine/base-en")',
     '"moonshine-lang"',
     'positive: artifactKind: путь moonshine/… даёт moonshine-lang'),
    ('ak_whisper',
     '',
     'le.artifactKind("whisper/models--Systran--faster-whisper-large-v3")',
     '"whisper-size"',
     'positive: artifactKind: whisper/models--Systran--faster-whisper-… даёт whisper-size'),
    ('ak_whisper_other_repo',
     '',
     'le.artifactKind("whisper/models--openai--whisper-large")',
     '"safetensors"',
     'as-is: artifactKind: whisper-репо не от Systran проваливается в safetensors (префикс строгий, как есть)'),
    ('ak_nllb',
     '',
     'le.artifactKind("translate/models--facebook--nllb-200-distilled-600M")',
     '"nllb-repo"',
     'positive: artifactKind: translate/models--… даёт nllb-repo'),
    ('ak_seamless_found',
     'st.state.artifacts = [{ path: "st/seamless-m4t-v2", arch: "seamless_m4t_v2" }];',
     'le.artifactKind("st/seamless-m4t-v2")',
     '"seamless-st"',
     'positive: artifactKind: не-gguf путь из state.artifacts с arch seamless_m4t* даёт seamless-st'),
    ('ak_st_found_other_arch',
     'st.state.artifacts = [{ path: "st/qwen", arch: "qwen2" }];',
     'le.artifactKind("st/qwen")',
     '"safetensors"',
     'negative: artifactKind: найденный не-gguf артефакт с другой arch даёт safetensors'),
    ('ak_st_not_found',
     '',
     'le.artifactKind("st/whatever-dir")',
     '"safetensors"',
     'positive: artifactKind: не-gguf путь, которого нет в state.artifacts, всё равно safetensors'),
    ('ak_st_artifacts_undefined',
     'st.state.artifacts = undefined;',
     'le.artifactKind("st/whatever-dir")',
     '"safetensors"',
     'boundary: artifactKind: state.artifacts=undefined не роняет, не-gguf → safetensors'),
    ('ak_gguf_asr',
     'st.state.models = [{ path: "m/gigaam.gguf", ggufMeta: { sttVariant: "gigaam" } }];',
     'le.artifactKind("m/gigaam.gguf")',
     '"asr-gguf"',
     'positive: artifactKind: .gguf из state.models с ggufMeta.sttVariant даёт asr-gguf'),
    ('ak_gguf_llm',
     'st.state.models = [{ path: "m/qwen.gguf", ggufMeta: {} }];',
     'le.artifactKind("m/qwen.gguf")',
     '"llm-gguf"',
     'negative: artifactKind: .gguf из state.models без sttVariant даёт llm-gguf'),
    ('ak_gguf_llm_no_meta',
     'st.state.models = [{ path: "m/qwen.gguf" }];',
     'le.artifactKind("m/qwen.gguf")',
     '"llm-gguf"',
     'boundary: artifactKind: .gguf без ggufMeta вовсе — тоже llm-gguf'),
    ('ak_gguf_unknown',
     '',
     'le.artifactKind("m/unknown.gguf")',
     '""',
     'as-is: artifactKind: .gguf, которого нет в state.models, даёт "" (неизвестное никогда не блокирует, как есть)'),
    ('ak_gguf_models_undefined',
     'st.state.models = undefined;',
     'le.artifactKind("m/unknown.gguf")',
     '""',
     'boundary: artifactKind: state.models=undefined не роняет, .gguf → ""'),
    ('ak_empty',
     '',
     'le.artifactKind("")',
     '""',
     'negative: artifactKind: пустая строка даёт ""'),
    ('ak_whitespace',
     '',
     'le.artifactKind("   ")',
     '""',
     'boundary: artifactKind: одни пробелы даёт "" (trim)'),
    ('ak_undefined',
     '',
     'le.artifactKind(undefined)',
     '""',
     'boundary: artifactKind: undefined даёт ""'),
    ('ak_upper_GGUF_found',
     'st.state.models = [{ path: "m/X.GGUF", ggufMeta: {} }];',
     'le.artifactKind("m/X.GGUF")',
     '"llm-gguf"',
     'boundary: artifactKind: суффикс .GGUF в верхнем регистре считается gguf, поиск по точному пути'),
    ('ak_trimmed_lookup',
     'st.state.models = [{ path: "m/qwen.gguf", ggufMeta: {} }];',
     'le.artifactKind("  m/qwen.gguf  ")',
     '"llm-gguf"',
     'boundary: artifactKind: пробелы вокруг пути срезаются до поиска в state.models'),
    ('ak_precedence_moonshine_gguf',
     '',
     'le.artifactKind("moonshine/x.gguf")',
     '"moonshine-lang"',
     'boundary: artifactKind: префикс moonshine/ побеждает суффикс .gguf'),
    ('cap_rtx5090',
     '',
     'le.gpuComputeCap("NVIDIA GeForce RTX 5090")',
     '12',
     'positive: gpuComputeCap: RTX 5090 → 12 (Blackwell consumer)'),
    ('cap_rtx50_substring_rtx5000',
     '',
     'le.gpuComputeCap("NVIDIA RTX 5000 Ada")',
     '12',
     'as-is: gpuComputeCap: RTX 5000 Ada попадает под /RTX 50/ и даёт 12 вместо 8.9 (как есть)'),
    ('cap_b200',
     '',
     'le.gpuComputeCap("NVIDIA B200")',
     '10',
     'positive: gpuComputeCap: B200 → 10 (Blackwell datacenter)'),
    ('cap_gb10',
     '',
     'le.gpuComputeCap("NVIDIA GB10")',
     '10',
     'positive: gpuComputeCap: GB10 → 10'),
    ('cap_gb100',
     '',
     'le.gpuComputeCap("NVIDIA GB100")',
     '10',
     'boundary: gpuComputeCap: GB100 → 10 (\\bGB[12]0 без правой границы ловит и GB100)'),
    ('cap_gb300',
     '',
     'le.gpuComputeCap("NVIDIA GB300")',
     'null',
     'as-is: gpuComputeCap: GB300 (Blackwell Ultra) не в карте → null (как есть)'),
    ('cap_h100',
     '',
     'le.gpuComputeCap("NVIDIA H100 80GB HBM3")',
     '9',
     'positive: gpuComputeCap: H100 → 9 (Hopper)'),
    ('cap_gh200',
     '',
     'le.gpuComputeCap("GH200")',
     '9',
     'positive: gpuComputeCap: GH200 → 9'),
    ('cap_rtx4090',
     '',
     'le.gpuComputeCap("NVIDIA GeForce RTX 4090")',
     '8.9',
     'positive: gpuComputeCap: RTX 4090 → 8.9 (Ada)'),
    ('cap_l4',
     '',
     'le.gpuComputeCap("NVIDIA L4")',
     '8.9',
     'positive: gpuComputeCap: L4 → 8.9'),
    ('cap_l40s',
     '',
     'le.gpuComputeCap("NVIDIA L40S")',
     '8.9',
     'boundary: gpuComputeCap: L40S → 8.9 (\\bL40 без правой границы)'),
    ('cap_rtx3050',
     '',
     'le.gpuComputeCap("NVIDIA GeForce RTX 3050")',
     '8.6',
     'positive: gpuComputeCap: RTX 3050 → 8.6 (Ampere)'),
    ('cap_a2000',
     '',
     'le.gpuComputeCap("NVIDIA RTX A2000")',
     'null',
     'as-is: gpuComputeCap: RTX A2000 (Ampere) не матчится ни \\bA2\\b, ни A[45]000 → null (как есть)'),
    ('cap_a2',
     '',
     'le.gpuComputeCap("NVIDIA A2")',
     '8.6',
     'boundary: gpuComputeCap: A2 → 8.6 (граница слова держит)'),
    ('cap_a16',
     '',
     'le.gpuComputeCap("NVIDIA A16")',
     '8.6',
     'positive: gpuComputeCap: A16 → 8.6'),
    ('cap_a1600',
     '',
     'le.gpuComputeCap("NVIDIA A1600")',
     'null',
     'negative: gpuComputeCap: A1600 не проходит границу \\bA16\\b → null'),
    ('cap_a5000',
     '',
     'le.gpuComputeCap("NVIDIA RTX A5000")',
     '8.6',
     'positive: gpuComputeCap: RTX A5000 → 8.6'),
    ('cap_a6000',
     '',
     'le.gpuComputeCap("NVIDIA RTX A6000")',
     '8.6',
     'positive: gpuComputeCap: RTX A6000 → 8.6'),
    ('cap_a100',
     '',
     'le.gpuComputeCap("NVIDIA A100-SXM4-80GB")',
     '8',
     'positive: gpuComputeCap: A100 → 8 (Ampere datacenter)'),
    ('cap_a30',
     '',
     'le.gpuComputeCap("NVIDIA A30")',
     '8',
     'positive: gpuComputeCap: A30 → 8'),
    ('cap_rtx2080',
     '',
     'le.gpuComputeCap("NVIDIA GeForce RTX 2080 Ti")',
     '7.5',
     'positive: gpuComputeCap: RTX 2080 Ti → 7.5 (Turing)'),
    ('cap_titan_rtx',
     '',
     'le.gpuComputeCap("TITAN RTX")',
     '7.5',
     'positive: gpuComputeCap: TITAN RTX → 7.5'),
    ('cap_t4',
     '',
     'le.gpuComputeCap("Tesla T4")',
     '7.5',
     'positive: gpuComputeCap: T4 → 7.5'),
    ('cap_t400',
     '',
     'le.gpuComputeCap("NVIDIA T400")',
     'null',
     'negative: gpuComputeCap: T400 не проходит \\bT4\\b → null'),
    ('cap_v100',
     '',
     'le.gpuComputeCap("Tesla V100-PCIE-16GB")',
     '7',
     'positive: gpuComputeCap: V100 → 7 (Volta)'),
    ('cap_gtx1080',
     '',
     'le.gpuComputeCap("NVIDIA GeForce GTX 1080")',
     'null',
     'negative: gpuComputeCap: GTX 1080 (Pascal) → null'),
    ('cap_lowercase',
     '',
     'le.gpuComputeCap("nvidia geforce rtx 3090")',
     '8.6',
     'boundary: gpuComputeCap: строчные буквы приводятся к верхнему регистру → 8.6'),
    ('cap_empty',
     '',
     'le.gpuComputeCap("")',
     'null',
     'negative: gpuComputeCap: пустая строка → null'),
    ('cap_undefined',
     '',
     'le.gpuComputeCap(undefined)',
     'null',
     'boundary: gpuComputeCap: undefined → null'),
    ('dev_cpu_wins',
     '',
     'le._envDeviceState("TTS_DEVICE=cuda\\nTTS_DEVICE=cpu", "")',
     '"cpu"',
     'positive: _envDeviceState: при cuda и cpu в ENV побеждает cpu'),
    ('dev_cpu_wins_cmd_gpu',
     '',
     'le._envDeviceState("TTS_DEVICE=cpu", "python x.py --device cuda")',
     '"cpu"',
     'positive: _envDeviceState: cpu в ENV побеждает --device cuda в команде'),
    ('dev_cvd_empty',
     '',
     'le._envDeviceState("CUDA_VISIBLE_DEVICES=", "")',
     '"cpu"',
     'positive: _envDeviceState: пустой CUDA_VISIBLE_DEVICES= → cpu'),
    ('dev_cvd_empty_dquotes',
     '',
     'le._envDeviceState(\'CUDA_VISIBLE_DEVICES=""\', "")',
     '"cpu"',
     'positive: _envDeviceState: CUDA_VISIBLE_DEVICES="" (двойные кавычки) → cpu'),
    ('dev_cvd_empty_squotes',
     '',
     'le._envDeviceState("CUDA_VISIBLE_DEVICES=\'\'", "")',
     '"cpu"',
     "positive: _envDeviceState: CUDA_VISIBLE_DEVICES='' (одинарные кавычки) → cpu"),
    ('dev_cvd_empty_mid',
     '',
     'le._envDeviceState("FOO=1\\nCUDA_VISIBLE_DEVICES=\\nBAR=2", "")',
     '"cpu"',
     'boundary: _envDeviceState: пустой CUDA_VISIBLE_DEVICES= в середине строк → cpu'),
    ('dev_cvd_zero',
     '',
     'le._envDeviceState("CUDA_VISIBLE_DEVICES=0", "")',
     '"auto"',
     'negative: _envDeviceState: CUDA_VISIBLE_DEVICES=0 не cpu → auto'),
    ('dev_cvd_in_cmd_ignored',
     '',
     'le._envDeviceState("", "CUDA_VISIBLE_DEVICES= python x.py")',
     '"auto"',
     'negative: _envDeviceState: пустой CUDA_VISIBLE_DEVICES в команде (не в ENV) не учитывается → auto'),
    ('dev_device_eq_gpu',
     '',
     'le._envDeviceState("", "python x.py --device=gpu")',
     '"gpu"',
     'positive: _envDeviceState: --device=gpu только в команде → gpu'),
    ('dev_device_space_cuda',
     '',
     'le._envDeviceState("", "python x.py --device cuda")',
     '"gpu"',
     'positive: _envDeviceState: --device cuda через пробел только в команде → gpu'),
    ('dev_device_space_cpu_cmd',
     '',
     'le._envDeviceState("", "python x.py --device cpu")',
     '"cpu"',
     'positive: _envDeviceState: --device cpu только в команде → cpu'),
    ('dev_DEVICE_cudart',
     '',
     'le._envDeviceState("DEVICE=cudart", "")',
     '"auto"',
     'negative: _envDeviceState: DEVICE=cudart не проходит границу слова → auto'),
    ('dev_MYDEVICE_cuda',
     '',
     'le._envDeviceState("MYDEVICE=cuda", "")',
     '"auto"',
     'negative: _envDeviceState: MYDEVICE=cuda не якорится на начало имени → auto'),
    ('dev_DEVICE_cuda',
     '',
     'le._envDeviceState("DEVICE=cuda", "")',
     '"gpu"',
     'positive: _envDeviceState: DEVICE=cuda в ENV → gpu'),
    ('dev_TTS_DEVICE_gpu_lower',
     '',
     'le._envDeviceState("tts_device=GPU", "")',
     '"gpu"',
     'boundary: _envDeviceState: регистр не важен, tts_device=GPU → gpu'),
    ('dev_cpu_semicolon_cmd',
     '',
     'le._envDeviceState("", "TTS_DEVICE=cpu;python x.py")',
     '"cpu"',
     'positive: _envDeviceState: TTS_DEVICE=cpu в начале команды перед ; → cpu'),
    ('dev_TTS_DEVICE_cpux',
     '',
     'le._envDeviceState("TTS_DEVICE=cpux", "")',
     '"auto"',
     'negative: _envDeviceState: TTS_DEVICE=cpux не проходит \\b после cpu → auto'),
    ('dev_auto_empty',
     '',
     'le._envDeviceState("", "")',
     '"auto"',
     'negative: _envDeviceState: пустые ENV и команда → auto'),
    ('app_cpu_strips',
     '',
     'le._applyDeviceToEnv("FOO=1\\ntts_device=cuda\\ncuda_visible_devices=0\\nBAR=2", "cpu")',
     '"FOO=1\\nBAR=2\\nTTS_DEVICE=cpu\\nCUDA_VISIBLE_DEVICES="',
     'positive: _applyDeviceToEnv cpu: старые TTS_DEVICE/CUDA_VISIBLE_DEVICES (любой регистр) выкинуты, остальное сохранено, дописаны две строки'),
    ('app_gpu_strips',
     '',
     'le._applyDeviceToEnv("FOO=1\\nTTS_DEVICE=cpu\\nCUDA_VISIBLE_DEVICES=\\nBAR=2", "gpu")',
     '"FOO=1\\nBAR=2\\nTTS_DEVICE=cuda"',
     'positive: _applyDeviceToEnv gpu: cpu-строки сняты, дописана одна TTS_DEVICE=cuda'),
    ('app_auto_strips',
     '',
     'le._applyDeviceToEnv("FOO=1\\nTTS_DEVICE=cpu\\nCUDA_VISIBLE_DEVICES=\\nBAR=2", "auto")',
     '"FOO=1\\nBAR=2"',
     'negative: _applyDeviceToEnv auto: device-строки сняты, ничего не дописано'),
    ('app_cpu_empty',
     '',
     'le._applyDeviceToEnv("", "cpu")',
     '"TTS_DEVICE=cpu\\nCUDA_VISIBLE_DEVICES="',
     'boundary: _applyDeviceToEnv: пустой ENV + cpu → ровно две строки'),
    ('app_gpu_empty',
     '',
     'le._applyDeviceToEnv("", "gpu")',
     '"TTS_DEVICE=cuda"',
     'boundary: _applyDeviceToEnv: пустой ENV + gpu → одна строка'),
    ('app_auto_empty',
     '',
     'le._applyDeviceToEnv("", "auto")',
     '""',
     'negative: _applyDeviceToEnv: пустой ENV + auto → пустая строка'),
    ('app_undefined_cpu',
     '',
     'le._applyDeviceToEnv(undefined, "cpu")',
     '"TTS_DEVICE=cpu\\nCUDA_VISIBLE_DEVICES="',
     'boundary: _applyDeviceToEnv: undefined ENV не роняет, cpu → две строки'),
    ('app_comma_split',
     '',
     'le._applyDeviceToEnv("A=1, B=2,C=3", "auto")',
     '"A=1\\nB=2\\nC=3"',
     'as-is: _applyDeviceToEnv: ввод через запятую переписывается через перевод строки (разделитель не сохраняется, как есть)'),
    ('app_blank_rows_dropped',
     '',
     'le._applyDeviceToEnv("A=1\\n\\n  \\nB=2", "auto")',
     '"A=1\\nB=2"',
     'boundary: _applyDeviceToEnv: пустые и пробельные строки выбрасываются'),
    ('app_unknown_mode',
     '',
     'le._applyDeviceToEnv("A=1", "banana")',
     '"A=1"',
     'negative: _applyDeviceToEnv: неизвестный режим ведёт себя как auto — ничего не дописывает'),
    ('app_MYTTS_DEVICE_kept',
     '',
     'le._applyDeviceToEnv("MYTTS_DEVICE=cpu", "auto")',
     '"MYTTS_DEVICE=cpu"',
     'negative: _applyDeviceToEnv: строка с префиксом перед TTS_DEVICE не снимается (якорь ^)'),
    ('rr_fallback_empty',
     '',
     'le.runnerRegistry()',
     '[{"id":"llama-server","icon":"🦙","labelKey":"runnerLlama","benefitsKey":"runnerLlamaBenefits","formats":["gguf"]},{"id":"custom","icon":"🛠️","labelKey":"runnerCustom","benefitsKey":"runnerCustomBenefits","formats":["*"]}]',
     'positive: runnerRegistry: state.runners=[] → встроенная пара llama-server/custom'),
    ('rr_fallback_undefined',
     'st.state.runners = undefined;',
     'le.runnerRegistry()',
     '[{"id":"llama-server","icon":"🦙","labelKey":"runnerLlama","benefitsKey":"runnerLlamaBenefits","formats":["gguf"]},{"id":"custom","icon":"🛠️","labelKey":"runnerCustom","benefitsKey":"runnerCustomBenefits","formats":["*"]}]',
     'boundary: runnerRegistry: state.runners=undefined → та же встроенная пара'),
    ('rr_fallback_nonarray',
     'st.state.runners = { id: "x" };',
     'le.runnerRegistry()',
     '[{"id":"llama-server","icon":"🦙","labelKey":"runnerLlama","benefitsKey":"runnerLlamaBenefits","formats":["gguf"]},{"id":"custom","icon":"🛠️","labelKey":"runnerCustom","benefitsKey":"runnerCustomBenefits","formats":["*"]}]',
     'boundary: runnerRegistry: state.runners не массив → встроенная пара'),
    ('rr_provided',
     'st.state.runners = [{ id: "moonshine", icon: "🌙", artifacts: ["moonshine-lang"] }];',
     'le.runnerRegistry()',
     '[{"id":"moonshine","icon":"🌙","artifacts":["moonshine-lang"]}]',
     'negative: runnerRegistry: непустой state.runners возвращается как есть, без встроенной пары'),
    ('bl_prefix',
     '',
     'le.backupLabel("/opt/x/var/backups/start-server.sh.bak.20260901-123456-mine")',
     '"20260901-123456-mine"',
     'positive: backupLabel: берёт basename и срезает префикс start-server.sh.bak.'),
    ('bl_no_prefix',
     '',
     'le.backupLabel("/opt/x/var/backups/other.txt")',
     '"other.txt"',
     'negative: backupLabel: без префикса — просто basename'),
    ('bl_prefix_twice',
     '',
     'le.backupLabel("start-server.sh.bak.start-server.sh.bak.x")',
     '"start-server.sh.bak.x"',
     'as-is: backupLabel: replace строкой снимает только первое вхождение префикса (как есть)'),
    ('bl_number',
     '',
     'le.backupLabel(42)',
     '"42"',
     'boundary: backupLabel: число приводится к строке'),
    ('bp_string',
     '',
     'le.backupPath("/a/b")',
     '"/a/b"',
     'positive: backupPath: строка возвращается как есть'),
    ('bp_object',
     '',
     'le.backupPath({ path: "/a/b", label: "L" })',
     '"/a/b"',
     'positive: backupPath: у объекта берётся .path'),
    ('bdl_string',
     '',
     'le.backupDisplayLabel("/a/start-server.sh.bak.foo")',
     '"foo"',
     'positive: backupDisplayLabel: строка → backupLabel'),
    ('bdl_label_wins',
     '',
     'le.backupDisplayLabel({ path: "/a/start-server.sh.bak.foo", label: "My label" })',
     '"My label"',
     'positive: backupDisplayLabel: label объекта побеждает путь'),
    ('bdl_no_label',
     '',
     'le.backupDisplayLabel({ path: "/a/start-server.sh.bak.foo", label: "" })',
     '"foo"',
     'negative: backupDisplayLabel: пустой label → падаем на backupLabel(path)'),
    ('bcl_match',
     '',
     'le.backupCreatedLabel("/a/start-server.sh.bak.20260901-123456-mine")',
     '"2026-09-01 12:34:56"',
     'positive: backupCreatedLabel: 20260901-123456… форматируется в 2026-09-01 12:34:56, хвост -mine отброшен'),
    ('bcl_match_obj_label_ignored',
     '',
     'le.backupCreatedLabel({ path: "/a/start-server.sh.bak.20260901-123456", label: "Custom" })',
     '"2026-09-01 12:34:56"',
     'positive: backupCreatedLabel: у объекта дата берётся из path, label не участвует'),
    ('bcl_nomatch',
     '',
     'le.backupCreatedLabel("/a/start-server.sh.bak.mine-20260901-123456")',
     '"mine-20260901-123456"',
     'negative: backupCreatedLabel: метка не начинается с даты → возвращается метка без изменений'),
    ('bcl_short_digits',
     '',
     'le.backupCreatedLabel("/a/start-server.sh.bak.2026090-123456")',
     '"2026090-123456"',
     'boundary: backupCreatedLabel: 7 цифр вместо 8 — не матч, метка как есть'),
    ('csc_tr',
     'st.topology.nodes = [{ servers: [{ isSlot: true, port: 22001, slotConfig: { MODEL_FILE: "x" } }] }];',
     'le.currentSavedConfig("tr-")',
     'null',
     'negative: currentSavedConfig: для tr- всегда null, даже при слоте с конфигом'),
    ('cp_table',
     '',
     'le.COMMAND_PRESETS.map((p) => [p.id, p.COMMAND, p.HEALTH_PATH])',
     '[["",null,null],["whisper","bash ~/run_whisper.sh $PORT large-v3","/health"],["tts-xtts","bash ~/run_tts.sh $PORT xtts","/health"],["tts-f5","bash ~/run_tts.sh $PORT f5","/health"],["tts-cosyvoice","bash ~/run_tts.sh $PORT cosyvoice","/health"]]',
     'positive: COMMAND_PRESETS: таблица [id, COMMAND, HEALTH_PATH]; у плейсхолдера COMMAND/HEALTH_PATH отсутствуют (JSON печатает null)'),
    ('cp_placeholder_labelKey',
     '',
     'le.COMMAND_PRESETS[0].labelKey',
     '"cmdPresetPlaceholder"',
     'positive: COMMAND_PRESETS: плейсхолдер несёт labelKey cmdPresetPlaceholder вместо label'),
    ('cp_labels',
     '',
     'le.COMMAND_PRESETS.map((p) => p.label)',
     '[null,"whisper · faster-whisper (large-v3)","tts · XTTS-v2 (voice clone) — non-commercial","tts · F5-TTS (voice clone) — MIT code, NC base model","tts · CosyVoice2 (voice clone) — Apache-2.0"]',
     'positive: COMMAND_PRESETS: подписи пресетов с лицензией в тексте; у плейсхолдера label отсутствует (null в JSON)'),
    ('csc_te_slot_overlays',
     'st.state.config = { BASE: "b", MODEL_FILE: "old" }; st.topology.nodes = [{ servers: [{ isSlot: true, port: 22001, slotConfig: { MODEL_FILE: "x" } }] }]; try { le.openTopologyLlamaEdit("edit", 22001); } catch (e) {};',
     'le.currentSavedConfig("te-")',
     '{"BASE":"b","MODEL_FILE":"x"}',
     'positive: currentSavedConfig("te-") с открытой ячейкой: slotConfig ячейки накладывается поверх state.config (числовой порт сравнивается через String)'),
    ('csc_te_slotConfig_empty',
     'st.state.config = { BASE: "b" }; st.topology.nodes = [{ servers: [{ isSlot: true, port: 22001, slotConfig: {} }] }]; try { le.openTopologyLlamaEdit("edit", 22001); } catch (e) {};',
     'le.currentSavedConfig("te-")',
     'null',
     'negative: currentSavedConfig("te-"): открытая ячейка с пустым slotConfig {} → null (гвард Object.keys().length)'),
    ('csc_te_port_not_found',
     'st.state.config = { BASE: "b" }; st.topology.nodes = [{ servers: [{ isSlot: true, port: 22002, slotConfig: { MODEL_FILE: "x" } }] }]; try { le.openTopologyLlamaEdit("edit", 22001); } catch (e) {};',
     'le.currentSavedConfig("te-")',
     'null',
     'negative: currentSavedConfig("te-"): открыт порт 22001, в топологии только 22002 → null'),
    ('csc_te_not_slot',
     'st.state.config = { BASE: "b" }; st.topology.nodes = [{ servers: [{ isSlot: false, port: 22001, slotConfig: { MODEL_FILE: "x" } }] }]; try { le.openTopologyLlamaEdit("edit", 22001); } catch (e) {};',
     'le.currentSavedConfig("te-")',
     'null',
     'negative: currentSavedConfig("te-"): сервер на том же порту, но isSlot:false → null'),
    ('csc_teCellPort_after_open',
     'try { le.openTopologyLlamaEdit("edit", 22001); } catch (e) {};',
     'le._teCellPort',
     '"22001"',
     'positive: _teCellPort после openTopologyLlamaEdit("edit", 22001) → "22001" (строка; присваивается на первой строке до броска на DOM-словаре)'),
    ('csc_tr_with_cell_open',
     'st.state.config = { BASE: "b" }; st.topology.nodes = [{ servers: [{ isSlot: true, port: 22001, slotConfig: { MODEL_FILE: "x" } }] }]; try { le.openTopologyLlamaEdit("edit", 22001); } catch (e) {};',
     'le.currentSavedConfig("tr-")',
     'null',
     'negative: currentSavedConfig("tr-") → null даже при открытой контроллерной ячейке с slotConfig (ветка только для "te-")'),
    ('csc_open_throws',
     '',
     '(() => { try { le.openTopologyLlamaEdit("edit", 22001); return "no throw"; } catch (e) { return e.message; } finally { try { le.openTopologyLlamaEdit("edit", ""); } catch (e) {} } })()',
     '"Cannot set properties of null (setting \'hidden\')"',
     'as-is: openTopologyLlamaEdit в харнессе бросает на DOM-словаре ПОСЛЕ присваивания _teCellPort — потому setup csc-пинов оборачивает вызов в try/catch; порт возвращается в "" в finally'),
    ('cap_h200',
     '',
     'le.gpuComputeCap("NVIDIA H200")',
     '9',
     'positive: gpuComputeCap: H200 → 9 (Hopper, альтернатива H200)'),
    ('cap_a40',
     '',
     'le.gpuComputeCap("NVIDIA A40")',
     '8.6',
     'positive: gpuComputeCap: A40 → 8.6 (альтернатива \\bA(40)\\b)'),
    ('cap_a10',
     '',
     'le.gpuComputeCap("NVIDIA A10")',
     '8.6',
     'positive: gpuComputeCap: A10 → 8.6 (альтернатива \\bA(10)\\b)'),
    ('cap_b100',
     '',
     'le.gpuComputeCap("NVIDIA B100")',
     '10',
     'positive: gpuComputeCap: B100 → 10 (альтернатива \\bB[12]00\\b, единица)'),
    ('cap_gb200',
     '',
     'le.gpuComputeCap("NVIDIA GB200")',
     '10',
     'positive: gpuComputeCap: GB200 → 10 (\\bGB[12]0 — префикс GB20)'),
    ('cap_gb20',
     '',
     'le.gpuComputeCap("NVIDIA GB20")',
     '10',
     'positive: gpuComputeCap: GB20 → 10 (\\bGB[12]0 без правой границы)'),
    ('cap_rtx_a4000',
     '',
     'le.gpuComputeCap("NVIDIA RTX A4000")',
     '8.6',
     'positive: gpuComputeCap: RTX A4000 → 8.6 (A[45]000, четвёрка)'),
    ('cap_l40',
     '',
     'le.gpuComputeCap("NVIDIA L40")',
     '8.9',
     'positive: gpuComputeCap: голый L40 → 8.9 (\\bL40 без суффикса S)'),
    ('cap_rtx4000_ada',
     '',
     'le.gpuComputeCap("NVIDIA RTX 4000 Ada Generation")',
     '8.9',
     'as-is: gpuComputeCap: RTX 4000 Ada → 8.9 — верно только по совпадению подстроки /RTX 40/, а не по распознаванию Ada-воркстейшн карты'),
    ('cap_rtx2000_ada',
     '',
     'le.gpuComputeCap("NVIDIA RTX 2000 Ada Generation")',
     '7.5',
     'as-is: gpuComputeCap: RTX 2000 Ada (Ada, реально 8.9) → 7.5 — /RTX 20/ читает воркстейшн-Ada как Turing; НЕВЕРНЫЙ не-null ответ'),
    ('cap_rtx500_ada',
     '',
     'le.gpuComputeCap("NVIDIA RTX 500 Ada Generation Laptop GPU")',
     '12',
     'as-is: gpuComputeCap: RTX 500 Ada (Ada, реально 8.9) → 12 — /RTX 50/ ловит префикс «RTX 500»; НЕВЕРНЫЙ Blackwell-ответ'),
    ('cap_rtx4500_ada',
     '',
     'le.gpuComputeCap("NVIDIA RTX 4500 Ada Generation")',
     'null',
     'as-is: gpuComputeCap: RTX 4500 Ada → null (ни одна семья не матчит «RTX 45», хотя это Ada 8.9)'),
    ('cap_a10g',
     '',
     'le.gpuComputeCap("NVIDIA A10G")',
     'null',
     'as-is: gpuComputeCap: A10G (имя в AWS) → null — \\bA10\\b не проходит перед буквой G'),
    ('cap_rtx_pro_6000',
     '',
     'le.gpuComputeCap("NVIDIA RTX PRO 6000 Blackwell")',
     'null',
     'as-is: gpuComputeCap: RTX PRO 6000 Blackwell → null (Blackwell-воркстейшн не в карте)'),
    ('cap_titan_v',
     '',
     'le.gpuComputeCap("TITAN V")',
     'null',
     'negative: gpuComputeCap: TITAN V → null (только TITAN RTX и \\bV100\\b в карте)'),
    ('cap_rtx5090_nospace',
     '',
     'le.gpuComputeCap("RTX5090")',
     'null',
     'negative: gpuComputeCap: «RTX5090» без пробела → null (шаблон требует «RTX 50»)'),
    ('cap_number',
     '',
     'le.gpuComputeCap(3090)',
     'null',
     'negative: gpuComputeCap(3090) → null (число стрингифицируется в «3090», без «RTX » не матчит)'),
    ('dev_comma_sep_cpu',
     '',
     'le._envDeviceState("FOO=1,TTS_DEVICE=cpu", "")',
     '"cpu"',
     'positive: _envDeviceState: запятая — допустимый разделитель перед TTS_DEVICE=cpu → cpu'),
    ('dev_cvd_empty_comma_term',
     '',
     'le._envDeviceState("CUDA_VISIBLE_DEVICES=,X=1", "")',
     '"cpu"',
     'positive: _envDeviceState: пустой CUDA_VISIBLE_DEVICES= с запятой-терминатором → cpu'),
    ('dev_cvd_lowercase_asis',
     '',
     'le._envDeviceState("cuda_visible_devices=", "")',
     '"auto"',
     'as-is: _envDeviceState: строчный cuda_visible_devices= → auto — регэксп без /i, тогда как _applyDeviceToEnv стирает эту строку без учёта регистра (асимметрия чтения и записи)'),
    ('dev_cvd_empty_beats_gpu',
     '',
     'le._envDeviceState("TTS_DEVICE=cuda\\nCUDA_VISIBLE_DEVICES=", "")',
     '"cpu"',
     'positive: _envDeviceState: пустой CUDA_VISIBLE_DEVICES= перевешивает явный TTS_DEVICE=cuda → cpu (оба в первом if)'),
    ('dev_device_eq_cpu',
     '',
     'le._envDeviceState("", "--device=cpu")',
     '"cpu"',
     'positive: _envDeviceState: --device=cpu в команде (форма с «=») → cpu'),
    ('dev_MYTTS_DEVICE_cpu',
     '',
     'le._envDeviceState("MYTTS_DEVICE=cpu", "")',
     '"auto"',
     'negative: _envDeviceState: MYTTS_DEVICE=cpu → auto (якорь начала/разделителя, cpu-сторона)'),
    ('dev_TTS_DEVICE_cuda_colon',
     '',
     'le._envDeviceState("TTS_DEVICE=cuda:0", "")',
     '"gpu"',
     'positive: _envDeviceState: TTS_DEVICE=cuda:0 → gpu (\\b перед двоеточием)'),
    ('dev_DEVICE_CPU_upper',
     '',
     'le._envDeviceState("DEVICE=CPU", "")',
     '"cpu"',
     'positive: _envDeviceState: DEVICE=CPU в верхнем регистре → cpu (флаг /i)'),
    ('dev_cvd_quoted_zero',
     '',
     'le._envDeviceState("CUDA_VISIBLE_DEVICES=\\"0\\"", "")',
     '"auto"',
     'negative: _envDeviceState: CUDA_VISIBLE_DEVICES="0" (кавычки с содержимым) → auto'),
    ('dev_cvd_empty_trailing_space',
     '',
     'le._envDeviceState("CUDA_VISIBLE_DEVICES= ", "")',
     '"cpu"',
     'positive: _envDeviceState: CUDA_VISIBLE_DEVICES= с хвостовым пробелом → cpu (пробел — терминатор)'),
    ('dev_MYCUDA_VISIBLE_DEVICES',
     '',
     'le._envDeviceState("MYCUDA_VISIBLE_DEVICES=", "")',
     '"auto"',
     'negative: _envDeviceState: MYCUDA_VISIBLE_DEVICES= → auto (якорь начала строки на CVD-проверке)'),
    ('dev_undefined_both',
     '',
     'le._envDeviceState(undefined, undefined)',
     '"auto"',
     'negative: _envDeviceState(undefined, undefined) → auto (шаблонная строка даёт «undefined», не бросает)'),
    ('app_semicolon_row_dropped_whole',
     '',
     'le._applyDeviceToEnv("TTS_DEVICE=cpu;B=2", "auto")',
     '""',
     'as-is: _applyDeviceToEnv: строка «TTS_DEVICE=cpu;B=2» выбрасывается ЦЕЛИКОМ вместе с B=2 — split только по \\n и запятой, тогда как _envDeviceState считает «;» разделителем'),
    ('app_leading_space_trimmed',
     '',
     'le._applyDeviceToEnv("  TTS_DEVICE=cpu\\nA=1", "auto")',
     '"A=1"',
     'positive: _applyDeviceToEnv: строка с ведущими пробелами тримится до проверки и стирается → «A=1»'),
    ('app_no_equals_kept',
     '',
     'le._applyDeviceToEnv("TTS_DEVICE\\nA=1", "auto")',
     '"TTS_DEVICE\\nA=1"',
     'negative: _applyDeviceToEnv: «TTS_DEVICE» без «=» не стирается (регэксп требует =)'),
    ('app_null_gpu',
     '',
     'le._applyDeviceToEnv(null, "gpu")',
     '"TTS_DEVICE=cuda"',
     'positive: _applyDeviceToEnv(null, gpu) → «TTS_DEVICE=cuda» (null коэрсится в пустую строку)'),
    ('app_mode_upper_CPU',
     '',
     'le._applyDeviceToEnv("TTS_DEVICE=cpu\\nA=1", "CPU")',
     '"A=1"',
     'as-is: _applyDeviceToEnv: режим «CPU» в верхнем регистре сравнивается чувствительно к регистру и ведёт себя как auto — стирает, ничего не добавляет'),
    ('app_cpu_idempotent',
     '',
     'le._applyDeviceToEnv(le._applyDeviceToEnv("A=1", "cpu"), "cpu")',
     '"A=1\\nTTS_DEVICE=cpu\\nCUDA_VISIBLE_DEVICES="',
     'positive: _applyDeviceToEnv: двойное применение cpu идемпотентно — ровно две device-строки, без дублей'),
    ('ak_translate_other',
     '',
     'le.artifactKind("translate/other")',
     '"safetensors"',
     'negative: artifactKind: «translate/other» без префикса models-- → safetensors, а не nllb-repo'),
    ('ak_seamless_exact_arch',
     'st.state.artifacts = [{ path: "st/x", arch: "seamless_m4t" }];',
     'le.artifactKind("st/x")',
     '"seamless-st"',
     'boundary: artifactKind: arch ровно «seamless_m4t» (граница startsWith) → seamless-st'),
    ('ak_seamless_arch_case',
     'st.state.artifacts = [{ path: "st/x", arch: "Seamless_M4T" }];',
     'le.artifactKind("st/x")',
     '"safetensors"',
     'as-is: artifactKind: arch «Seamless_M4T» → safetensors — сравнение arch чувствительно к регистру'),
    ('ak_st_found_no_arch',
     'st.state.artifacts = [{ path: "st/x" }];',
     'le.artifactKind("st/x")',
     '"safetensors"',
     'negative: artifactKind: артефакт найден, но без поля arch → safetensors'),
    ('ak_gguf_sttVariant_empty',
     'st.state.models = [{ path: "m.gguf", ggufMeta: { sttVariant: "" } }];',
     'le.artifactKind("m.gguf")',
     '"llm-gguf"',
     'boundary: artifactKind: ggufMeta.sttVariant «» (falsy) → llm-gguf'),
    ('ak_gguf_sttVariant_empty_neg',
     'st.state.models = [{ path: "m.gguf", ggufMeta: { sttVariant: "gigaam" } }];',
     'le.artifactKind("m.gguf")',
     '"asr-gguf"',
     'positive: artifactKind: ggufMeta.sttVariant «gigaam» (truthy) → asr-gguf — пара к пустому sttVariant'),
    ('ak_moonshine_capital',
     '',
     'le.artifactKind("Moonshine/base")',
     '"safetensors"',
     'as-is: artifactKind: «Moonshine/base» → safetensors — префиксы чувствительны к регистру, тогда как суффикс .gguf — нет'),
    ('ak_number',
     '',
     'le.artifactKind(123)',
     '"safetensors"',
     'negative: artifactKind(123) → safetensors (число стрингифицируется, не .gguf, в артефактах нет)'),
    ('bl_prefix_mid_name',
     '',
     'le.backupLabel("/a/foo.start-server.sh.bak.x")',
     '"foo.x"',
     'as-is: backupLabel: префикс, найденный в середине имени, вырезается — replace не заякорен к началу'),
    ('bl_undefined',
     '',
     'le.backupLabel(undefined)',
     '"undefined"',
     'as-is: backupLabel(undefined) → «undefined» (String()-коэрсия, не бросает)'),
    ('bl_trailing_slash',
     '',
     'le.backupLabel("/a/b/")',
     '""',
     'negative: backupLabel: путь с завершающим слэшем → «» (последний сегмент пуст)'),
    ('bp_null',
     '',
     'le.backupPath(null)',
     '{"__threw":"Cannot read properties of null (reading \'path\')"}',
     'as-is: backupPath(null) бросает TypeError — не строка, читается .path у null'),
    ('bp_object_no_path',
     '',
     'String(le.backupPath({ label: "L" }))',
     '"undefined"',
     'negative: backupPath({label}) без path → undefined (пин через String(), JSON выкинул бы ключ)'),
    ('bdl_label_absent',
     '',
     'le.backupDisplayLabel({ path: "/a/start-server.sh.bak.foo" })',
     '"foo"',
     'positive: backupDisplayLabel: ключ label ОТСУТСТВУЕТ (обычная форма бэкенда) → лейбл из пути'),
    ('bcl_short_time',
     '',
     'le.backupCreatedLabel("/a/start-server.sh.bak.20260901-12345")',
     '"20260901-12345"',
     'boundary: backupCreatedLabel: время из 5 цифр (ниже порога 6) → лейбл как есть'),
    ('bcl_no_calendar_check',
     '',
     'le.backupCreatedLabel("/a/start-server.sh.bak.99999999-999999")',
     '"9999-99-99 99:99:99"',
     'as-is: backupCreatedLabel: календарь не валидируется — 99999999-999999 форматируется в «9999-99-99 99:99:99»'),
    ('rr_fallback_fresh_each_call',
     '',
     'le.runnerRegistry() === le.runnerRegistry()',
     'false',
     'negative: runnerRegistry: фолбэк — новый массив на каждый вызов (=== false), пара к rr_provided_same_ref'),
]

_fail = []


def check(cond, msg):
    print(("  ok  " if cond else " FAIL ") + msg)
    if not cond:
        _fail.append(msg)


def main():
    if len(PINS) < 40:
        print(f"js llama-edit FAILED: всего {len(PINS)} пинов — снимок пуст или урезан")
        return 1
    node = find_node()
    if node is None:
        print("js llama-edit: SKIPPED — node не найден ни в PATH, ни у менеджеров версий: " + ", ".join(node_search_paths()))
        return 0
    ids = [p[0] for p in PINS]
    dup = {i for i in ids if ids.count(i) > 1}
    if dup:
        print(f"js llama-edit FAILED: повторяющиеся id пинов: {sorted(dup)}")
        return 1
    def blocks(pins, sink):
        return [f"try {{ reset(); {setup}\n  {sink}[{json.dumps(pid)}] = {expr}; }} catch (e) {{ {sink}[{json.dumps(pid)}] = {{ __threw: String(e && e.message || e) }}; }}"
                for pid, setup, expr, _exp, _msg in pins]
    # Каждый пин обязан быть независим от соседей: reset() перед ним для того и
    # стоит. Доказывается это здесь же — весь набор прогоняется ВТОРОЙ раз в
    # обратном порядке, и значения должны совпасть. Без этой проверки пин может
    # проходить из-за состояния, оставленного предыдущим (так и было: два пина
    # про «порт не задан» зеленели лишь потому, что шли раньше открытия ячейки).
    probe = (PREAMBLE + "\n".join(blocks(PINS, "out")) + "\nconst rev = {};\n"
             + "\n".join(blocks(list(reversed(PINS)), "rev")).replace("out[", "rev[")
             + "\nconsole.log(JSON.stringify({ out, rev })); process.exit(0);\n")
    harness = ROOT / "scripts" / "_js_harness.mjs"
    probe_path = ROOT / "scripts" / ".probe_js_llama_edit.tmp.mjs"
    probe_path.write_text(probe)
    try:
        env = {**os.environ, "JS_ROOT": str(ROOT / "static" / "js"), "JS_STUBS": STUBS,
               "LANG": "en_US.UTF-8", "LC_ALL": "en_US.UTF-8", "TZ": "UTC"}
        run = subprocess.run(
            [node, "--import", f"data:text/javascript,import {{ register }} from 'node:module'; register('{harness.as_uri()}');",
             str(probe_path)], capture_output=True, text=True, env=env, cwd=ROOT, timeout=120)
    finally:
        probe_path.unlink(missing_ok=True)
    if run.returncode != 0:
        print(run.stdout); print(run.stderr)
        print("js llama-edit FAILED: node вышел с кодом %d" % run.returncode)
        return 1
    both = json.loads(run.stdout.strip().splitlines()[-1])
    got, rev = both["out"], both["rev"]
    for pid, _s, _e, _x, _m in PINS:
        if got.get(pid, "\0missing") != rev.get(pid, "\0missing"):
            _fail.append(f"пин {pid} зависит от порядка: прямой прогон {json.dumps(got.get(pid), ensure_ascii=False)[:120]}, "
                         f"обратный {json.dumps(rev.get(pid), ensure_ascii=False)[:120]}")
    section = ""
    for pid, _setup, _expr, expected, msg in PINS:
        head = pid.split("_", 1)[0]
        if head != section:
            section = head
            print(f"{section}:")
        want = json.loads(expected)
        have = got.get(pid, {"__missing": True})
        ok = have == want
        check(ok, msg if ok else f"{msg}\n        ожидалось {json.dumps(want, ensure_ascii=False)[:300]}\n        получено  {json.dumps(have, ensure_ascii=False)[:300]}")
    print(f"порядок: {len(PINS)} пинов дают те же значения в обратном порядке" if not _fail else "")
    print()
    if _fail:
        print(f"FAILED ({len(_fail)}):")
        for f in _fail:
            print("  - " + f.splitlines()[0])
        return 1
    print(f"js llama-edit OK: настоящий модуль в node, {len(PINS)} пинов редактора ячейки значениями")
    return 0


if __name__ == "__main__":
    sys.exit(main())
